[package]
name = "sunspec-modbus-codec"
version = "0.1.0"
edition = "2024"

[dependencies]
heapless = "0.9.3"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["time"] }
tokio-modbus = { version = "*", default-features = false, features = ["tcp-server"] }

[build-dependencies]
cbindgen = "0.29.4"
