[workspace]
resolver = "3"
members = [
    "crates/sunspec-modbus-lib-rs",
    "crates/sunspec-modbus-lib-static",
    "crates/sunspec-gen"
]

[profile.dev]
lto = true
debug = true
strip = false
panic = "abort"

[profile.release]
lto = true
debug = true
strip = false
panic = "abort"

[workspace.dependencies]
bytemuck = "1.25.2"
codegen = "0.3.0"
glob = "0.3.3"
heck = "0.5.0"
serde = "1.0.228"
serde_json = "1.0.150"
typify = "0.7.0"
schemars = "0.8"
rustfmt-wrapper = "0.2.1"
tokio = { version = "1.52.3", features = ["time"] }
tokio-modbus = { version = "0.17.0", default-features = false, features = ["tcp-server"] }
cbindgen = "0.29.4"
rand = "0.10.2"
