[workspace]
resolver = "3"
members = [
    "crates/sunspec-modbus-lib-rs",
    "crates/sunspec-modbus-lib-static",
    "crates/sunspec-modbus-derive",
    "crates/sunspec-gen"
]
# The output of sunspec-gen is committed to the repository - it only needs to be rebuilt if the models or codegen are changing.
default-members = [
    "crates/sunspec-modbus-lib-rs",
    "crates/sunspec-modbus-lib-static",
    "crates/sunspec-modbus-derive",
]

[profile.dev]
lto = true
debug = true
strip = false
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
debug = false
strip = true
panic = "abort"

[workspace.package]
version = "1.0.0-SNAPSHOT"
license = "Apache-2.0"
repository = "https://github.com/cuprous-au/sunspec-modbus-codec"
readme = "README.md"

[workspace.dependencies]
# Internal workspace dependencies
sunspec-modbus-derive = { path = "crates/sunspec-modbus-derive", version = "1.0.0-SNAPSHOT" }

# External dependencies
bytemuck = "1.25.2"
cbindgen = "0.29.4" # only used as a build dependency
codegen = "0.3.0"
embassy-executor = { version = "0.10.0", features = ["platform-std", "executor-thread"]}
embassy-net = "0.9.1"
embassy-net-tuntap = "0.1.1"
embassy-time = { version = "0.5.1", features = ["std"] }
embedded-io-async = "0.7.0"
glob = "0.3.3"
heapless = "0.9.3"
heck = "0.5.0"
hex = "0.4.3"
proc-macro2 = "1.0.107"
quote = "1.0.47"
rand = "0.10.2"
rmodbus = { version = "0.12.2", features = ["heapless"] }
rustfmt-wrapper = "0.2.1"
schemars = "0.8"
serde = "1.0.228"
serde_json = "1.0.150"
static_cell = "2.1.1"
syn = "2.0.119"
tokio = { version = "1.52.3", features = ["time"] }
tokio-modbus = { version = "0.17.0", default-features = false, features = ["tcp-server"] }
typify = "0.7.0"
