[package]
name = "sunspec-modbus-lib-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
bytemuck = { workspace = true }
heapless = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["time"] }
tokio-modbus = { version = "*", default-features = false, features = ["tcp-server"] }
