[package]
name = "sunspec-modbus-lib-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib"]

[dependencies]
bytemuck = "1.25.2"
heapless = "0.9.3"

[dev-dependencies]
tokio = { version = "1.52.3", features = ["time"] }
tokio-modbus = { version = "*", default-features = false, features = ["tcp-server"] }
