// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::SunspecAdapter;
use core::ffi::c_void;
use sunspec_modbus_lib_rs::ModbusException;
use sunspec_modbus_lib_rs::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use sunspec_modbus_lib_rs::cursor::Cursor;
use sunspec_modbus_lib_rs::model::{ModelSpec, StaticModelSpec};
use sunspec_modbus_lib_rs::sunspec::models::model_807::*;

#[repr(C)]
pub struct Model807CallbackAdapter {
    context: *mut c_void,
    /// String Index (Idx)
    ///
    /// Index of the string within the bank.
    ///
    /// Indices are one-based.
    string_index_callback: extern "C" fn(*const c_void) -> u16,
    /// Module Count (NMod)
    ///
    /// Number of modules in this string.
    module_count_callback: extern "C" fn(*const c_void) -> u16,
    /// Connected Module Count (NModCon)
    ///
    /// Number of electrically connected modules in this string.
    connected_module_count_callback: extern "C" fn(*const c_void) -> u16,
    /// Max Module Voltage (ModVMax)
    ///
    /// Maximum voltage for all modules in the string.
    ///
    /// Measurement.
    max_module_voltage_callback: extern "C" fn(*const c_void) -> u16,
    /// Max Module Voltage Module (ModVMaxMod)
    ///
    /// Module with the maximum voltage.
    max_module_voltage_module_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Min Module Voltage (ModVMin)
    ///
    /// Minimum voltage for all modules in the string.
    ///
    /// Measurement.
    min_module_voltage_callback: extern "C" fn(*const c_void) -> u16,
    /// Min Module Voltage Module (ModVMinMod)
    ///
    /// Module with the minimum voltage.
    min_module_voltage_module_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Average Module Voltage (ModVAvg)
    ///
    /// Average voltage for all modules in the string.
    ///
    /// Calculation based on measurements.
    average_module_voltage_callback: extern "C" fn(*const c_void) -> u16,
    /// Max Cell Voltage (CellVMax)
    ///
    /// Maximum voltage for all cells in the string.
    ///
    /// Measurement.
    max_cell_voltage_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Max Cell Voltage Module (CellVMaxMod)
    ///
    /// Module containing the cell with the maximum voltage.
    max_cell_voltage_module_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Max Cell Voltage Stack (CellVMaxStk)
    ///
    /// Stack containing the cell with the maximum voltage.
    max_cell_voltage_stack_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Min Cell Voltage (CellVMin)
    ///
    /// Minimum voltage for all cells in the string.
    ///
    /// Measurement.
    min_cell_voltage_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Min Cell Voltage Module (CellVMinMod)
    ///
    /// Module containing the cell with the minimum voltage.
    min_cell_voltage_module_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Min Cell Voltage Stack (CellVMinStk)
    ///
    /// Stack containing the cell with the minimum voltage.
    min_cell_voltage_stack_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Average Cell Voltage (CellVAvg)
    ///
    /// Average voltage for all cells in the string.
    ///
    /// Calculation based on measurements.
    average_cell_voltage_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Max Temperature (TmpMax)
    ///
    /// Maximum electrolyte temperature for all modules in the string.
    ///
    /// Measurement.
    max_temperature_callback: extern "C" fn(*const c_void) -> i16,
    /// Max Temperature Module (TmpMaxMod)
    ///
    /// Module with the maximum temperature.
    max_temperature_module_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Min Temperature (TmpMin)
    ///
    /// Minimum electrolyte temperature for all modules in the string.
    ///
    /// Measurement.
    min_temperature_callback: extern "C" fn(*const c_void) -> i16,
    /// Min Temperature Module (TmpMinMod)
    ///
    /// Module with the minimum temperature.
    min_temperature_module_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Average Temperature (TmpAvg)
    ///
    /// Average electrolyte temperature for all modules in the string.
    ///
    /// Calculation based on measurements.
    average_temperature_callback: extern "C" fn(*const c_void) -> i16,
    /// String Event 1 (Evt1)
    ///
    /// Alarms, warnings and status values.
    string_event_1_callback: extern "C" fn(*const c_void) -> u32,
    /// String Event 2 (Evt2)
    ///
    /// Alarms, warnings and status values.
    string_event_2_callback: extern "C" fn(*const c_void) -> u32,
    /// Vendor Event Bitfield 1 (EvtVnd1)
    ///
    /// Vendor defined events.
    vendor_event_bitfield_1_callback: extern "C" fn(*const c_void) -> u32,
    /// Vendor Event Bitfield 2 (EvtVnd2)
    ///
    /// Vendor defined events.
    vendor_event_bitfield_2_callback: extern "C" fn(*const c_void) -> u32,
    /// ModV_SF
    mod_v_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// CellV_SF
    ///
    /// Scale factor for voltage.
    cell_v_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// Tmp_SF
    ///
    /// Scale factor for temperature.
    tmp_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// SoC_SF
    ///
    /// Scale factor for state of charge.
    so_c_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// OCV_SF
    ///
    /// Scale factor for open circuit voltage.
    ocv_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// Module Index (ModIdx)
    ///
    /// Index of the module within the string.
    module_module_index_callback: extern "C" fn(*const c_void) -> u16,
    /// Stack Count (ModNStk)
    ///
    /// Number of stacks in this module.
    module_stack_count_callback: extern "C" fn(*const c_void) -> u16,
    /// Module Status (ModSt)
    ///
    /// Current status of the module.
    module_module_status_callback: extern "C" fn(*const c_void) -> u32,
    /// Module State of Charge (ModSoC)
    ///
    /// State of charge for this module.
    module_module_state_of_charge_callback: extern "C" fn(*const c_void) -> u16,
    /// Open Circuit Voltage (ModOCV)
    ///
    /// Open circuit voltage for this module.
    module_open_circuit_voltage_callback: extern "C" fn(*const c_void) -> u16,
    /// External Voltage (ModV)
    ///
    /// External voltage fo this module.
    module_external_voltage_callback: extern "C" fn(*const c_void) -> u16,
    /// Maximum Cell Voltage (ModCellVMax)
    ///
    /// Maximum voltage for all cells in this module.
    module_maximum_cell_voltage_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Max Cell Voltage Cell (ModCellVMaxCell)
    ///
    /// Cell with the maximum cell voltage.
    module_max_cell_voltage_cell_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Minimum Cell Voltage (ModCellVMin)
    ///
    /// Minimum voltage for all cells in this module.
    module_minimum_cell_voltage_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Min Cell Voltage Cell (ModCellVMinCell)
    ///
    /// Cell with the minimum cell voltage.
    module_min_cell_voltage_cell_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Average Cell Voltage (ModCellVAvg)
    ///
    /// Average voltage for all cells in this module.
    module_average_cell_voltage_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Anolyte Temperature (ModAnoTmp)
    module_anolyte_temperature_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Catholyte Temperature (ModCatTmp)
    module_catholyte_temperature_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Contactor Status (ModConSt)
    module_contactor_status_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Module Event 1 (ModEvt1)
    ///
    /// Alarms, warnings and status values.
    module_module_event_1_callback: extern "C" fn(*const c_void) -> u32,
    /// Module Event 2 (ModEvt2)
    ///
    /// Alarms, warnings and status values.
    module_module_event_2_callback: extern "C" fn(*const c_void) -> u32,
    /// Connection Failure Reason (ModConFail)
    module_connection_failure_reason_callback:
        Option<extern "C" fn(*const c_void) -> Model807ModConFail>,
    /// Enable/Disable Module (ModSetEna)
    ///
    /// Enables and disables the module.
    module_enable_disable_module_callback:
        Option<extern "C" fn(*const c_void) -> Model807ModSetEna>,
    /// Enable/Disable Module (ModSetEna)
    ///
    /// Enables and disables the module.
    set_module_enable_disable_module_callback:
        Option<extern "C" fn(Model807ModSetEna, *mut c_void)>,
    /// Connect/Disconnect Module  (ModSetCon)
    ///
    /// Connects and disconnects the module.
    module_connect_disconnect_module_callback:
        Option<extern "C" fn(*const c_void) -> Model807ModSetCon>,
    /// Connect/Disconnect Module  (ModSetCon)
    ///
    /// Connects and disconnects the module.
    set_module_connect_disconnect_module_callback:
        Option<extern "C" fn(Model807ModSetCon, *mut c_void)>,
    /// Disabled Reason (ModDisRsn)
    ///
    /// Reason why the module is currently disabled.
    module_disabled_reason_callback: Option<extern "C" fn(*const c_void) -> Model807ModDisRsn>,
}

impl ReadAdapter for Model807CallbackAdapter {
    fn string_index(&self) -> u16 {
        (self.string_index_callback)(self.context)
    }

    fn module_count(&self) -> u16 {
        (self.module_count_callback)(self.context)
    }

    fn connected_module_count(&self) -> u16 {
        (self.connected_module_count_callback)(self.context)
    }

    fn max_module_voltage(&self) -> u16 {
        (self.max_module_voltage_callback)(self.context)
    }

    fn max_module_voltage_module(&self) -> Option<u16> {
        self.max_module_voltage_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn min_module_voltage(&self) -> u16 {
        (self.min_module_voltage_callback)(self.context)
    }

    fn min_module_voltage_module(&self) -> Option<u16> {
        self.min_module_voltage_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn average_module_voltage(&self) -> u16 {
        (self.average_module_voltage_callback)(self.context)
    }

    fn max_cell_voltage(&self) -> Option<u16> {
        self.max_cell_voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn max_cell_voltage_module(&self) -> Option<u16> {
        self.max_cell_voltage_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn max_cell_voltage_stack(&self) -> Option<u16> {
        self.max_cell_voltage_stack_callback
            .map(|callback| (callback)(self.context))
    }

    fn min_cell_voltage(&self) -> Option<u16> {
        self.min_cell_voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn min_cell_voltage_module(&self) -> Option<u16> {
        self.min_cell_voltage_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn min_cell_voltage_stack(&self) -> Option<u16> {
        self.min_cell_voltage_stack_callback
            .map(|callback| (callback)(self.context))
    }

    fn average_cell_voltage(&self) -> Option<u16> {
        self.average_cell_voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn max_temperature(&self) -> i16 {
        (self.max_temperature_callback)(self.context)
    }

    fn max_temperature_module(&self) -> Option<u16> {
        self.max_temperature_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn min_temperature(&self) -> i16 {
        (self.min_temperature_callback)(self.context)
    }

    fn min_temperature_module(&self) -> Option<u16> {
        self.min_temperature_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn average_temperature(&self) -> i16 {
        (self.average_temperature_callback)(self.context)
    }

    fn string_event_1(&self) -> u32 {
        (self.string_event_1_callback)(self.context)
    }

    fn string_event_2(&self) -> u32 {
        (self.string_event_2_callback)(self.context)
    }

    fn vendor_event_bitfield_1(&self) -> u32 {
        (self.vendor_event_bitfield_1_callback)(self.context)
    }

    fn vendor_event_bitfield_2(&self) -> u32 {
        (self.vendor_event_bitfield_2_callback)(self.context)
    }

    fn mod_v_sf(&self) -> i16 {
        (self.mod_v_sf_callback)(self.context)
    }

    fn cell_v_sf(&self) -> i16 {
        (self.cell_v_sf_callback)(self.context)
    }

    fn tmp_sf(&self) -> i16 {
        (self.tmp_sf_callback)(self.context)
    }

    fn so_c_sf(&self) -> i16 {
        (self.so_c_sf_callback)(self.context)
    }

    fn ocv_sf(&self) -> i16 {
        (self.ocv_sf_callback)(self.context)
    }

    fn module_module_index(&self) -> u16 {
        (self.module_module_index_callback)(self.context)
    }

    fn module_stack_count(&self) -> u16 {
        (self.module_stack_count_callback)(self.context)
    }

    fn module_module_status(&self) -> u32 {
        (self.module_module_status_callback)(self.context)
    }

    fn module_module_state_of_charge(&self) -> u16 {
        (self.module_module_state_of_charge_callback)(self.context)
    }

    fn module_open_circuit_voltage(&self) -> u16 {
        (self.module_open_circuit_voltage_callback)(self.context)
    }

    fn module_external_voltage(&self) -> u16 {
        (self.module_external_voltage_callback)(self.context)
    }

    fn module_maximum_cell_voltage(&self) -> Option<u16> {
        self.module_maximum_cell_voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_max_cell_voltage_cell(&self) -> Option<u16> {
        self.module_max_cell_voltage_cell_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_minimum_cell_voltage(&self) -> Option<u16> {
        self.module_minimum_cell_voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_min_cell_voltage_cell(&self) -> Option<u16> {
        self.module_min_cell_voltage_cell_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_average_cell_voltage(&self) -> Option<u16> {
        self.module_average_cell_voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_anolyte_temperature(&self) -> Option<u16> {
        self.module_anolyte_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_catholyte_temperature(&self) -> Option<u16> {
        self.module_catholyte_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_contactor_status(&self) -> Option<u32> {
        self.module_contactor_status_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_module_event_1(&self) -> u32 {
        (self.module_module_event_1_callback)(self.context)
    }

    fn module_module_event_2(&self) -> u32 {
        (self.module_module_event_2_callback)(self.context)
    }

    fn module_connection_failure_reason(&self) -> Option<ModConFail> {
        self.module_connection_failure_reason_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_enable_disable_module(&self) -> Option<ModSetEna> {
        self.module_enable_disable_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_connect_disconnect_module(&self) -> Option<ModSetCon> {
        self.module_connect_disconnect_module_callback
            .map(|callback| (callback)(self.context))
    }

    fn module_disabled_reason(&self) -> Option<ModDisRsn> {
        self.module_disabled_reason_callback
            .map(|callback| (callback)(self.context))
    }
}

impl WriteAdapter for Model807CallbackAdapter {
    /// Enable/Disable Module (ModSetEna)
    ///
    /// Enables and disables the module.
    fn set_module_enable_disable_module(&mut self, value: ModSetEna) {
        if let Some(callback) = self.set_module_enable_disable_module_callback {
            (callback)(value, self.context);
        };
    }

    /// Connect/Disconnect Module  (ModSetCon)
    ///
    /// Connects and disconnects the module.
    fn set_module_connect_disconnect_module(&mut self, value: ModSetCon) {
        if let Some(callback) = self.set_module_connect_disconnect_module_callback {
            (callback)(value, self.context);
        };
    }
}

/// C-FFI dispatch descriptor for SunSpec model 807. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_807: StaticModelSpec = StaticModelSpec {
    id: 807,
    length: model_807_c_length,
    writable: true,
    visit_read: model_807_c_visit_read,
    visit_write: model_807_c_visit_write,
};

fn model_807_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model807).model_length()
}

/// # Safety
/// `adapter` must be null or point to a live `Model807CallbackAdapter`, valid for the
/// duration of the call.
unsafe fn model_807_c_visit_read(
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model807;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *const Model807CallbackAdapter).as_ref() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_807_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_807_c_visit_write(
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let model = Model807;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *mut Model807CallbackAdapter).as_mut() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| match adapter {
        Some(adapter) => model.traverse_points_write(adapter, &buffer.slice(from, len), offset),
        None => Err(ModbusException::IllegalDataAddress),
    });
}

/// Build a [`SunspecAdapter`] for model 807 backed by a callback adapter.
#[unsafe(no_mangle)]
pub extern "C" fn sunspec_model_807_callback(
    adapter: *mut Model807CallbackAdapter,
) -> SunspecAdapter {
    SunspecAdapter {
        model_spec: &SUNSPEC_MODEL_807,
        adapter: adapter as *mut c_void,
    }
}
