// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::SunspecAdapter;
use core::ffi::{CStr, c_char, c_void};
use sunspec_modbus_lib_rs::ModbusException;
use sunspec_modbus_lib_rs::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use sunspec_modbus_lib_rs::cursor::Cursor;
use sunspec_modbus_lib_rs::model::{ModelSpec, StaticModelSpec};
use sunspec_modbus_lib_rs::sunspec::models::model_16::*;

#[repr(C)]
pub struct Model16CallbackAdapter {
    context: *mut c_void,
    /// Name (Nam)
    ///
    /// Interface name. (8 chars)
    name_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// Name (Nam)
    ///
    /// Interface name. (8 chars)
    set_name_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// Config (Cfg)
    ///
    /// Force IPv4 configuration method
    config_callback: extern "C" fn(*const c_void) -> Model16Cfg,
    /// Control (Ctl)
    ///
    /// Configure use of services
    control_callback: extern "C" fn(*const c_void) -> u16,
    /// Control (Ctl)
    ///
    /// Configure use of services
    set_control_callback: extern "C" fn(u16, *mut c_void),
    /// Address (Addr)
    ///
    /// IP address
    address_callback: extern "C" fn(*const c_void) -> *const c_char,
    /// Address (Addr)
    ///
    /// IP address
    set_address_callback: extern "C" fn(*const c_char, *mut c_void),
    /// Netmask (Msk)
    ///
    /// Netmask
    netmask_callback: extern "C" fn(*const c_void) -> *const c_char,
    /// Netmask (Msk)
    ///
    /// Netmask
    set_netmask_callback: extern "C" fn(*const c_char, *mut c_void),
    /// Gateway (Gw)
    ///
    /// Gateway IP address
    gateway_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// Gateway (Gw)
    ///
    /// Gateway IP address
    set_gateway_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// DNS1 (DNS1)
    ///
    /// 32 bit IP address of DNS server
    dns1_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// DNS1 (DNS1)
    ///
    /// 32 bit IP address of DNS server
    set_dns1_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// DNS2 (DNS2)
    ///
    /// 32 bit IP address of DNS server
    dns2_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// DNS2 (DNS2)
    ///
    /// 32 bit IP address of DNS server
    set_dns2_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// MAC (MAC)
    ///
    /// IEEE MAC address of this interface
    mac_callback: Option<extern "C" fn(*const c_void) -> *const u8>,
    /// Link Control (LnkCtl)
    ///
    /// Link control flags
    link_control_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Link Control (LnkCtl)
    ///
    /// Link control flags
    set_link_control_callback: Option<extern "C" fn(u16, *mut c_void)>,
}

impl ReadAdapter for Model16CallbackAdapter {
    fn name(&self) -> Option<&CStr> {
        self.name_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn config(&self) -> Cfg {
        (self.config_callback)(self.context)
    }

    fn control(&self) -> u16 {
        (self.control_callback)(self.context)
    }

    fn address(&self) -> &CStr {
        unsafe { CStr::from_ptr((self.address_callback)(self.context)) }
    }

    fn netmask(&self) -> &CStr {
        unsafe { CStr::from_ptr((self.netmask_callback)(self.context)) }
    }

    fn gateway(&self) -> Option<&CStr> {
        self.gateway_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn dns1(&self) -> Option<&CStr> {
        self.dns1_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn dns2(&self) -> Option<&CStr> {
        self.dns2_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn mac(&self) -> Option<&[u8; 6]> {
        self.mac_callback
            .map(|callback| unsafe { &*((callback)(self.context) as *const [u8; 6]) })
    }

    fn link_control(&self) -> Option<u16> {
        self.link_control_callback
            .map(|callback| (callback)(self.context))
    }
}

impl WriteAdapter for Model16CallbackAdapter {
    /// Name (Nam)
    ///
    /// Interface name. (8 chars)
    fn set_name(&mut self, value: &CStr) {
        if let Some(callback) = self.set_name_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// Control (Ctl)
    ///
    /// Configure use of services
    fn set_control(&mut self, value: u16) {
        (self.set_control_callback)(value, self.context);
    }

    /// Address (Addr)
    ///
    /// IP address
    fn set_address(&mut self, value: &CStr) {
        (self.set_address_callback)(value.as_ptr(), self.context);
    }

    /// Netmask (Msk)
    ///
    /// Netmask
    fn set_netmask(&mut self, value: &CStr) {
        (self.set_netmask_callback)(value.as_ptr(), self.context);
    }

    /// Gateway (Gw)
    ///
    /// Gateway IP address
    fn set_gateway(&mut self, value: &CStr) {
        if let Some(callback) = self.set_gateway_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// DNS1 (DNS1)
    ///
    /// 32 bit IP address of DNS server
    fn set_dns1(&mut self, value: &CStr) {
        if let Some(callback) = self.set_dns1_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// DNS2 (DNS2)
    ///
    /// 32 bit IP address of DNS server
    fn set_dns2(&mut self, value: &CStr) {
        if let Some(callback) = self.set_dns2_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// Link Control (LnkCtl)
    ///
    /// Link control flags
    fn set_link_control(&mut self, value: u16) {
        if let Some(callback) = self.set_link_control_callback {
            (callback)(value, self.context);
        };
    }
}

/// C-FFI dispatch descriptor for SunSpec model 16. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_16: StaticModelSpec = StaticModelSpec {
    id: 16,
    length: model_16_c_length,
    writable: true,
    visit_read: model_16_c_visit_read,
    visit_write: model_16_c_visit_write,
};

fn model_16_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model16).model_length()
}

/// # Safety
/// `adapter` must be null or point to a live `Model16CallbackAdapter`, valid for the
/// duration of the call.
unsafe fn model_16_c_visit_read(
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model16;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *const Model16CallbackAdapter).as_ref() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_16_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_16_c_visit_write(
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let model = Model16;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *mut Model16CallbackAdapter).as_mut() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| match adapter {
        Some(adapter) => model.traverse_points_write(adapter, &buffer.slice(from, len), offset),
        None => Err(ModbusException::IllegalDataAddress),
    });
}

/// Build a [`SunspecAdapter`] for model 16 backed by a callback adapter.
#[unsafe(no_mangle)]
pub extern "C" fn sunspec_model_16_callback(
    adapter: *mut Model16CallbackAdapter,
) -> SunspecAdapter {
    SunspecAdapter {
        model_spec: &SUNSPEC_MODEL_16,
        adapter: adapter as *mut c_void,
    }
}
