// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::SunspecAdapter;
use core::ffi::c_void;
use sunspec_modbus_lib_rs::ModbusException;
use sunspec_modbus_lib_rs::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use sunspec_modbus_lib_rs::cursor::Cursor;
use sunspec_modbus_lib_rs::model::{ModelSpec, StaticModelSpec};
use sunspec_modbus_lib_rs::sunspec::models::model_15::*;

#[repr(C)]
pub struct Model15CallbackAdapter {
    context: *mut c_void,
    /// Clear (Clr)
    ///
    /// Write a "1" to clear all counters
    clear_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Clear (Clr)
    ///
    /// Write a "1" to clear all counters
    set_clear_callback: Option<extern "C" fn(u16, *mut c_void)>,
    /// Input Count (InCnt)
    ///
    /// Number of bytes received
    input_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Input Unicast Count (InUcCnt)
    ///
    /// Number of Unicast packets received
    input_unicast_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Input Non-Unicast Count (InNUcCnt)
    ///
    /// Number of non-Unicast packets received
    input_non_unicast_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Input Discarded Count (InDscCnt)
    ///
    /// Number of inbound packets received on the interface but discarded
    input_discarded_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Input Error Count (InErrCnt)
    ///
    /// Number of inbound packets that contain errors (excluding discards)
    input_error_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Input Unknown Count (InUnkCnt)
    ///
    /// Number of inbound packets with unknown protocol
    input_unknown_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Output Count (OutCnt)
    ///
    /// Total number of bytes transmitted on this interface
    output_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Output Unicast Count (OutUcCnt)
    ///
    /// Number of Unicast packets transmitted
    output_unicast_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Output Non-Unicast Count (OutNUcCnt)
    ///
    /// Number of Non-Unicast packets transmitted
    output_non_unicast_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Output Discarded Count (OutDscCnt)
    ///
    /// Number of Discarded output packets
    output_discarded_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Output Error Count (OutErrCnt)
    ///
    /// Number of outbound error packets
    output_error_count_callback: Option<extern "C" fn(*const c_void) -> u32>,
}

impl ReadAdapter for Model15CallbackAdapter {
    fn clear(&self) -> Option<u16> {
        self.clear_callback.map(|callback| (callback)(self.context))
    }

    fn input_count(&self) -> Option<u32> {
        self.input_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn input_unicast_count(&self) -> Option<u32> {
        self.input_unicast_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn input_non_unicast_count(&self) -> Option<u32> {
        self.input_non_unicast_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn input_discarded_count(&self) -> Option<u32> {
        self.input_discarded_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn input_error_count(&self) -> Option<u32> {
        self.input_error_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn input_unknown_count(&self) -> Option<u32> {
        self.input_unknown_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn output_count(&self) -> Option<u32> {
        self.output_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn output_unicast_count(&self) -> Option<u32> {
        self.output_unicast_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn output_non_unicast_count(&self) -> Option<u32> {
        self.output_non_unicast_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn output_discarded_count(&self) -> Option<u32> {
        self.output_discarded_count_callback
            .map(|callback| (callback)(self.context))
    }

    fn output_error_count(&self) -> Option<u32> {
        self.output_error_count_callback
            .map(|callback| (callback)(self.context))
    }
}

impl WriteAdapter for Model15CallbackAdapter {
    /// Clear (Clr)
    ///
    /// Write a "1" to clear all counters
    fn set_clear(&mut self, value: u16) {
        if let Some(callback) = self.set_clear_callback {
            (callback)(value, self.context);
        };
    }
}

/// C-FFI dispatch descriptor for SunSpec model 15. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_15: StaticModelSpec = StaticModelSpec {
    id: 15,
    length: model_15_c_length,
    writable: true,
    visit_read: model_15_c_visit_read,
    visit_write: model_15_c_visit_write,
};

fn model_15_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model15).model_length()
}

/// # Safety
/// `adapter` must be null or point to a live `Model15CallbackAdapter`, valid for the
/// duration of the call.
unsafe fn model_15_c_visit_read(
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model15;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *const Model15CallbackAdapter).as_ref() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_15_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_15_c_visit_write(
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let model = Model15;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *mut Model15CallbackAdapter).as_mut() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| match adapter {
        Some(adapter) => model.traverse_points_write(adapter, &buffer.slice(from, len), offset),
        None => Err(ModbusException::IllegalDataAddress),
    });
}

/// Build a [`SunspecAdapter`] for model 15 backed by a callback adapter.
#[unsafe(no_mangle)]
pub extern "C" fn sunspec_model_15_callback(
    adapter: *mut Model15CallbackAdapter,
) -> SunspecAdapter {
    SunspecAdapter {
        model_spec: &SUNSPEC_MODEL_15,
        adapter: adapter as *mut c_void,
    }
}
