// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::SunspecAdapter;
use core::ffi::{CStr, c_char, c_void};
use sunspec_modbus_lib_rs::ModbusException;
use sunspec_modbus_lib_rs::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use sunspec_modbus_lib_rs::cursor::Cursor;
use sunspec_modbus_lib_rs::model::{ModelSpec, StaticModelSpec};
use sunspec_modbus_lib_rs::sunspec::models::model_63001::*;

#[repr(C)]
pub struct Model63001CallbackAdapter {
    context: *mut c_void,
    /// sunssf_1
    sunssf_1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// sunssf_2
    sunssf_2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// sunssf_3
    sunssf_3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// sunssf_4
    sunssf_4_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_1
    int16_1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_2
    int16_2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_3
    int16_3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_4
    int16_4_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_4
    set_int16_4_callback: Option<extern "C" fn(i16, *mut c_void)>,
    /// int16_5
    int16_5_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_u
    int16_u_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// uint16_1
    uint16_1_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_2
    uint16_2_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_3
    uint16_3_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_4
    uint16_4_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_4
    set_uint16_4_callback: Option<extern "C" fn(u16, *mut c_void)>,
    /// uint16_5
    uint16_5_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_u
    uint16_u_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// acc16
    acc16_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// acc16_u
    acc16_u_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// enum16
    enum16_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// enum16_u
    enum16_u_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// bitfield16
    bitfield16_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// bitfield16_u
    bitfield16_u_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// int32_1
    int32_1_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// int32_2
    int32_2_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// int32_3
    int32_3_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// int32_3
    set_int32_3_callback: Option<extern "C" fn(i32, *mut c_void)>,
    /// int32_4
    int32_4_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// int32_5
    int32_5_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// int32_u
    int32_u_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// uint32_1
    uint32_1_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// uint32_2
    uint32_2_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// uint32_3
    uint32_3_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// uint32_3
    set_uint32_3_callback: Option<extern "C" fn(u32, *mut c_void)>,
    /// uint32_4
    uint32_4_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// uint32_5
    uint32_5_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// uint32_u
    uint32_u_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// acc32
    acc32_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// acc32_u
    acc32_u_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// enum32
    enum32_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// enum32_u
    enum32_u_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// bitfield32
    bitfield32_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// bitfield32_u
    bitfield32_u_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// ipaddr
    ipaddr_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// ipaddr
    set_ipaddr_callback: Option<extern "C" fn(u32, *mut c_void)>,
    /// ipaddr_u
    ipaddr_u_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// int64
    int64_callback: Option<extern "C" fn(*const c_void) -> i64>,
    /// int64
    set_int64_callback: Option<extern "C" fn(i64, *mut c_void)>,
    /// int64_u
    int64_u_callback: Option<extern "C" fn(*const c_void) -> i64>,
    /// acc64
    acc64_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// acc64_u
    acc64_u_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// ipv6addr
    ipv6addr_callback: Option<extern "C" fn(*const c_void) -> *const u16>,
    /// ipv6addr_u
    ipv6addr_u_callback: Option<extern "C" fn(*const c_void) -> *const u16>,
    /// float32
    float32_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// float32
    set_float32_callback: Option<extern "C" fn(f32, *mut c_void)>,
    /// float32_u
    float32_u_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// string
    string_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// string
    set_string_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// string_u
    string_u_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// sunssf_5
    sunssf_5_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// sunssf_6
    sunssf_6_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// sunssf_7
    sunssf_7_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// sunssf_8
    repeating_sunssf_8_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_11
    repeating_int16_11_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_11
    set_repeating_int16_11_callback: Option<extern "C" fn(i16, *mut c_void)>,
    /// int16_12
    repeating_int16_12_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// int16_u
    repeating_int16_u_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// uint16_11
    repeating_uint16_11_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_11
    set_repeating_uint16_11_callback: Option<extern "C" fn(u16, *mut c_void)>,
    /// uint16_12
    repeating_uint16_12_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_13
    repeating_uint16_13_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// uint16_u
    repeating_uint16_u_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// int32
    repeating_int32_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// int32
    set_repeating_int32_callback: Option<extern "C" fn(i32, *mut c_void)>,
    /// int32_u
    repeating_int32_u_callback: Option<extern "C" fn(*const c_void) -> i32>,
    /// uint32
    repeating_uint32_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// uint32
    set_repeating_uint32_callback: Option<extern "C" fn(u32, *mut c_void)>,
    /// uint32_u
    repeating_uint32_u_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// sunssf_9
    repeating_sunssf_9_callback: Option<extern "C" fn(*const c_void) -> i16>,
}

impl ReadAdapter for Model63001CallbackAdapter {
    fn sunssf_1(&self) -> Option<i16> {
        self.sunssf_1_callback
            .map(|callback| (callback)(self.context))
    }

    fn sunssf_2(&self) -> Option<i16> {
        self.sunssf_2_callback
            .map(|callback| (callback)(self.context))
    }

    fn sunssf_3(&self) -> Option<i16> {
        self.sunssf_3_callback
            .map(|callback| (callback)(self.context))
    }

    fn sunssf_4(&self) -> Option<i16> {
        self.sunssf_4_callback
            .map(|callback| (callback)(self.context))
    }

    fn int16_1(&self) -> Option<i16> {
        self.int16_1_callback
            .map(|callback| (callback)(self.context))
    }

    fn int16_2(&self) -> Option<i16> {
        self.int16_2_callback
            .map(|callback| (callback)(self.context))
    }

    fn int16_3(&self) -> Option<i16> {
        self.int16_3_callback
            .map(|callback| (callback)(self.context))
    }

    fn int16_4(&self) -> Option<i16> {
        self.int16_4_callback
            .map(|callback| (callback)(self.context))
    }

    fn int16_5(&self) -> Option<i16> {
        self.int16_5_callback
            .map(|callback| (callback)(self.context))
    }

    fn int16_u(&self) -> Option<i16> {
        self.int16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint16_1(&self) -> Option<u16> {
        self.uint16_1_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint16_2(&self) -> Option<u16> {
        self.uint16_2_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint16_3(&self) -> Option<u16> {
        self.uint16_3_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint16_4(&self) -> Option<u16> {
        self.uint16_4_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint16_5(&self) -> Option<u16> {
        self.uint16_5_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint16_u(&self) -> Option<u16> {
        self.uint16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn acc16(&self) -> Option<u16> {
        self.acc16_callback.map(|callback| (callback)(self.context))
    }

    fn acc16_u(&self) -> Option<u16> {
        self.acc16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn enum16(&self) -> Option<u16> {
        self.enum16_callback
            .map(|callback| (callback)(self.context))
    }

    fn enum16_u(&self) -> Option<u16> {
        self.enum16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn bitfield16(&self) -> Option<u16> {
        self.bitfield16_callback
            .map(|callback| (callback)(self.context))
    }

    fn bitfield16_u(&self) -> Option<u16> {
        self.bitfield16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn int32_1(&self) -> Option<i32> {
        self.int32_1_callback
            .map(|callback| (callback)(self.context))
    }

    fn int32_2(&self) -> Option<i32> {
        self.int32_2_callback
            .map(|callback| (callback)(self.context))
    }

    fn int32_3(&self) -> Option<i32> {
        self.int32_3_callback
            .map(|callback| (callback)(self.context))
    }

    fn int32_4(&self) -> Option<i32> {
        self.int32_4_callback
            .map(|callback| (callback)(self.context))
    }

    fn int32_5(&self) -> Option<i32> {
        self.int32_5_callback
            .map(|callback| (callback)(self.context))
    }

    fn int32_u(&self) -> Option<i32> {
        self.int32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint32_1(&self) -> Option<u32> {
        self.uint32_1_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint32_2(&self) -> Option<u32> {
        self.uint32_2_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint32_3(&self) -> Option<u32> {
        self.uint32_3_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint32_4(&self) -> Option<u32> {
        self.uint32_4_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint32_5(&self) -> Option<u32> {
        self.uint32_5_callback
            .map(|callback| (callback)(self.context))
    }

    fn uint32_u(&self) -> Option<u32> {
        self.uint32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn acc32(&self) -> Option<u32> {
        self.acc32_callback.map(|callback| (callback)(self.context))
    }

    fn acc32_u(&self) -> Option<u32> {
        self.acc32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn enum32(&self) -> Option<u32> {
        self.enum32_callback
            .map(|callback| (callback)(self.context))
    }

    fn enum32_u(&self) -> Option<u32> {
        self.enum32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn bitfield32(&self) -> Option<u32> {
        self.bitfield32_callback
            .map(|callback| (callback)(self.context))
    }

    fn bitfield32_u(&self) -> Option<u32> {
        self.bitfield32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn ipaddr(&self) -> Option<u32> {
        self.ipaddr_callback
            .map(|callback| (callback)(self.context))
    }

    fn ipaddr_u(&self) -> Option<u32> {
        self.ipaddr_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn int64(&self) -> Option<i64> {
        self.int64_callback.map(|callback| (callback)(self.context))
    }

    fn int64_u(&self) -> Option<i64> {
        self.int64_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn acc64(&self) -> Option<u64> {
        self.acc64_callback.map(|callback| (callback)(self.context))
    }

    fn acc64_u(&self) -> Option<u64> {
        self.acc64_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn ipv6addr(&self) -> Option<&[u16; 8]> {
        self.ipv6addr_callback
            .map(|callback| unsafe { &*((callback)(self.context) as *const [u16; 8]) })
    }

    fn ipv6addr_u(&self) -> Option<&[u16; 8]> {
        self.ipv6addr_u_callback
            .map(|callback| unsafe { &*((callback)(self.context) as *const [u16; 8]) })
    }

    fn float32(&self) -> Option<f32> {
        self.float32_callback
            .map(|callback| (callback)(self.context))
    }

    fn float32_u(&self) -> Option<f32> {
        self.float32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn string(&self) -> Option<&CStr> {
        self.string_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn string_u(&self) -> Option<&CStr> {
        self.string_u_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn sunssf_5(&self) -> Option<i16> {
        self.sunssf_5_callback
            .map(|callback| (callback)(self.context))
    }

    fn sunssf_6(&self) -> Option<i16> {
        self.sunssf_6_callback
            .map(|callback| (callback)(self.context))
    }

    fn sunssf_7(&self) -> Option<i16> {
        self.sunssf_7_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_sunssf_8(&self) -> Option<i16> {
        self.repeating_sunssf_8_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_int16_11(&self) -> Option<i16> {
        self.repeating_int16_11_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_int16_12(&self) -> Option<i16> {
        self.repeating_int16_12_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_int16_u(&self) -> Option<i16> {
        self.repeating_int16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_uint16_11(&self) -> Option<u16> {
        self.repeating_uint16_11_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_uint16_12(&self) -> Option<u16> {
        self.repeating_uint16_12_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_uint16_13(&self) -> Option<u16> {
        self.repeating_uint16_13_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_uint16_u(&self) -> Option<u16> {
        self.repeating_uint16_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_int32(&self) -> Option<i32> {
        self.repeating_int32_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_int32_u(&self) -> Option<i32> {
        self.repeating_int32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_uint32(&self) -> Option<u32> {
        self.repeating_uint32_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_uint32_u(&self) -> Option<u32> {
        self.repeating_uint32_u_callback
            .map(|callback| (callback)(self.context))
    }

    fn repeating_sunssf_9(&self) -> Option<i16> {
        self.repeating_sunssf_9_callback
            .map(|callback| (callback)(self.context))
    }
}

impl WriteAdapter for Model63001CallbackAdapter {
    /// int16_4
    fn set_int16_4(&mut self, value: i16) {
        if let Some(callback) = self.set_int16_4_callback {
            (callback)(value, self.context);
        };
    }

    /// uint16_4
    fn set_uint16_4(&mut self, value: u16) {
        if let Some(callback) = self.set_uint16_4_callback {
            (callback)(value, self.context);
        };
    }

    /// int32_3
    fn set_int32_3(&mut self, value: i32) {
        if let Some(callback) = self.set_int32_3_callback {
            (callback)(value, self.context);
        };
    }

    /// uint32_3
    fn set_uint32_3(&mut self, value: u32) {
        if let Some(callback) = self.set_uint32_3_callback {
            (callback)(value, self.context);
        };
    }

    /// ipaddr
    fn set_ipaddr(&mut self, value: u32) {
        if let Some(callback) = self.set_ipaddr_callback {
            (callback)(value, self.context);
        };
    }

    /// int64
    fn set_int64(&mut self, value: i64) {
        if let Some(callback) = self.set_int64_callback {
            (callback)(value, self.context);
        };
    }

    /// float32
    fn set_float32(&mut self, value: f32) {
        if let Some(callback) = self.set_float32_callback {
            (callback)(value, self.context);
        };
    }

    /// string
    fn set_string(&mut self, value: &CStr) {
        if let Some(callback) = self.set_string_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// int16_11
    fn set_repeating_int16_11(&mut self, value: i16) {
        if let Some(callback) = self.set_repeating_int16_11_callback {
            (callback)(value, self.context);
        };
    }

    /// uint16_11
    fn set_repeating_uint16_11(&mut self, value: u16) {
        if let Some(callback) = self.set_repeating_uint16_11_callback {
            (callback)(value, self.context);
        };
    }

    /// int32
    fn set_repeating_int32(&mut self, value: i32) {
        if let Some(callback) = self.set_repeating_int32_callback {
            (callback)(value, self.context);
        };
    }

    /// uint32
    fn set_repeating_uint32(&mut self, value: u32) {
        if let Some(callback) = self.set_repeating_uint32_callback {
            (callback)(value, self.context);
        };
    }
}

/// C-FFI dispatch descriptor for SunSpec model 63001. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_63001: StaticModelSpec = StaticModelSpec {
    id: 63001,
    length: model_63001_c_length,
    writable: true,
    visit_read: model_63001_c_visit_read,
    visit_write: model_63001_c_visit_write,
};

fn model_63001_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model63001).model_length()
}

/// # Safety
/// `adapter` must be null or point to a live `Model63001CallbackAdapter`, valid for the
/// duration of the call.
unsafe fn model_63001_c_visit_read(
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model63001;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *const Model63001CallbackAdapter).as_ref() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_63001_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_63001_c_visit_write(
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let model = Model63001;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *mut Model63001CallbackAdapter).as_mut() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| match adapter {
        Some(adapter) => model.traverse_points_write(adapter, &buffer.slice(from, len), offset),
        None => Err(ModbusException::IllegalDataAddress),
    });
}

/// Build a [`SunspecAdapter`] for model 63001 backed by a callback adapter.
#[unsafe(no_mangle)]
pub extern "C" fn sunspec_model_63001_callback(
    adapter: *mut Model63001CallbackAdapter,
) -> SunspecAdapter {
    SunspecAdapter {
        model_spec: &SUNSPEC_MODEL_63001,
        adapter: adapter as *mut c_void,
    }
}
