// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::SunspecAdapter;
use core::ffi::c_void;
use sunspec_modbus_lib_rs::ModbusException;
use sunspec_modbus_lib_rs::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use sunspec_modbus_lib_rs::cursor::Cursor;
use sunspec_modbus_lib_rs::model::{ModelSpec, StaticModelSpec};
use sunspec_modbus_lib_rs::sunspec::models::model_809::*;

#[repr(C)]
pub struct Model809CallbackAdapter {
    context: *mut c_void,
    /// Stack Points To Be Determined (StackTBD)
    stack_points_to_be_determined_callback: extern "C" fn(*const c_void) -> u16,
    /// Cell Points To Be Determined (CellTBD)
    cell_cell_points_to_be_determined_callback: extern "C" fn(*const c_void) -> u16,
}

impl ReadAdapter for Model809CallbackAdapter {
    fn stack_points_to_be_determined(&self) -> u16 {
        (self.stack_points_to_be_determined_callback)(self.context)
    }

    fn cell_cell_points_to_be_determined(&self) -> u16 {
        (self.cell_cell_points_to_be_determined_callback)(self.context)
    }
}

/// C-FFI dispatch descriptor for SunSpec model 809. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_809: StaticModelSpec = StaticModelSpec {
    id: 809,
    length: model_809_c_length,
    writable: false,
    visit_read: model_809_c_visit_read,
    visit_write: model_809_c_visit_write,
};

fn model_809_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model809).model_length()
}

/// # Safety
/// `adapter` must be null or point to a live `Model809CallbackAdapter`, valid for the
/// duration of the call.
unsafe fn model_809_c_visit_read(
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model809;
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *const Model809CallbackAdapter).as_ref() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_809_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_809_c_visit_write(
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let _ = (adapter, buffer);
    let model = Model809;
    cursor.visit_source_block(model.model_length(), |_, _, _| {
        Err(ModbusException::IllegalDataAddress)
    });
}

/// Build a [`SunspecAdapter`] for model 809 backed by a callback adapter.
#[unsafe(no_mangle)]
pub extern "C" fn sunspec_model_809_callback(
    adapter: *mut Model809CallbackAdapter,
) -> SunspecAdapter {
    SunspecAdapter {
        model_spec: &SUNSPEC_MODEL_809,
        adapter: adapter as *mut c_void,
    }
}
