// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::SunspecAdapter;
use core::ffi::c_void;
use sunspec_modbus_lib_rs::ModbusException;
use sunspec_modbus_lib_rs::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use sunspec_modbus_lib_rs::cursor::Cursor;
use sunspec_modbus_lib_rs::model::{ModelSpec, StaticModelSpec};
use sunspec_modbus_lib_rs::sunspec::models::model_712::*;

#[repr(C)]
pub struct Model712CallbackAdapter {
    context: *mut c_void,
    /// DER Watt-Var Module Enable (Ena)
    ///
    /// DER Watt-Var control enable.
    der_watt_var_module_enable_callback: extern "C" fn(*const c_void) -> Model712Ena,
    /// DER Watt-Var Module Enable (Ena)
    ///
    /// DER Watt-Var control enable.
    set_der_watt_var_module_enable_callback: extern "C" fn(Model712Ena, *mut c_void),
    /// Set Active Curve Request (AdptCrvReq)
    ///
    /// Set active curve. 0 = No active curve.
    active_curve_request_callback: extern "C" fn(*const c_void) -> u16,
    /// Set Active Curve Request (AdptCrvReq)
    ///
    /// Set active curve. 0 = No active curve.
    set_active_curve_request_callback: extern "C" fn(u16, *mut c_void),
    /// Set Active Curve Result (AdptCrvRslt)
    ///
    /// Result of last set active curve operation.
    set_active_curve_result_callback: extern "C" fn(*const c_void) -> Model712AdptCrvRslt,
    /// Number Of Points (NPt)
    ///
    /// Number of curve points supported.
    number_of_points_callback: extern "C" fn(*const c_void) -> u16,
    /// Stored Curve Count (NCrv)
    ///
    /// Number of stored curves supported.
    stored_curve_count_callback: extern "C" fn(*const c_void) -> u16,
    /// Reversion Timeout (RvrtTms)
    ///
    /// Reversion time in seconds. 0 = No reversion time.
    reversion_timeout_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Reversion Timeout (RvrtTms)
    ///
    /// Reversion time in seconds. 0 = No reversion time.
    set_reversion_timeout_callback: Option<extern "C" fn(u32, *mut c_void)>,
    /// Reversion Time Left (RvrtRem)
    ///
    /// Reversion time remaining in seconds.
    reversion_time_left_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Reversion Curve (RvrtCrv)
    ///
    /// Default curve after reversion timeout.
    reversion_curve_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Reversion Curve (RvrtCrv)
    ///
    /// Default curve after reversion timeout.
    set_reversion_curve_callback: Option<extern "C" fn(u16, *mut c_void)>,
    /// Active Power Scale Factor (W_SF)
    ///
    /// Scale factor for curve active power points.
    active_power_scale_factor_callback: extern "C" fn(*const c_void) -> i16,
    /// Var Scale Factor (DeptRef_SF)
    ///
    /// Scale factor for curve var points.
    var_scale_factor_callback: extern "C" fn(*const c_void) -> i16,
    /// Active Points (ActPt)
    ///
    /// Number of active points.
    crv_active_points_callback: extern "C" fn(*const c_void, u16) -> u16,
    /// Active Points (ActPt)
    ///
    /// Number of active points.
    set_crv_active_points_callback: extern "C" fn(u16, *mut c_void, u16),
    /// Dependent Reference (DeptRef)
    ///
    /// Curve dependent reference.
    crv_dependent_reference_callback: extern "C" fn(*const c_void, u16) -> Model712DeptRef,
    /// Dependent Reference (DeptRef)
    ///
    /// Curve dependent reference.
    set_crv_dependent_reference_callback: extern "C" fn(Model712DeptRef, *mut c_void, u16),
    /// Power Priority (Pri)
    ///
    /// Power priority.
    crv_power_priority_callback: Option<extern "C" fn(*const c_void, u16) -> Model712Pri>,
    /// Power Priority (Pri)
    ///
    /// Power priority.
    set_crv_power_priority_callback: Option<extern "C" fn(Model712Pri, *mut c_void, u16)>,
    /// Curve Access (ReadOnly)
    ///
    /// Curve read-write access.
    crv_curve_access_callback: extern "C" fn(*const c_void, u16) -> Model712ReadOnly,
    /// Active Power Point (W)
    ///
    /// Curve active power point as percentage.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes. IEEE 1547 implementations must allow 0 values for all three load points.
    pt_active_power_point_callback: Option<extern "C" fn(*const c_void, u16, u16) -> i16>,
    /// Active Power Point (W)
    ///
    /// Curve active power point as percentage.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes. IEEE 1547 implementations must allow 0 values for all three load points.
    set_pt_active_power_point_callback: Option<extern "C" fn(i16, *mut c_void, u16, u16)>,
    /// Reactive Power Point (Var)
    ///
    /// Curve reactive power point as set in DeptRef point.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes. IEEE 1547 implementations must allow 0 values for all three load points
    pt_reactive_power_point_callback: Option<extern "C" fn(*const c_void, u16, u16) -> i16>,
    /// Reactive Power Point (Var)
    ///
    /// Curve reactive power point as set in DeptRef point.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes. IEEE 1547 implementations must allow 0 values for all three load points
    set_pt_reactive_power_point_callback: Option<extern "C" fn(i16, *mut c_void, u16, u16)>,
}

impl ReadAdapter for Model712CallbackAdapter {
    fn der_watt_var_module_enable(&self) -> Ena {
        (self.der_watt_var_module_enable_callback)(self.context)
    }

    fn active_curve_request(&self) -> u16 {
        (self.active_curve_request_callback)(self.context)
    }

    fn set_active_curve_result(&self) -> AdptCrvRslt {
        (self.set_active_curve_result_callback)(self.context)
    }

    fn number_of_points(&self) -> u16 {
        (self.number_of_points_callback)(self.context)
    }

    fn stored_curve_count(&self) -> u16 {
        (self.stored_curve_count_callback)(self.context)
    }

    fn reversion_timeout(&self) -> Option<u32> {
        self.reversion_timeout_callback
            .map(|callback| (callback)(self.context))
    }

    fn reversion_time_left(&self) -> Option<u32> {
        self.reversion_time_left_callback
            .map(|callback| (callback)(self.context))
    }

    fn reversion_curve(&self) -> Option<u16> {
        self.reversion_curve_callback
            .map(|callback| (callback)(self.context))
    }

    fn active_power_scale_factor(&self) -> i16 {
        (self.active_power_scale_factor_callback)(self.context)
    }

    fn var_scale_factor(&self) -> i16 {
        (self.var_scale_factor_callback)(self.context)
    }

    fn crv_active_points(&self, crv_index: u16) -> u16 {
        (self.crv_active_points_callback)(self.context, crv_index)
    }

    fn crv_dependent_reference(&self, crv_index: u16) -> DeptRef {
        (self.crv_dependent_reference_callback)(self.context, crv_index)
    }

    fn crv_power_priority(&self, crv_index: u16) -> Option<Pri> {
        self.crv_power_priority_callback
            .map(|callback| (callback)(self.context, crv_index))
    }

    fn crv_curve_access(&self, crv_index: u16) -> ReadOnly {
        (self.crv_curve_access_callback)(self.context, crv_index)
    }

    fn pt_active_power_point(&self, crv_index: u16, pt_index: u16) -> Option<i16> {
        self.pt_active_power_point_callback
            .map(|callback| (callback)(self.context, crv_index, pt_index))
    }

    fn pt_reactive_power_point(&self, crv_index: u16, pt_index: u16) -> Option<i16> {
        self.pt_reactive_power_point_callback
            .map(|callback| (callback)(self.context, crv_index, pt_index))
    }
}

impl WriteAdapter for Model712CallbackAdapter {
    /// DER Watt-Var Module Enable (Ena)
    ///
    /// DER Watt-Var control enable.
    fn set_der_watt_var_module_enable(&mut self, value: Ena) {
        (self.set_der_watt_var_module_enable_callback)(value, self.context);
    }

    /// Set Active Curve Request (AdptCrvReq)
    ///
    /// Set active curve. 0 = No active curve.
    fn set_active_curve_request(&mut self, value: u16) {
        (self.set_active_curve_request_callback)(value, self.context);
    }

    /// Reversion Timeout (RvrtTms)
    ///
    /// Reversion time in seconds. 0 = No reversion time.
    fn set_reversion_timeout(&mut self, value: u32) {
        if let Some(callback) = self.set_reversion_timeout_callback {
            (callback)(value, self.context);
        };
    }

    /// Reversion Curve (RvrtCrv)
    ///
    /// Default curve after reversion timeout.
    fn set_reversion_curve(&mut self, value: u16) {
        if let Some(callback) = self.set_reversion_curve_callback {
            (callback)(value, self.context);
        };
    }

    /// Active Points (ActPt)
    ///
    /// Number of active points.
    fn set_crv_active_points(&mut self, value: u16, crv_index: u16) {
        (self.set_crv_active_points_callback)(value, self.context, crv_index);
    }

    /// Dependent Reference (DeptRef)
    ///
    /// Curve dependent reference.
    fn set_crv_dependent_reference(&mut self, value: DeptRef, crv_index: u16) {
        (self.set_crv_dependent_reference_callback)(value, self.context, crv_index);
    }

    /// Power Priority (Pri)
    ///
    /// Power priority.
    fn set_crv_power_priority(&mut self, value: Pri, crv_index: u16) {
        if let Some(callback) = self.set_crv_power_priority_callback {
            (callback)(value, self.context, crv_index);
        };
    }

    /// Active Power Point (W)
    ///
    /// Curve active power point as percentage.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes. IEEE 1547 implementations must allow 0 values for all three load points.
    fn set_pt_active_power_point(&mut self, value: i16, crv_index: u16, pt_index: u16) {
        if let Some(callback) = self.set_pt_active_power_point_callback {
            (callback)(value, self.context, crv_index, pt_index);
        };
    }

    /// Reactive Power Point (Var)
    ///
    /// Curve reactive power point as set in DeptRef point.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes. IEEE 1547 implementations must allow 0 values for all three load points
    fn set_pt_reactive_power_point(&mut self, value: i16, crv_index: u16, pt_index: u16) {
        if let Some(callback) = self.set_pt_reactive_power_point_callback {
            (callback)(value, self.context, crv_index, pt_index);
        };
    }
}

/// C-FFI dispatch descriptor for SunSpec model 712. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_712: StaticModelSpec = StaticModelSpec {
    id: 712,
    length: model_712_c_length,
    writable: true,
    visit_read: model_712_c_visit_read,
    visit_write: model_712_c_visit_write,
};

fn model_712_c_length(repeat_count_0: u16, repeat_count_1: u16) -> u16 {
    (Model712 {
        stored_curve_count: repeat_count_0,
        number_of_points: repeat_count_1,
    })
    .model_length()
}

/// # Safety
/// `adapter` must be null or point to a live `Model712CallbackAdapter`, valid for the
/// duration of the call.
unsafe fn model_712_c_visit_read(
    adapter: *const c_void,
    repeat_count_0: u16,
    repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model712 {
        stored_curve_count: repeat_count_0,
        number_of_points: repeat_count_1,
    };
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *const Model712CallbackAdapter).as_ref() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_712_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_712_c_visit_write(
    adapter: *mut c_void,
    repeat_count_0: u16,
    repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let model = Model712 {
        stored_curve_count: repeat_count_0,
        number_of_points: repeat_count_1,
    };
    // SAFETY: as required by this function's own contract.
    let adapter = unsafe { (adapter as *mut Model712CallbackAdapter).as_mut() };
    cursor.visit_source_block(model.model_length(), |offset, from, len| match adapter {
        Some(adapter) => model.traverse_points_write(adapter, &buffer.slice(from, len), offset),
        None => Err(ModbusException::IllegalDataAddress),
    });
}

/// Build a [`SunspecAdapter`] for model 712 backed by a callback adapter.
#[unsafe(no_mangle)]
pub extern "C" fn sunspec_model_712_callback(
    adapter: *mut Model712CallbackAdapter,
) -> SunspecAdapter {
    SunspecAdapter {
        model_spec: &SUNSPEC_MODEL_712,
        adapter: adapter as *mut c_void,
    }
}
