// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::model::ModelSpec;
use core::cmp::min;

static POINTS: [PointDetails<()>; 64] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::Amps,
        size: 2,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::AmpsPhaseA,
        size: 2,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::AmpsPhaseB,
        size: 2,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::AmpsPhaseC,
        size: 2,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::VoltageLn,
        size: 2,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageAn,
        size: 2,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageBn,
        size: 2,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageCn,
        size: 2,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::VoltageLl,
        size: 2,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageAb,
        size: 2,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageBc,
        size: 2,
        start_address: 22,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageCa,
        size: 2,
        start_address: 24,
    },
    PointDetails {
        point: |()| Point::Hz,
        size: 2,
        start_address: 26,
    },
    PointDetails {
        point: |()| Point::Watts,
        size: 2,
        start_address: 28,
    },
    PointDetails {
        point: |()| Point::WattsPhaseA,
        size: 2,
        start_address: 30,
    },
    PointDetails {
        point: |()| Point::WattsPhaseB,
        size: 2,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::WattsPhaseC,
        size: 2,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::Va,
        size: 2,
        start_address: 36,
    },
    PointDetails {
        point: |()| Point::VaPhaseA,
        size: 2,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::VaPhaseB,
        size: 2,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::VaPhaseC,
        size: 2,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::Var,
        size: 2,
        start_address: 44,
    },
    PointDetails {
        point: |()| Point::VarPhaseA,
        size: 2,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::VarPhaseB,
        size: 2,
        start_address: 48,
    },
    PointDetails {
        point: |()| Point::VarPhaseC,
        size: 2,
        start_address: 50,
    },
    PointDetails {
        point: |()| Point::Pf,
        size: 2,
        start_address: 52,
    },
    PointDetails {
        point: |()| Point::PfPhaseA,
        size: 2,
        start_address: 54,
    },
    PointDetails {
        point: |()| Point::PfPhaseB,
        size: 2,
        start_address: 56,
    },
    PointDetails {
        point: |()| Point::PfPhaseC,
        size: 2,
        start_address: 58,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursExported,
        size: 2,
        start_address: 60,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursExportedPhaseA,
        size: 2,
        start_address: 62,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursExportedPhaseB,
        size: 2,
        start_address: 64,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursExportedPhaseC,
        size: 2,
        start_address: 66,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursImported,
        size: 2,
        start_address: 68,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursImportedPhaseA,
        size: 2,
        start_address: 70,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursImportedPhaseB,
        size: 2,
        start_address: 72,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursImportedPhaseC,
        size: 2,
        start_address: 74,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursExported,
        size: 2,
        start_address: 76,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursExportedPhaseA,
        size: 2,
        start_address: 78,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursExportedPhaseB,
        size: 2,
        start_address: 80,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursExportedPhaseC,
        size: 2,
        start_address: 82,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursImported,
        size: 2,
        start_address: 84,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursImportedPhaseA,
        size: 2,
        start_address: 86,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursImportedPhaseB,
        size: 2,
        start_address: 88,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursImportedPhaseC,
        size: 2,
        start_address: 90,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursImportedQ1,
        size: 2,
        start_address: 92,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ1PhaseA,
        size: 2,
        start_address: 94,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ1PhaseB,
        size: 2,
        start_address: 96,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ1PhaseC,
        size: 2,
        start_address: 98,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ2,
        size: 2,
        start_address: 100,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ2PhaseA,
        size: 2,
        start_address: 102,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ2PhaseB,
        size: 2,
        start_address: 104,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ2PhaseC,
        size: 2,
        start_address: 106,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ3,
        size: 2,
        start_address: 108,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ3PhaseA,
        size: 2,
        start_address: 110,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ3PhaseB,
        size: 2,
        start_address: 112,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ3PhaseC,
        size: 2,
        start_address: 114,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ4,
        size: 2,
        start_address: 116,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ4ImportedPhaseA,
        size: 2,
        start_address: 118,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ4ImportedPhaseB,
        size: 2,
        start_address: 120,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ4ImportedPhaseC,
        size: 2,
        start_address: 122,
    },
    PointDetails {
        point: |()| Point::Events,
        size: 2,
        start_address: 124,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    Amps,
    AmpsPhaseA,
    AmpsPhaseB,
    AmpsPhaseC,
    VoltageLn,
    PhaseVoltageAn,
    PhaseVoltageBn,
    PhaseVoltageCn,
    VoltageLl,
    PhaseVoltageAb,
    PhaseVoltageBc,
    PhaseVoltageCa,
    Hz,
    Watts,
    WattsPhaseA,
    WattsPhaseB,
    WattsPhaseC,
    Va,
    VaPhaseA,
    VaPhaseB,
    VaPhaseC,
    Var,
    VarPhaseA,
    VarPhaseB,
    VarPhaseC,
    Pf,
    PfPhaseA,
    PfPhaseB,
    PfPhaseC,
    TotalWattHoursExported,
    TotalWattHoursExportedPhaseA,
    TotalWattHoursExportedPhaseB,
    TotalWattHoursExportedPhaseC,
    TotalWattHoursImported,
    TotalWattHoursImportedPhaseA,
    TotalWattHoursImportedPhaseB,
    TotalWattHoursImportedPhaseC,
    TotalVaHoursExported,
    TotalVaHoursExportedPhaseA,
    TotalVaHoursExportedPhaseB,
    TotalVaHoursExportedPhaseC,
    TotalVaHoursImported,
    TotalVaHoursImportedPhaseA,
    TotalVaHoursImportedPhaseB,
    TotalVaHoursImportedPhaseC,
    TotalVarHoursImportedQ1,
    TotalVArHoursImportedQ1PhaseA,
    TotalVArHoursImportedQ1PhaseB,
    TotalVArHoursImportedQ1PhaseC,
    TotalVArHoursImportedQ2,
    TotalVArHoursImportedQ2PhaseA,
    TotalVArHoursImportedQ2PhaseB,
    TotalVArHoursImportedQ2PhaseC,
    TotalVArHoursExportedQ3,
    TotalVArHoursExportedQ3PhaseA,
    TotalVArHoursExportedQ3PhaseB,
    TotalVArHoursExportedQ3PhaseC,
    TotalVArHoursExportedQ4,
    TotalVArHoursExportedQ4ImportedPhaseA,
    TotalVArHoursExportedQ4ImportedPhaseB,
    TotalVArHoursExportedQ4ImportedPhaseC,
    Events,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 213. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model213;

impl<'ad> ModelSpec<'ad> for Model213 {
    const MODEL_ID: u16 = 213;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        126
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model213,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(213);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::Amps => {
            buffer.write_f32(adapter.amps(), offset);
        }
        Point::AmpsPhaseA => {
            buffer.write_f32(adapter.amps_phase_a(), offset);
        }
        Point::AmpsPhaseB => {
            buffer.write_f32(adapter.amps_phase_b(), offset);
        }
        Point::AmpsPhaseC => {
            buffer.write_f32(adapter.amps_phase_c(), offset);
        }
        Point::VoltageLn => {
            buffer.write_f32(adapter.voltage_ln(), offset);
        }
        Point::PhaseVoltageAn => {
            buffer.write_f32(adapter.phase_voltage_an(), offset);
        }
        Point::PhaseVoltageBn => {
            buffer.write_f32(adapter.phase_voltage_bn(), offset);
        }
        Point::PhaseVoltageCn => {
            buffer.write_f32(adapter.phase_voltage_cn(), offset);
        }
        Point::VoltageLl => {
            buffer.write_f32(adapter.voltage_ll(), offset);
        }
        Point::PhaseVoltageAb => {
            buffer.write_f32(adapter.phase_voltage_ab(), offset);
        }
        Point::PhaseVoltageBc => {
            buffer.write_f32(adapter.phase_voltage_bc(), offset);
        }
        Point::PhaseVoltageCa => {
            buffer.write_f32(adapter.phase_voltage_ca(), offset);
        }
        Point::Hz => {
            buffer.write_f32(adapter.hz(), offset);
        }
        Point::Watts => {
            buffer.write_f32(adapter.watts(), offset);
        }
        Point::WattsPhaseA => {
            if let Some(value) = adapter.watts_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::WattsPhaseB => {
            if let Some(value) = adapter.watts_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::WattsPhaseC => {
            if let Some(value) = adapter.watts_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Va => {
            if let Some(value) = adapter.va() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VaPhaseA => {
            if let Some(value) = adapter.va_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VaPhaseB => {
            if let Some(value) = adapter.va_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VaPhaseC => {
            if let Some(value) = adapter.va_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Var => {
            if let Some(value) = adapter.var() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VarPhaseA => {
            if let Some(value) = adapter.var_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VarPhaseB => {
            if let Some(value) = adapter.var_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VarPhaseC => {
            if let Some(value) = adapter.var_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Pf => {
            if let Some(value) = adapter.pf() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::PfPhaseA => {
            if let Some(value) = adapter.pf_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::PfPhaseB => {
            if let Some(value) = adapter.pf_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::PfPhaseC => {
            if let Some(value) = adapter.pf_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursExported => {
            buffer.write_f32(adapter.total_watt_hours_exported(), offset);
        }
        Point::TotalWattHoursExportedPhaseA => {
            if let Some(value) = adapter.total_watt_hours_exported_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursExportedPhaseB => {
            if let Some(value) = adapter.total_watt_hours_exported_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursExportedPhaseC => {
            if let Some(value) = adapter.total_watt_hours_exported_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursImported => {
            buffer.write_f32(adapter.total_watt_hours_imported(), offset);
        }
        Point::TotalWattHoursImportedPhaseA => {
            if let Some(value) = adapter.total_watt_hours_imported_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursImportedPhaseB => {
            if let Some(value) = adapter.total_watt_hours_imported_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursImportedPhaseC => {
            if let Some(value) = adapter.total_watt_hours_imported_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursExported => {
            if let Some(value) = adapter.total_va_hours_exported() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursExportedPhaseA => {
            if let Some(value) = adapter.total_va_hours_exported_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursExportedPhaseB => {
            if let Some(value) = adapter.total_va_hours_exported_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursExportedPhaseC => {
            if let Some(value) = adapter.total_va_hours_exported_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursImported => {
            if let Some(value) = adapter.total_va_hours_imported() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursImportedPhaseA => {
            if let Some(value) = adapter.total_va_hours_imported_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursImportedPhaseB => {
            if let Some(value) = adapter.total_va_hours_imported_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursImportedPhaseC => {
            if let Some(value) = adapter.total_va_hours_imported_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursImportedQ1 => {
            if let Some(value) = adapter.total_var_hours_imported_q1() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ1PhaseA => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q1_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ1PhaseB => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q1_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ1PhaseC => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q1_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ2 => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q2() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ2PhaseA => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q2_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ2PhaseB => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q2_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ2PhaseC => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q2_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ3 => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q3() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ3PhaseA => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q3_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ3PhaseB => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q3_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ3PhaseC => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q3_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ4 => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q4() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ4ImportedPhaseA => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q4_imported_phase_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ4ImportedPhaseB => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q4_imported_phase_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ4ImportedPhaseC => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q4_imported_phase_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Events => {
            buffer.write_u32(adapter.events(), offset);
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model213,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// Amps (A)
    ///
    /// Total AC Current
    fn amps(&self) -> f32;

    /// Amps PhaseA (AphA)
    ///
    /// Phase A Current
    fn amps_phase_a(&self) -> f32;

    /// Amps PhaseB (AphB)
    ///
    /// Phase B Current
    fn amps_phase_b(&self) -> f32;

    /// Amps PhaseC (AphC)
    ///
    /// Phase C Current
    fn amps_phase_c(&self) -> f32;

    /// Voltage LN (PhV)
    ///
    /// Line to Neutral AC Voltage (average of active phases)
    fn voltage_ln(&self) -> f32;

    /// Phase Voltage AN (PhVphA)
    ///
    /// Phase Voltage AN
    fn phase_voltage_an(&self) -> f32;

    /// Phase Voltage BN (PhVphB)
    ///
    /// Phase Voltage BN
    fn phase_voltage_bn(&self) -> f32;

    /// Phase Voltage CN (PhVphC)
    ///
    /// Phase Voltage CN
    fn phase_voltage_cn(&self) -> f32;

    /// Voltage LL (PPV)
    ///
    /// Line to Line AC Voltage (average of active phases)
    fn voltage_ll(&self) -> f32;

    /// Phase Voltage AB (PPVphAB)
    ///
    /// Phase Voltage AB
    fn phase_voltage_ab(&self) -> f32;

    /// Phase Voltage BC (PPVphBC)
    ///
    /// Phase Voltage BC
    fn phase_voltage_bc(&self) -> f32;

    /// Phase Voltage CA (PPVphCA)
    ///
    /// Phase Voltage CA
    fn phase_voltage_ca(&self) -> f32;

    /// Hz (Hz)
    ///
    /// Frequency
    fn hz(&self) -> f32;

    /// Watts (W)
    ///
    /// Total Real Power
    fn watts(&self) -> f32;

    /// Watts phase A (WphA)
    fn watts_phase_a(&self) -> Option<f32> {
        None
    }

    /// Watts phase B (WphB)
    fn watts_phase_b(&self) -> Option<f32> {
        None
    }

    /// Watts phase C (WphC)
    fn watts_phase_c(&self) -> Option<f32> {
        None
    }

    /// VA (VA)
    ///
    /// AC Apparent Power
    fn va(&self) -> Option<f32> {
        None
    }

    /// VA phase A (VAphA)
    fn va_phase_a(&self) -> Option<f32> {
        None
    }

    /// VA phase B (VAphB)
    fn va_phase_b(&self) -> Option<f32> {
        None
    }

    /// VA phase C (VAphC)
    fn va_phase_c(&self) -> Option<f32> {
        None
    }

    /// VAR (VAR)
    ///
    /// Reactive Power
    fn var(&self) -> Option<f32> {
        None
    }

    /// VAR phase A (VARphA)
    fn var_phase_a(&self) -> Option<f32> {
        None
    }

    /// VAR phase B (VARphB)
    fn var_phase_b(&self) -> Option<f32> {
        None
    }

    /// VAR phase C (VARphC)
    fn var_phase_c(&self) -> Option<f32> {
        None
    }

    /// PF (PF)
    ///
    /// Power Factor
    fn pf(&self) -> Option<f32> {
        None
    }

    /// PF phase A (PFphA)
    fn pf_phase_a(&self) -> Option<f32> {
        None
    }

    /// PF phase B (PFphB)
    fn pf_phase_b(&self) -> Option<f32> {
        None
    }

    /// PF phase C (PFphC)
    fn pf_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total Watt-hours Exported (TotWhExp)
    ///
    /// Total Real Energy Exported
    fn total_watt_hours_exported(&self) -> f32;

    /// Total Watt-hours Exported phase A (TotWhExpPhA)
    fn total_watt_hours_exported_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total Watt-hours Exported phase B (TotWhExpPhB)
    fn total_watt_hours_exported_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total Watt-hours Exported phase C (TotWhExpPhC)
    fn total_watt_hours_exported_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total Watt-hours Imported (TotWhImp)
    ///
    /// Total Real Energy Imported
    fn total_watt_hours_imported(&self) -> f32;

    /// Total Watt-hours Imported phase A (TotWhImpPhA)
    fn total_watt_hours_imported_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total Watt-hours Imported phase B (TotWhImpPhB)
    fn total_watt_hours_imported_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total Watt-hours Imported phase C (TotWhImpPhC)
    fn total_watt_hours_imported_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Exported (TotVAhExp)
    ///
    /// Total Apparent Energy Exported
    fn total_va_hours_exported(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Exported phase A (TotVAhExpPhA)
    fn total_va_hours_exported_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Exported phase B (TotVAhExpPhB)
    fn total_va_hours_exported_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Exported phase C (TotVAhExpPhC)
    fn total_va_hours_exported_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Imported (TotVAhImp)
    ///
    /// Total Apparent Energy Imported
    fn total_va_hours_imported(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Imported phase A (TotVAhImpPhA)
    fn total_va_hours_imported_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Imported phase B (TotVAhImpPhB)
    fn total_va_hours_imported_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total VA-hours Imported phase C (TotVAhImpPhC)
    fn total_va_hours_imported_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total VAR-hours Imported Q1 (TotVArhImpQ1)
    ///
    /// Total Reactive Energy Imported Quadrant 1
    fn total_var_hours_imported_q1(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q1 phase A (TotVArhImpQ1phA)
    fn total_v_ar_hours_imported_q1_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q1 phase B (TotVArhImpQ1phB)
    fn total_v_ar_hours_imported_q1_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q1 phase C (TotVArhImpQ1phC)
    fn total_v_ar_hours_imported_q1_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q2 (TotVArhImpQ2)
    ///
    /// Total Reactive Power Imported Quadrant 2
    fn total_v_ar_hours_imported_q2(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q2 phase A (TotVArhImpQ2phA)
    fn total_v_ar_hours_imported_q2_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q2 phase B (TotVArhImpQ2phB)
    fn total_v_ar_hours_imported_q2_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Imported Q2 phase C (TotVArhImpQ2phC)
    fn total_v_ar_hours_imported_q2_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q3 (TotVArhExpQ3)
    ///
    /// Total Reactive Power Exported Quadrant 3
    fn total_v_ar_hours_exported_q3(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q3 phase A (TotVArhExpQ3phA)
    fn total_v_ar_hours_exported_q3_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q3 phase B (TotVArhExpQ3phB)
    fn total_v_ar_hours_exported_q3_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q3 phase C (TotVArhExpQ3phC)
    fn total_v_ar_hours_exported_q3_phase_c(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q4 (TotVArhExpQ4)
    ///
    /// Total Reactive Power Exported Quadrant 4
    fn total_v_ar_hours_exported_q4(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q4 Imported phase A (TotVArhExpQ4phA)
    fn total_v_ar_hours_exported_q4_imported_phase_a(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q4 Imported phase B (TotVArhExpQ4phB)
    fn total_v_ar_hours_exported_q4_imported_phase_b(&self) -> Option<f32> {
        None
    }

    /// Total VAr-hours Exported Q4 Imported phase C (TotVArhExpQ4phC)
    fn total_v_ar_hours_exported_q4_imported_phase_c(&self) -> Option<f32> {
        None
    }

    /// Events (Evt)
    ///
    /// Meter Event Flags
    fn events(&self) -> u32;
}

pub trait WriteAdapter {}
