// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::model::ModelSpec;
use core::cmp::min;

static POINTS: [PointDetails<()>; 41] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::StringIndex,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::ModuleCount,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::StringStatus,
        size: 2,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::ConnectionFailureReason,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::StringCellBalancingCount,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::StringStateOfCharge,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::StringDepthOfDischarge,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::StringCycleCount,
        size: 2,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::StringStateOfHealth,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::StringCurrent,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::StringVoltage,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::MaxCellVoltage,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::MaxCellVoltageModule,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::MinCellVoltage,
        size: 1,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::MinCellVoltageModule,
        size: 1,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::AverageCellVoltage,
        size: 1,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::MaxModuleTemperature,
        size: 1,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::MaxModuleTemperatureModule,
        size: 1,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::MinModuleTemperature,
        size: 1,
        start_address: 22,
    },
    PointDetails {
        point: |()| Point::MinModuleTemperatureModule,
        size: 1,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::AverageModuleTemperature,
        size: 1,
        start_address: 24,
    },
    PointDetails {
        point: |()| Point::Pad1,
        size: 1,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::ContactorStatus,
        size: 2,
        start_address: 26,
    },
    PointDetails {
        point: |()| Point::StringEvent1,
        size: 2,
        start_address: 28,
    },
    PointDetails {
        point: |()| Point::StringEvent2,
        size: 2,
        start_address: 30,
    },
    PointDetails {
        point: |()| Point::VendorEventBitfield1,
        size: 2,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::VendorEventBitfield2,
        size: 2,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::EnableDisableString,
        size: 1,
        start_address: 36,
    },
    PointDetails {
        point: |()| Point::ConnectDisconnectString,
        size: 1,
        start_address: 37,
    },
    PointDetails {
        point: |()| Point::SoCSf,
        size: 1,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::SoHSf,
        size: 1,
        start_address: 39,
    },
    PointDetails {
        point: |()| Point::DoDSf,
        size: 1,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::ASf,
        size: 1,
        start_address: 41,
    },
    PointDetails {
        point: |()| Point::VSf,
        size: 1,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::CellVSf,
        size: 1,
        start_address: 43,
    },
    PointDetails {
        point: |()| Point::ModTmpSf,
        size: 1,
        start_address: 44,
    },
    PointDetails {
        point: |()| Point::Pad2,
        size: 1,
        start_address: 45,
    },
    PointDetails {
        point: |()| Point::Pad3,
        size: 1,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::Pad4,
        size: 1,
        start_address: 47,
    },
];

static LITHIUM_ION_STRING_MODULE_POINTS: [PointDetails<u16>; 16] = [
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleModuleCellCount {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleModuleSoC {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleModuleSoH {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleMaxCellVoltage {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleMaxCellVoltageCell {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleMinCellVoltage {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleMinCellVoltageCell {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleAverageCellVoltage {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleMaxCellTemperature {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| {
            Point::LithiumIonStringModuleMaxCellTemperatureCell {
                lithium_ion_string_module_index,
            }
        },
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::LithiumIonStringModuleMinCellTemperature {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| {
            Point::LithiumIonStringModuleMinCellTemperatureCell {
                lithium_ion_string_module_index,
            }
        },
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| {
            Point::LithiumIonStringModuleAverageCellTemperature {
                lithium_ion_string_module_index,
            }
        },
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::Pad5 {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::Pad6 {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |lithium_ion_string_module_index| Point::Pad7 {
            lithium_ion_string_module_index,
        },
        size: 1,
        start_address: 15,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    StringIndex,
    ModuleCount,
    StringStatus,
    ConnectionFailureReason,
    StringCellBalancingCount,
    StringStateOfCharge,
    StringDepthOfDischarge,
    StringCycleCount,
    StringStateOfHealth,
    StringCurrent,
    StringVoltage,
    MaxCellVoltage,
    MaxCellVoltageModule,
    MinCellVoltage,
    MinCellVoltageModule,
    AverageCellVoltage,
    MaxModuleTemperature,
    MaxModuleTemperatureModule,
    MinModuleTemperature,
    MinModuleTemperatureModule,
    AverageModuleTemperature,
    Pad1,
    ContactorStatus,
    StringEvent1,
    StringEvent2,
    VendorEventBitfield1,
    VendorEventBitfield2,
    EnableDisableString,
    ConnectDisconnectString,
    SoCSf,
    SoHSf,
    DoDSf,
    ASf,
    VSf,
    CellVSf,
    ModTmpSf,
    Pad2,
    Pad3,
    Pad4,
    LithiumIonStringModuleModuleCellCount {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleModuleSoC {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleModuleSoH {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMaxCellVoltage {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMaxCellVoltageCell {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMinCellVoltage {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMinCellVoltageCell {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleAverageCellVoltage {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMaxCellTemperature {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMaxCellTemperatureCell {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMinCellTemperature {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleMinCellTemperatureCell {
        lithium_ion_string_module_index: u16,
    },
    LithiumIonStringModuleAverageCellTemperature {
        lithium_ion_string_module_index: u16,
    },
    Pad5 {
        lithium_ion_string_module_index: u16,
    },
    Pad6 {
        lithium_ion_string_module_index: u16,
    },
    Pad7 {
        lithium_ion_string_module_index: u16,
    },
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 804. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model804 {
    /// Number of repeating blocks in this model instance.
    pub module_count: u16,
}

impl<'ad> ModelSpec<'ad> for Model804 {
    const MODEL_ID: u16 = 804;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        48 + self.module_count * (16)
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let lithium_ion_string_module_count = self.module_count;
        let lithium_ion_string_module_size = 16;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain((0..lithium_ion_string_module_count).flat_map(
                move |lithium_ion_string_module_index| {
                    let lithium_ion_string_module_address =
                        48 + lithium_ion_string_module_index * lithium_ion_string_module_size;
                    LITHIUM_ION_STRING_MODULE_POINTS.iter().map(move |p| {
                        (
                            lithium_ion_string_module_address + p.start_address,
                            p.size,
                            (p.point)(lithium_ion_string_module_index),
                        )
                    })
                },
            ))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let lithium_ion_string_module_count = self.module_count;
        let lithium_ion_string_module_size = 16;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain((0..lithium_ion_string_module_count).flat_map(
                move |lithium_ion_string_module_index| {
                    let lithium_ion_string_module_address =
                        48 + lithium_ion_string_module_index * lithium_ion_string_module_size;
                    LITHIUM_ION_STRING_MODULE_POINTS.iter().map(move |p| {
                        (
                            lithium_ion_string_module_address + p.start_address,
                            p.size,
                            (p.point)(lithium_ion_string_module_index),
                        )
                    })
                },
            ))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model804,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(804);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::StringIndex => {
            buffer.write_u16(adapter.string_index());
        }
        Point::ModuleCount => {
            buffer.write_u16(adapter.module_count());
        }
        Point::StringStatus => {
            buffer.write_u32(adapter.string_status(), offset);
        }
        Point::ConnectionFailureReason => {
            if let Some(value) = adapter.connection_failure_reason() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::StringCellBalancingCount => {
            if let Some(value) = adapter.string_cell_balancing_count() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::StringStateOfCharge => {
            buffer.write_u16(adapter.string_state_of_charge());
        }
        Point::StringDepthOfDischarge => {
            if let Some(value) = adapter.string_depth_of_discharge() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::StringCycleCount => {
            if let Some(value) = adapter.string_cycle_count() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::StringStateOfHealth => {
            if let Some(value) = adapter.string_state_of_health() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::StringCurrent => {
            buffer.write_i16(adapter.string_current());
        }
        Point::StringVoltage => {
            if let Some(value) = adapter.string_voltage() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MaxCellVoltage => {
            buffer.write_u16(adapter.max_cell_voltage());
        }
        Point::MaxCellVoltageModule => {
            if let Some(value) = adapter.max_cell_voltage_module() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MinCellVoltage => {
            buffer.write_u16(adapter.min_cell_voltage());
        }
        Point::MinCellVoltageModule => {
            if let Some(value) = adapter.min_cell_voltage_module() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::AverageCellVoltage => {
            buffer.write_u16(adapter.average_cell_voltage());
        }
        Point::MaxModuleTemperature => {
            buffer.write_i16(adapter.max_module_temperature());
        }
        Point::MaxModuleTemperatureModule => {
            buffer.write_u16(adapter.max_module_temperature_module());
        }
        Point::MinModuleTemperature => {
            buffer.write_i16(adapter.min_module_temperature());
        }
        Point::MinModuleTemperatureModule => {
            buffer.write_u16(adapter.min_module_temperature_module());
        }
        Point::AverageModuleTemperature => {
            buffer.write_i16(adapter.average_module_temperature());
        }
        Point::Pad1 => {
            buffer.write_u16(0);
        }
        Point::ContactorStatus => {
            if let Some(value) = adapter.contactor_status() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::StringEvent1 => {
            buffer.write_u32(adapter.string_event_1(), offset);
        }
        Point::StringEvent2 => {
            if let Some(value) = adapter.string_event_2() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VendorEventBitfield1 => {
            if let Some(value) = adapter.vendor_event_bitfield_1() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VendorEventBitfield2 => {
            if let Some(value) = adapter.vendor_event_bitfield_2() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::EnableDisableString => {
            if let Some(value) = adapter.enable_disable_string() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ConnectDisconnectString => {
            if let Some(value) = adapter.connect_disconnect_string() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::SoCSf => {
            buffer.write_i16(adapter.so_c_sf());
        }
        Point::SoHSf => {
            if let Some(value) = adapter.so_h_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::DoDSf => {
            if let Some(value) = adapter.do_d_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ASf => {
            buffer.write_i16(adapter.a_sf());
        }
        Point::VSf => {
            if let Some(value) = adapter.v_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::CellVSf => {
            buffer.write_i16(adapter.cell_v_sf());
        }
        Point::ModTmpSf => {
            buffer.write_i16(adapter.mod_tmp_sf());
        }
        Point::Pad2 => {
            buffer.write_u16(0);
        }
        Point::Pad3 => {
            buffer.write_u16(0);
        }
        Point::Pad4 => {
            buffer.write_u16(0);
        }
        Point::LithiumIonStringModuleModuleCellCount {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(
                adapter
                    .lithium_ion_string_module_module_cell_count(*lithium_ion_string_module_index),
            );
        }
        Point::LithiumIonStringModuleModuleSoC {
            lithium_ion_string_module_index,
        } => {
            if let Some(value) =
                adapter.lithium_ion_string_module_module_so_c(*lithium_ion_string_module_index)
            {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::LithiumIonStringModuleModuleSoH {
            lithium_ion_string_module_index,
        } => {
            if let Some(value) =
                adapter.lithium_ion_string_module_module_so_h(*lithium_ion_string_module_index)
            {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::LithiumIonStringModuleMaxCellVoltage {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(
                adapter
                    .lithium_ion_string_module_max_cell_voltage(*lithium_ion_string_module_index),
            );
        }
        Point::LithiumIonStringModuleMaxCellVoltageCell {
            lithium_ion_string_module_index,
        } => {
            if let Some(value) = adapter
                .lithium_ion_string_module_max_cell_voltage_cell(*lithium_ion_string_module_index)
            {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::LithiumIonStringModuleMinCellVoltage {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(
                adapter
                    .lithium_ion_string_module_min_cell_voltage(*lithium_ion_string_module_index),
            );
        }
        Point::LithiumIonStringModuleMinCellVoltageCell {
            lithium_ion_string_module_index,
        } => {
            if let Some(value) = adapter
                .lithium_ion_string_module_min_cell_voltage_cell(*lithium_ion_string_module_index)
            {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::LithiumIonStringModuleAverageCellVoltage {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(
                adapter.lithium_ion_string_module_average_cell_voltage(
                    *lithium_ion_string_module_index,
                ),
            );
        }
        Point::LithiumIonStringModuleMaxCellTemperature {
            lithium_ion_string_module_index,
        } => {
            buffer.write_i16(
                adapter.lithium_ion_string_module_max_cell_temperature(
                    *lithium_ion_string_module_index,
                ),
            );
        }
        Point::LithiumIonStringModuleMaxCellTemperatureCell {
            lithium_ion_string_module_index,
        } => {
            if let Some(value) = adapter.lithium_ion_string_module_max_cell_temperature_cell(
                *lithium_ion_string_module_index,
            ) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::LithiumIonStringModuleMinCellTemperature {
            lithium_ion_string_module_index,
        } => {
            buffer.write_i16(
                adapter.lithium_ion_string_module_min_cell_temperature(
                    *lithium_ion_string_module_index,
                ),
            );
        }
        Point::LithiumIonStringModuleMinCellTemperatureCell {
            lithium_ion_string_module_index,
        } => {
            if let Some(value) = adapter.lithium_ion_string_module_min_cell_temperature_cell(
                *lithium_ion_string_module_index,
            ) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::LithiumIonStringModuleAverageCellTemperature {
            lithium_ion_string_module_index,
        } => {
            buffer.write_i16(adapter.lithium_ion_string_module_average_cell_temperature(
                *lithium_ion_string_module_index,
            ));
        }
        Point::Pad5 {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(0);
        }
        Point::Pad6 {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(0);
        }
        Point::Pad7 {
            lithium_ion_string_module_index,
        } => {
            buffer.write_u16(0);
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model804,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::EnableDisableString => {
            let value = buffer.read_u16()?;
            adapter.set_enable_disable_string(value);
            Ok(())
        }
        Point::ConnectDisconnectString => {
            let value = buffer.read_u16()?;
            let enum_value = SetCon::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_connect_disconnect_string(enum_value);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// String Index (Idx)
    ///
    /// Index of the string within the bank.
    ///
    /// Indices are one-based.
    fn string_index(&self) -> u16;

    /// Module Count (NMod)
    ///
    /// Count of modules in the string.
    fn module_count(&self) -> u16;

    /// String Status (St)
    ///
    /// Current status of the string.
    fn string_status(&self) -> u32;

    /// Connection Failure Reason (ConFail)
    fn connection_failure_reason(&self) -> Option<ConFail> {
        None
    }

    /// String Cell Balancing Count (NCellBal)
    ///
    /// Number of cells currently being balanced in the string.
    fn string_cell_balancing_count(&self) -> Option<u16> {
        None
    }

    /// String State of Charge (SoC)
    ///
    /// Battery string state of charge, expressed as a percentage.
    ///
    /// Measurement.
    fn string_state_of_charge(&self) -> u16;

    /// String Depth of Discharge (DoD)
    ///
    /// Depth of discharge for the string, expressed as a percentage.
    ///
    /// Measurement.
    fn string_depth_of_discharge(&self) -> Option<u16> {
        None
    }

    /// String Cycle Count (NCyc)
    ///
    /// Number of discharge cycles executed upon the string.
    fn string_cycle_count(&self) -> Option<u32> {
        None
    }

    /// String State of Health (SoH)
    ///
    /// Battery string state of health, expressed as a percentage.
    ///
    /// Measurement.
    fn string_state_of_health(&self) -> Option<u16> {
        None
    }

    /// String Current (A)
    ///
    /// String current measurement.
    ///
    /// Measurement.
    fn string_current(&self) -> i16;

    /// String Voltage (V)
    ///
    /// String voltage measurement.
    ///
    /// Measurement.
    fn string_voltage(&self) -> Option<u16> {
        None
    }

    /// Max Cell Voltage (CellVMax)
    ///
    /// Maximum voltage for all cells in the string.
    ///
    /// Measurement.
    fn max_cell_voltage(&self) -> u16;

    /// Max Cell Voltage Module (CellVMaxMod)
    ///
    /// Module containing the cell with maximum cell voltage.
    fn max_cell_voltage_module(&self) -> Option<u16> {
        None
    }

    /// Min Cell Voltage (CellVMin)
    ///
    /// Minimum voltage for all cells in the string.
    ///
    /// Measurement.
    fn min_cell_voltage(&self) -> u16;

    /// Min Cell Voltage Module (CellVMinMod)
    ///
    /// Module containing the cell with minimum cell voltage.
    fn min_cell_voltage_module(&self) -> Option<u16> {
        None
    }

    /// Average Cell Voltage (CellVAvg)
    ///
    /// Average voltage for all cells in the string.
    ///
    /// Calculation based on measurements.
    fn average_cell_voltage(&self) -> u16;

    /// Max Module Temperature (ModTmpMax)
    ///
    /// Maximum temperature for all modules in the string.
    ///
    /// Measurement.
    fn max_module_temperature(&self) -> i16;

    /// Max Module Temperature Module (ModTmpMaxMod)
    ///
    /// Module with the maximum temperature.
    fn max_module_temperature_module(&self) -> u16;

    /// Min Module Temperature (ModTmpMin)
    ///
    /// Minimum temperature for all modules in the string.
    ///
    /// Measurement.
    fn min_module_temperature(&self) -> i16;

    /// Min Module Temperature Module (ModTmpMinMod)
    ///
    /// Module with the minimum temperature.
    fn min_module_temperature_module(&self) -> u16;

    /// Average Module Temperature (ModTmpAvg)
    ///
    /// Average temperature for all modules in the string.
    ///
    /// Calculation based on measurements.
    fn average_module_temperature(&self) -> i16;

    /// Contactor Status (ConSt)
    ///
    /// Status of the contactor(s) for the string.
    fn contactor_status(&self) -> Option<u32> {
        None
    }

    /// String Event 1 (Evt1)
    ///
    /// Alarms, warnings and status values.
    fn string_event_1(&self) -> u32;

    /// String Event 2 (Evt2)
    ///
    /// Alarms, warnings and status values.
    ///
    /// Reserved for future use.
    fn string_event_2(&self) -> Option<u32> {
        None
    }

    /// Vendor Event Bitfield 1 (EvtVnd1)
    ///
    /// Vendor defined events.
    fn vendor_event_bitfield_1(&self) -> Option<u32> {
        None
    }

    /// Vendor Event Bitfield 2 (EvtVnd2)
    ///
    /// Vendor defined events.
    fn vendor_event_bitfield_2(&self) -> Option<u32> {
        None
    }

    /// Enable/Disable String (SetEna)
    ///
    /// Enables and disables the string. Should reset to 0 upon completion.
    fn enable_disable_string(&self) -> Option<u16> {
        None
    }

    /// Connect/Disconnect String (SetCon)
    ///
    /// Connects and disconnects the string.
    ///
    /// Should reset to 0 upon completion.
    fn connect_disconnect_string(&self) -> Option<SetCon> {
        None
    }

    /// SoC_SF
    ///
    /// Scale factor for string state of charge.
    fn so_c_sf(&self) -> i16;

    /// SoH_SF
    ///
    /// Scale factor for string state of health.
    fn so_h_sf(&self) -> Option<i16> {
        None
    }

    /// DoD_SF
    ///
    /// Scale factor for string depth of discharge.
    fn do_d_sf(&self) -> Option<i16> {
        None
    }

    /// A_SF
    ///
    /// Scale factor for string current.
    fn a_sf(&self) -> i16;

    /// V_SF
    ///
    /// Scale factor for string voltage.
    fn v_sf(&self) -> Option<i16> {
        None
    }

    /// CellV_SF
    ///
    /// Scale factor for cell voltage.
    fn cell_v_sf(&self) -> i16;

    /// ModTmp_SF
    ///
    /// Scale factor for module temperature.
    fn mod_tmp_sf(&self) -> i16;

    /// Module Cell Count (ModNCell)
    ///
    /// Count of all cells in the module.
    fn lithium_ion_string_module_module_cell_count(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> u16;

    /// Module SoC (ModSoC)
    ///
    /// Module state of charge, expressed as a percentage.
    fn lithium_ion_string_module_module_so_c(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Module SoH (ModSoH)
    ///
    /// Module state of health, expressed as a percentage.
    fn lithium_ion_string_module_module_so_h(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Max Cell Voltage (ModCellVMax)
    ///
    /// Maximum voltage for all cells in the module.
    fn lithium_ion_string_module_max_cell_voltage(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> u16;

    /// Max Cell Voltage Cell (ModCellVMaxCell)
    ///
    /// Cell with maximum voltage.
    fn lithium_ion_string_module_max_cell_voltage_cell(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Min Cell Voltage (ModCellVMin)
    ///
    /// Minimum voltage for all cells in the module.
    fn lithium_ion_string_module_min_cell_voltage(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> u16;

    /// Min Cell Voltage Cell (ModCellVMinCell)
    ///
    /// Cell with minimum voltage.
    fn lithium_ion_string_module_min_cell_voltage_cell(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Average Cell Voltage (ModCellVAvg)
    ///
    /// Average voltage for all cells in the module.
    fn lithium_ion_string_module_average_cell_voltage(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> u16;

    /// Max Cell Temperature (ModCellTmpMax)
    ///
    /// Maximum temperature for all cells in the module.
    fn lithium_ion_string_module_max_cell_temperature(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> i16;

    /// Max Cell Temperature Cell (ModCellTmpMaxCell)
    ///
    /// Cell with maximum temperature.
    fn lithium_ion_string_module_max_cell_temperature_cell(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Min Cell Temperature (ModCellTmpMin)
    ///
    /// Minimum temperature for all cells in the module.
    fn lithium_ion_string_module_min_cell_temperature(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> i16;

    /// Min Cell Temperature Cell (ModCellTmpMinCell)
    ///
    /// Cell with minimum temperature.
    fn lithium_ion_string_module_min_cell_temperature_cell(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Average Cell Temperature (ModCellTmpAvg)
    ///
    /// Average temperature for all cells in the module.
    fn lithium_ion_string_module_average_cell_temperature(
        &self,
        lithium_ion_string_module_index: u16,
    ) -> i16;
}

pub trait WriteAdapter {
    /// Enable/Disable String (SetEna)
    ///
    /// Enables and disables the string. Should reset to 0 upon completion.
    fn set_enable_disable_string(&mut self, value: u16) {}

    /// Connect/Disconnect String (SetCon)
    ///
    /// Connects and disconnects the string.
    ///
    /// Should reset to 0 upon completion.
    fn set_connect_disconnect_string(&mut self, value: SetCon) {}
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model804ConFail {
    NoFailure = 0,
    ButtonPushed = 1,
    StrGroundFault = 2,
    OutsideVoltageRange = 3,
    StringNotEnabled = 4,
    FuseOpen = 5,
    ContactorFailure = 6,
    PrechargeFailure = 7,
    /// See Evt1 for more information.
    StringFault = 8,
}

impl Model804ConFail {
    pub fn from_repr(repr: u16) -> Option<Model804ConFail> {
        match repr {
            0 => Some(Model804ConFail::NoFailure),
            1 => Some(Model804ConFail::ButtonPushed),
            2 => Some(Model804ConFail::StrGroundFault),
            3 => Some(Model804ConFail::OutsideVoltageRange),
            4 => Some(Model804ConFail::StringNotEnabled),
            5 => Some(Model804ConFail::FuseOpen),
            6 => Some(Model804ConFail::ContactorFailure),
            7 => Some(Model804ConFail::PrechargeFailure),
            8 => Some(Model804ConFail::StringFault),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model804ConFail`] - only `Model804ConFail` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `ConFail` distinct from another model's point of the same name.
pub type ConFail = Model804ConFail;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model804SetCon {
    ConnectString = 1,
    DisconnectString = 2,
}

impl Model804SetCon {
    pub fn from_repr(repr: u16) -> Option<Model804SetCon> {
        match repr {
            1 => Some(Model804SetCon::ConnectString),
            2 => Some(Model804SetCon::DisconnectString),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model804SetCon`] - only `Model804SetCon` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `SetCon` distinct from another model's point of the same name.
pub type SetCon = Model804SetCon;
