// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::model::ModelSpec;
use core::cmp::min;
use core::ffi::CStr;

static POINTS: [PointDetails<()>; 50] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::ActivePhases,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::PhaseAngle,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::NominalVoltage,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::MaximumVoltage,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::MaximumCurrent,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::Frequency,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::OutputState,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::RelayState,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::RegenerationState,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::VoltageSetpoint,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::VoltageSetpointPhaseA,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::VoltageSetpointPhaseB,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::VoltageSetpointPhaseC,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::FrequencySlewRate,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::VoltageSlewRate,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::MeasuredVoltagePhaseA,
        size: 2,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::MeasuredVoltagePhaseB,
        size: 2,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::MeasuredVoltagePhaseC,
        size: 2,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::MeasuredFrequency,
        size: 2,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::MeasuredCurrentPhaseA,
        size: 2,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::MeasuredCurrentPhaseB,
        size: 2,
        start_address: 27,
    },
    PointDetails {
        point: |()| Point::MeasuredCurrentPhaseC,
        size: 2,
        start_address: 29,
    },
    PointDetails {
        point: |()| Point::VoltageHarmonicsPhaseA,
        size: 150,
        start_address: 31,
    },
    PointDetails {
        point: |()| Point::VoltageHarmonicsPhaseB,
        size: 150,
        start_address: 181,
    },
    PointDetails {
        point: |()| Point::VoltageHarmonicsPhaseC,
        size: 150,
        start_address: 331,
    },
    PointDetails {
        point: |()| Point::CurrentHarmonicsPhaseA,
        size: 150,
        start_address: 481,
    },
    PointDetails {
        point: |()| Point::CurrentHarmonicsPhaseB,
        size: 150,
        start_address: 631,
    },
    PointDetails {
        point: |()| Point::CurrentHarmonicsPhaseC,
        size: 150,
        start_address: 781,
    },
    PointDetails {
        point: |()| Point::CurrentInterharmonicsPhaseA,
        size: 150,
        start_address: 931,
    },
    PointDetails {
        point: |()| Point::CurrentInterharmonicsPhaseB,
        size: 150,
        start_address: 1081,
    },
    PointDetails {
        point: |()| Point::CurrentInterharmonicsPhaseC,
        size: 150,
        start_address: 1231,
    },
    PointDetails {
        point: |()| Point::VoltageThdPhaseA,
        size: 1,
        start_address: 1381,
    },
    PointDetails {
        point: |()| Point::VoltageThdPhaseB,
        size: 1,
        start_address: 1382,
    },
    PointDetails {
        point: |()| Point::VoltageThdPhaseC,
        size: 1,
        start_address: 1383,
    },
    PointDetails {
        point: |()| Point::CurrentThdPhaseA,
        size: 1,
        start_address: 1384,
    },
    PointDetails {
        point: |()| Point::CurrentThdPhaseB,
        size: 1,
        start_address: 1385,
    },
    PointDetails {
        point: |()| Point::CurrentThdPhaseC,
        size: 1,
        start_address: 1386,
    },
    PointDetails {
        point: |()| Point::EnableProfile,
        size: 1,
        start_address: 1387,
    },
    PointDetails {
        point: |()| Point::ProfileResult,
        size: 1,
        start_address: 1388,
    },
    PointDetails {
        point: |()| Point::StoredProfileCount,
        size: 1,
        start_address: 1389,
    },
    PointDetails {
        point: |()| Point::MaxProfilePointCount,
        size: 1,
        start_address: 1390,
    },
    PointDetails {
        point: |()| Point::VoltageScaleFactor,
        size: 1,
        start_address: 1391,
    },
    PointDetails {
        point: |()| Point::CurrentScaleFactor,
        size: 1,
        start_address: 1392,
    },
    PointDetails {
        point: |()| Point::TimeScaleFactor,
        size: 1,
        start_address: 1393,
    },
    PointDetails {
        point: |()| Point::FrequencyScaleFactor,
        size: 1,
        start_address: 1394,
    },
    PointDetails {
        point: |()| Point::FrequencySlewRateScaleFactor,
        size: 1,
        start_address: 1395,
    },
    PointDetails {
        point: |()| Point::VoltageSlewRateScaleFactor,
        size: 1,
        start_address: 1396,
    },
    PointDetails {
        point: |()| Point::ThdScaleFactor,
        size: 1,
        start_address: 1397,
    },
];

static PROF_POINTS: [PointDetails<u16>; 2] = [
    PointDetails {
        point: |prof_index| Point::ProfProfileName { prof_index },
        size: 32,
        start_address: 0,
    },
    PointDetails {
        point: |prof_index| Point::ProfActivePoints { prof_index },
        size: 1,
        start_address: 32,
    },
];

static PT_POINTS: [PointDetails<(u16, u16)>; 8] = [
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtProfileTime {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtVoltagePoint {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtVoltagePointPhaseB {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtVoltagePointPhaseC {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtFrequencyPoint {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtPhaseAngleA {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtPhaseAngleB {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |(prof_index, pt_index)| Point::PtPhaseAngleC {
            prof_index,
            pt_index,
        },
        size: 1,
        start_address: 7,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    ActivePhases,
    PhaseAngle,
    NominalVoltage,
    MaximumVoltage,
    MaximumCurrent,
    Frequency,
    OutputState,
    RelayState,
    RegenerationState,
    VoltageSetpoint,
    VoltageSetpointPhaseA,
    VoltageSetpointPhaseB,
    VoltageSetpointPhaseC,
    FrequencySlewRate,
    VoltageSlewRate,
    MeasuredVoltagePhaseA,
    MeasuredVoltagePhaseB,
    MeasuredVoltagePhaseC,
    MeasuredFrequency,
    MeasuredCurrentPhaseA,
    MeasuredCurrentPhaseB,
    MeasuredCurrentPhaseC,
    VoltageHarmonicsPhaseA,
    VoltageHarmonicsPhaseB,
    VoltageHarmonicsPhaseC,
    CurrentHarmonicsPhaseA,
    CurrentHarmonicsPhaseB,
    CurrentHarmonicsPhaseC,
    CurrentInterharmonicsPhaseA,
    CurrentInterharmonicsPhaseB,
    CurrentInterharmonicsPhaseC,
    VoltageThdPhaseA,
    VoltageThdPhaseB,
    VoltageThdPhaseC,
    CurrentThdPhaseA,
    CurrentThdPhaseB,
    CurrentThdPhaseC,
    EnableProfile,
    ProfileResult,
    StoredProfileCount,
    MaxProfilePointCount,
    VoltageScaleFactor,
    CurrentScaleFactor,
    TimeScaleFactor,
    FrequencyScaleFactor,
    FrequencySlewRateScaleFactor,
    VoltageSlewRateScaleFactor,
    ThdScaleFactor,
    ProfProfileName { prof_index: u16 },
    ProfActivePoints { prof_index: u16 },
    PtProfileTime { prof_index: u16, pt_index: u16 },
    PtVoltagePoint { prof_index: u16, pt_index: u16 },
    PtVoltagePointPhaseB { prof_index: u16, pt_index: u16 },
    PtVoltagePointPhaseC { prof_index: u16, pt_index: u16 },
    PtFrequencyPoint { prof_index: u16, pt_index: u16 },
    PtPhaseAngleA { prof_index: u16, pt_index: u16 },
    PtPhaseAngleB { prof_index: u16, pt_index: u16 },
    PtPhaseAngleC { prof_index: u16, pt_index: u16 },
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 64411. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model64411 {
    /// Number of repeating blocks in this model instance.
    pub stored_profile_count: u16,
    /// Number of repeating blocks in this model instance.
    pub max_profile_point_count: u16,
}

impl<'ad> ModelSpec<'ad> for Model64411 {
    const MODEL_ID: u16 = 64411;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        1398 + self.stored_profile_count * (33 + self.max_profile_point_count * (8))
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let pt_count = self.max_profile_point_count;
        let pt_size = 8;

        let prof_count = self.stored_profile_count;
        let prof_size = 33 + pt_count * pt_size;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain((0..prof_count).flat_map(move |prof_index| {
                let prof_address = 1398 + prof_index * prof_size;
                PROF_POINTS
                    .iter()
                    .map(move |p| {
                        (
                            prof_address + p.start_address,
                            p.size,
                            (p.point)(prof_index),
                        )
                    })
                    .chain((0..pt_count).flat_map(move |pt_index| {
                        let pt_address = prof_address + 33 + pt_index * pt_size;
                        PT_POINTS.iter().map(move |p| {
                            (
                                pt_address + p.start_address,
                                p.size,
                                (p.point)((prof_index, pt_index)),
                            )
                        })
                    }))
            }))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let pt_count = self.max_profile_point_count;
        let pt_size = 8;

        let prof_count = self.stored_profile_count;
        let prof_size = 33 + pt_count * pt_size;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain((0..prof_count).flat_map(move |prof_index| {
                let prof_address = 1398 + prof_index * prof_size;
                PROF_POINTS
                    .iter()
                    .map(move |p| {
                        (
                            prof_address + p.start_address,
                            p.size,
                            (p.point)(prof_index),
                        )
                    })
                    .chain((0..pt_count).flat_map(move |pt_index| {
                        let pt_address = prof_address + 33 + pt_index * pt_size;
                        PT_POINTS.iter().map(move |p| {
                            (
                                pt_address + p.start_address,
                                p.size,
                                (p.point)((prof_index, pt_index)),
                            )
                        })
                    }))
            }))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model64411,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(64411);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::ActivePhases => {
            if let Some(value) = adapter.active_phases() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseAngle => {
            if let Some(value) = adapter.phase_angle() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::NominalVoltage => {
            if let Some(value) = adapter.nominal_voltage() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MaximumVoltage => {
            if let Some(value) = adapter.maximum_voltage() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MaximumCurrent => {
            if let Some(value) = adapter.maximum_current() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Frequency => {
            if let Some(value) = adapter.frequency() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::OutputState => {
            if let Some(value) = adapter.output_state() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::RelayState => {
            if let Some(value) = adapter.relay_state() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::RegenerationState => {
            if let Some(value) = adapter.regeneration_state() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageSetpoint => {
            if let Some(value) = adapter.voltage_setpoint() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageSetpointPhaseA => {
            if let Some(value) = adapter.voltage_setpoint_phase_a() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageSetpointPhaseB => {
            if let Some(value) = adapter.voltage_setpoint_phase_b() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageSetpointPhaseC => {
            if let Some(value) = adapter.voltage_setpoint_phase_c() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::FrequencySlewRate => {
            if let Some(value) = adapter.frequency_slew_rate() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageSlewRate => {
            if let Some(value) = adapter.voltage_slew_rate() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredVoltagePhaseA => {
            if let Some(value) = adapter.measured_voltage_phase_a() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredVoltagePhaseB => {
            if let Some(value) = adapter.measured_voltage_phase_b() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredVoltagePhaseC => {
            if let Some(value) = adapter.measured_voltage_phase_c() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredFrequency => {
            if let Some(value) = adapter.measured_frequency() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredCurrentPhaseA => {
            if let Some(value) = adapter.measured_current_phase_a() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredCurrentPhaseB => {
            if let Some(value) = adapter.measured_current_phase_b() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MeasuredCurrentPhaseC => {
            if let Some(value) = adapter.measured_current_phase_c() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageHarmonicsPhaseA => {
            if let Some(value) = adapter.voltage_harmonics_phase_a() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageHarmonicsPhaseB => {
            if let Some(value) = adapter.voltage_harmonics_phase_b() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageHarmonicsPhaseC => {
            if let Some(value) = adapter.voltage_harmonics_phase_c() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentHarmonicsPhaseA => {
            if let Some(value) = adapter.current_harmonics_phase_a() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentHarmonicsPhaseB => {
            if let Some(value) = adapter.current_harmonics_phase_b() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentHarmonicsPhaseC => {
            if let Some(value) = adapter.current_harmonics_phase_c() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentInterharmonicsPhaseA => {
            if let Some(value) = adapter.current_interharmonics_phase_a() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentInterharmonicsPhaseB => {
            if let Some(value) = adapter.current_interharmonics_phase_b() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentInterharmonicsPhaseC => {
            if let Some(value) = adapter.current_interharmonics_phase_c() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageThdPhaseA => {
            if let Some(value) = adapter.voltage_thd_phase_a() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageThdPhaseB => {
            if let Some(value) = adapter.voltage_thd_phase_b() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageThdPhaseC => {
            if let Some(value) = adapter.voltage_thd_phase_c() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentThdPhaseA => {
            if let Some(value) = adapter.current_thd_phase_a() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentThdPhaseB => {
            if let Some(value) = adapter.current_thd_phase_b() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentThdPhaseC => {
            if let Some(value) = adapter.current_thd_phase_c() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::EnableProfile => {
            if let Some(value) = adapter.enable_profile() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::ProfileResult => {
            buffer.write_u16(adapter.profile_result() as u16);
        }
        Point::StoredProfileCount => {
            buffer.write_u16(adapter.stored_profile_count());
        }
        Point::MaxProfilePointCount => {
            buffer.write_u16(adapter.max_profile_point_count());
        }
        Point::VoltageScaleFactor => {
            buffer.write_i16(adapter.voltage_scale_factor());
        }
        Point::CurrentScaleFactor => {
            buffer.write_i16(adapter.current_scale_factor());
        }
        Point::TimeScaleFactor => {
            buffer.write_i16(adapter.time_scale_factor());
        }
        Point::FrequencyScaleFactor => {
            buffer.write_i16(adapter.frequency_scale_factor());
        }
        Point::FrequencySlewRateScaleFactor => {
            buffer.write_i16(adapter.frequency_slew_rate_scale_factor());
        }
        Point::VoltageSlewRateScaleFactor => {
            buffer.write_i16(adapter.voltage_slew_rate_scale_factor());
        }
        Point::ThdScaleFactor => {
            buffer.write_i16(adapter.thd_scale_factor());
        }
        Point::ProfProfileName { prof_index } => {
            if let Some(value) = adapter.prof_profile_name(*prof_index) {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::ProfActivePoints { prof_index } => {
            buffer.write_u16(adapter.prof_active_points(*prof_index));
        }
        Point::PtProfileTime {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_profile_time(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtVoltagePoint {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_voltage_point(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtVoltagePointPhaseB {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_voltage_point_phase_b(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtVoltagePointPhaseC {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_voltage_point_phase_c(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtFrequencyPoint {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_frequency_point(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtPhaseAngleA {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_phase_angle_a(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtPhaseAngleB {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_phase_angle_b(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PtPhaseAngleC {
            prof_index,
            pt_index,
        } => {
            if let Some(value) = adapter.pt_phase_angle_c(*prof_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model64411,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::ActivePhases => {
            let value = buffer.read_u16()?;
            adapter.set_active_phases(value);
            Ok(())
        }
        Point::PhaseAngle => {
            let value = buffer.read_u16()?;
            adapter.set_phase_angle(value);
            Ok(())
        }
        Point::NominalVoltage => {
            let value = buffer.read_u16()?;
            adapter.set_nominal_voltage(value);
            Ok(())
        }
        Point::MaximumVoltage => {
            let value = buffer.read_u16()?;
            adapter.set_maximum_voltage(value);
            Ok(())
        }
        Point::MaximumCurrent => {
            let value = buffer.read_u16()?;
            adapter.set_maximum_current(value);
            Ok(())
        }
        Point::Frequency => {
            let value = buffer.read_u16()?;
            adapter.set_frequency(value);
            Ok(())
        }
        Point::OutputState => {
            let value = buffer.read_u16()?;
            let enum_value = Output::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_output_state(enum_value);
            Ok(())
        }
        Point::RelayState => {
            let value = buffer.read_u16()?;
            let enum_value = Relay::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_relay_state(enum_value);
            Ok(())
        }
        Point::RegenerationState => {
            let value = buffer.read_u16()?;
            let enum_value = Regen::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_regeneration_state(enum_value);
            Ok(())
        }
        Point::VoltageSetpoint => {
            let value = buffer.read_u16()?;
            adapter.set_voltage_setpoint(value);
            Ok(())
        }
        Point::VoltageSetpointPhaseA => {
            let value = buffer.read_u16()?;
            adapter.set_voltage_setpoint_phase_a(value);
            Ok(())
        }
        Point::VoltageSetpointPhaseB => {
            let value = buffer.read_u16()?;
            adapter.set_voltage_setpoint_phase_b(value);
            Ok(())
        }
        Point::VoltageSetpointPhaseC => {
            let value = buffer.read_u16()?;
            adapter.set_voltage_setpoint_phase_c(value);
            Ok(())
        }
        Point::FrequencySlewRate => {
            let value = buffer.read_u16()?;
            adapter.set_frequency_slew_rate(value);
            Ok(())
        }
        Point::VoltageSlewRate => {
            let value = buffer.read_u16()?;
            adapter.set_voltage_slew_rate(value);
            Ok(())
        }
        Point::EnableProfile => {
            let value = buffer.read_u16()?;
            let enum_value = EnaProf::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_enable_profile(enum_value);
            Ok(())
        }
        Point::ProfProfileName { prof_index } => {
            let value = buffer.read_string::<64>()?;
            let str_value =
                CStr::from_bytes_with_nul(&value).map_err(|_| ModbusException::IllegalDataValue)?;
            adapter.set_prof_profile_name(str_value, *prof_index);
            Ok(())
        }
        Point::ProfActivePoints { prof_index } => {
            let value = buffer.read_u16()?;
            adapter.set_prof_active_points(value, *prof_index);
            Ok(())
        }
        Point::PtProfileTime {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_profile_time(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtVoltagePoint {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_voltage_point(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtVoltagePointPhaseB {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_voltage_point_phase_b(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtVoltagePointPhaseC {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_voltage_point_phase_c(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtFrequencyPoint {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_frequency_point(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtPhaseAngleA {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_phase_angle_a(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtPhaseAngleB {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_phase_angle_b(value, *prof_index, *pt_index);
            Ok(())
        }
        Point::PtPhaseAngleC {
            prof_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_pt_phase_angle_c(value, *prof_index, *pt_index);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// Active Phases (Phases)
    ///
    /// Set the number of active phases for the power supply
    fn active_phases(&self) -> Option<u16> {
        None
    }

    /// Phase Angle (PhaseAngle)
    ///
    /// Phase angle (deg) between phases. 0 for signle phase, 120 for two phase, 120 for three phase.
    fn phase_angle(&self) -> Option<u16> {
        None
    }

    /// Nominal Voltage (VNom)
    ///
    /// Nominal L-N Voltage
    fn nominal_voltage(&self) -> Option<u16> {
        None
    }

    /// Maximum Voltage (VMax)
    ///
    /// Maximum Voltage Protection Level
    fn maximum_voltage(&self) -> Option<u16> {
        None
    }

    /// Maximum Current (IMax)
    ///
    /// Maximum Current Protection Level
    fn maximum_current(&self) -> Option<u16> {
        None
    }

    /// Frequency (Freq)
    ///
    /// Frequency Setpoint
    fn frequency(&self) -> Option<u16> {
        None
    }

    /// Output State (Output)
    ///
    /// AC Output State
    fn output_state(&self) -> Option<Output> {
        None
    }

    /// Relay State (Relay)
    ///
    /// AC Relay State
    fn relay_state(&self) -> Option<Relay> {
        None
    }

    /// Regeneration State (Regen)
    ///
    /// Regeneration State
    fn regeneration_state(&self) -> Option<Regen> {
        None
    }

    /// Voltage Setpoint (VSet)
    ///
    /// Voltage Setpoint (all phases)
    fn voltage_setpoint(&self) -> Option<u16> {
        None
    }

    /// Voltage Setpoint Phase A (VSetA)
    ///
    /// Voltage Setpoint Phase A
    fn voltage_setpoint_phase_a(&self) -> Option<u16> {
        None
    }

    /// Voltage Setpoint Phase B (VSetB)
    ///
    /// Voltage Setpoint Phase B
    fn voltage_setpoint_phase_b(&self) -> Option<u16> {
        None
    }

    /// Voltage Setpoint Phase C (VSetC)
    ///
    /// Voltage Setpoint Phase C
    fn voltage_setpoint_phase_c(&self) -> Option<u16> {
        None
    }

    /// Frequency Slew Rate (FreqSlew)
    ///
    /// Frequency Slew Rate
    fn frequency_slew_rate(&self) -> Option<u16> {
        None
    }

    /// Voltage Slew Rate (VSlew)
    ///
    /// Voltage Slew Rate
    fn voltage_slew_rate(&self) -> Option<u16> {
        None
    }

    /// Measured Voltage Phase A (VA)
    ///
    /// Measured Voltage Phase A
    fn measured_voltage_phase_a(&self) -> Option<i32> {
        None
    }

    /// Measured Voltage Phase B (VB)
    ///
    /// Measured Voltage Phase B
    fn measured_voltage_phase_b(&self) -> Option<i32> {
        None
    }

    /// Measured Voltage Phase C (VC)
    ///
    /// Measured Voltage Phase C
    fn measured_voltage_phase_c(&self) -> Option<i32> {
        None
    }

    /// Measured Frequency (Hz)
    ///
    /// Measured Frequency
    fn measured_frequency(&self) -> Option<i32> {
        None
    }

    /// Measured Current Phase A (IA)
    ///
    /// Measured Current Phase A
    fn measured_current_phase_a(&self) -> Option<i32> {
        None
    }

    /// Measured Current Phase B (IB)
    ///
    /// Measured Current Phase B
    fn measured_current_phase_b(&self) -> Option<i32> {
        None
    }

    /// Measured Current Phase C (IC)
    ///
    /// Measured Current Phase C
    fn measured_current_phase_c(&self) -> Option<i32> {
        None
    }

    /// Voltage Harmonics Phase A (VHarA)
    ///
    /// Voltage Harmonics Pct, Phase A (comma seperated string for harmonics 1-50)
    fn voltage_harmonics_phase_a(&self) -> Option<&CStr> {
        None
    }

    /// Voltage Harmonics Phase B (VHarB)
    ///
    /// Voltage Harmonics Pct, Phase B (comma seperated string for harmonics 1-50)
    fn voltage_harmonics_phase_b(&self) -> Option<&CStr> {
        None
    }

    /// Voltage Harmonics Phase C (VHarC)
    ///
    /// Voltage Harmonics Pct, Phase C (comma seperated string for harmonics 1-50)
    fn voltage_harmonics_phase_c(&self) -> Option<&CStr> {
        None
    }

    /// Current Harmonics Phase A (IHarA)
    ///
    /// Current Harmonics Pct, Phase A (comma seperated string for harmonics 1-50)
    fn current_harmonics_phase_a(&self) -> Option<&CStr> {
        None
    }

    /// Current Harmonics Phase B (IHarB)
    ///
    /// Current Harmonics Pct, Phase B (comma seperated string for harmonics 1-50)
    fn current_harmonics_phase_b(&self) -> Option<&CStr> {
        None
    }

    /// Current Harmonics Phase C (IHarC)
    ///
    /// Current Harmonics Pct, Phase C (comma seperated string for harmonics 1-50)
    fn current_harmonics_phase_c(&self) -> Option<&CStr> {
        None
    }

    /// Current Interharmonics Phase A (IIntHarA)
    ///
    /// Current Interharmonics Pct, Phase A (comma seperated string for interharmonics 1-50)
    fn current_interharmonics_phase_a(&self) -> Option<&CStr> {
        None
    }

    /// Current Interharmonics Phase B (IIntHarB)
    ///
    /// Current Interharmonics Pct, Phase B (comma seperated string for interharmonics 1-50)
    fn current_interharmonics_phase_b(&self) -> Option<&CStr> {
        None
    }

    /// Current Interharmonics Phase C (IIntHarC)
    ///
    /// Current Interharmonics Pct, Phase C (comma seperated string for interharmonics 1-50)
    fn current_interharmonics_phase_c(&self) -> Option<&CStr> {
        None
    }

    /// Voltage THD Phase A (VThdA)
    ///
    /// Voltage THD Phase A
    fn voltage_thd_phase_a(&self) -> Option<u16> {
        None
    }

    /// Voltage THD Phase B (VThdB)
    ///
    /// Voltage THD Phase B
    fn voltage_thd_phase_b(&self) -> Option<u16> {
        None
    }

    /// Voltage THD Phase C (VThdC)
    ///
    /// Voltage THD Phase C
    fn voltage_thd_phase_c(&self) -> Option<u16> {
        None
    }

    /// Current THD Phase A (IThdA)
    ///
    /// Current THD Phase A
    fn current_thd_phase_a(&self) -> Option<u16> {
        None
    }

    /// Current THD Phase B (IThdB)
    ///
    /// Current THD Phase B
    fn current_thd_phase_b(&self) -> Option<u16> {
        None
    }

    /// Current THD Phase C (IThdC)
    ///
    /// Current THD Phase C
    fn current_thd_phase_c(&self) -> Option<u16> {
        None
    }

    /// Enable Profile (EnaProf)
    ///
    /// Start/Stop the AC Profile
    fn enable_profile(&self) -> Option<EnaProf> {
        None
    }

    /// Profile Result (ProfRslt)
    ///
    /// Result of last profile operation.
    fn profile_result(&self) -> ProfRslt;

    /// Stored Profile Count (NProf)
    ///
    /// Number of stored profiles supported.
    fn stored_profile_count(&self) -> u16;

    /// Max Profile Point Count (NPt)
    ///
    /// Max profile points in the profiles.
    fn max_profile_point_count(&self) -> u16;

    /// Voltage Scale Factor (V_SF)
    ///
    /// Scale factor for voltage points.
    fn voltage_scale_factor(&self) -> i16;

    /// Current Scale Factor (A_SF)
    ///
    /// Scale factor for current points.
    fn current_scale_factor(&self) -> i16;

    /// Time Scale Factor (Tms_SF)
    ///
    /// Scale factor for time points.
    fn time_scale_factor(&self) -> i16;

    /// Frequency Scale Factor (Hz_SF)
    ///
    /// Scale factor for frequency points.
    fn frequency_scale_factor(&self) -> i16;

    /// Frequency Slew Rate Scale Factor (HzSlew_SF)
    ///
    /// Scale factor for frequency slew rate.
    fn frequency_slew_rate_scale_factor(&self) -> i16;

    /// Voltage Slew Rate Scale Factor (VSlew_SF)
    ///
    /// Scale factor for voltage slew rate.
    fn voltage_slew_rate_scale_factor(&self) -> i16;

    /// THD Scale Factor (THD_SF)
    ///
    /// Scale factor for THD values.
    fn thd_scale_factor(&self) -> i16;

    /// Profile Name (Name)
    ///
    /// Profile name.
    fn prof_profile_name(&self, prof_index: u16) -> Option<&CStr> {
        None
    }

    /// Active Points (ActPt)
    ///
    /// Number of active points.
    fn prof_active_points(&self, prof_index: u16) -> u16;

    /// Profile Time (Tms)
    ///
    /// Profile time.
    fn pt_profile_time(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Voltage Point (VA)
    ///
    /// Profile voltage phase A point in Volts.
    fn pt_voltage_point(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Voltage Point Phase B (VB)
    ///
    /// Profile voltage phase B point in Volts.
    fn pt_voltage_point_phase_b(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Voltage Point Phase C (VC)
    ///
    /// Profile voltage phase C point in Volts.
    fn pt_voltage_point_phase_c(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Frequency Point (Hz)
    ///
    /// Profile frequency point in Hz.
    fn pt_frequency_point(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Phase Angle A (PhaseAngleA)
    ///
    /// Profile phase A angle in degrees.
    fn pt_phase_angle_a(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Phase Angle B (PhaseAngleB)
    ///
    /// Profile phase B angle in degrees.
    fn pt_phase_angle_b(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Phase Angle C (PhaseAngleC)
    ///
    /// Profile phase C angle in degrees.
    fn pt_phase_angle_c(&self, prof_index: u16, pt_index: u16) -> Option<u16> {
        None
    }
}

pub trait WriteAdapter {
    /// Active Phases (Phases)
    ///
    /// Set the number of active phases for the power supply
    fn set_active_phases(&mut self, value: u16) {}

    /// Phase Angle (PhaseAngle)
    ///
    /// Phase angle (deg) between phases. 0 for signle phase, 120 for two phase, 120 for three phase.
    fn set_phase_angle(&mut self, value: u16) {}

    /// Nominal Voltage (VNom)
    ///
    /// Nominal L-N Voltage
    fn set_nominal_voltage(&mut self, value: u16) {}

    /// Maximum Voltage (VMax)
    ///
    /// Maximum Voltage Protection Level
    fn set_maximum_voltage(&mut self, value: u16) {}

    /// Maximum Current (IMax)
    ///
    /// Maximum Current Protection Level
    fn set_maximum_current(&mut self, value: u16) {}

    /// Frequency (Freq)
    ///
    /// Frequency Setpoint
    fn set_frequency(&mut self, value: u16) {}

    /// Output State (Output)
    ///
    /// AC Output State
    fn set_output_state(&mut self, value: Output) {}

    /// Relay State (Relay)
    ///
    /// AC Relay State
    fn set_relay_state(&mut self, value: Relay) {}

    /// Regeneration State (Regen)
    ///
    /// Regeneration State
    fn set_regeneration_state(&mut self, value: Regen) {}

    /// Voltage Setpoint (VSet)
    ///
    /// Voltage Setpoint (all phases)
    fn set_voltage_setpoint(&mut self, value: u16) {}

    /// Voltage Setpoint Phase A (VSetA)
    ///
    /// Voltage Setpoint Phase A
    fn set_voltage_setpoint_phase_a(&mut self, value: u16) {}

    /// Voltage Setpoint Phase B (VSetB)
    ///
    /// Voltage Setpoint Phase B
    fn set_voltage_setpoint_phase_b(&mut self, value: u16) {}

    /// Voltage Setpoint Phase C (VSetC)
    ///
    /// Voltage Setpoint Phase C
    fn set_voltage_setpoint_phase_c(&mut self, value: u16) {}

    /// Frequency Slew Rate (FreqSlew)
    ///
    /// Frequency Slew Rate
    fn set_frequency_slew_rate(&mut self, value: u16) {}

    /// Voltage Slew Rate (VSlew)
    ///
    /// Voltage Slew Rate
    fn set_voltage_slew_rate(&mut self, value: u16) {}

    /// Enable Profile (EnaProf)
    ///
    /// Start/Stop the AC Profile
    fn set_enable_profile(&mut self, value: EnaProf) {}

    /// Profile Name (Name)
    ///
    /// Profile name.
    fn set_prof_profile_name(&mut self, value: &CStr, prof_index: u16) {}

    /// Active Points (ActPt)
    ///
    /// Number of active points.
    fn set_prof_active_points(&mut self, value: u16, prof_index: u16);

    /// Profile Time (Tms)
    ///
    /// Profile time.
    fn set_pt_profile_time(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Voltage Point (VA)
    ///
    /// Profile voltage phase A point in Volts.
    fn set_pt_voltage_point(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Voltage Point Phase B (VB)
    ///
    /// Profile voltage phase B point in Volts.
    fn set_pt_voltage_point_phase_b(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Voltage Point Phase C (VC)
    ///
    /// Profile voltage phase C point in Volts.
    fn set_pt_voltage_point_phase_c(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Frequency Point (Hz)
    ///
    /// Profile frequency point in Hz.
    fn set_pt_frequency_point(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Phase Angle A (PhaseAngleA)
    ///
    /// Profile phase A angle in degrees.
    fn set_pt_phase_angle_a(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Phase Angle B (PhaseAngleB)
    ///
    /// Profile phase B angle in degrees.
    fn set_pt_phase_angle_b(&mut self, value: u16, prof_index: u16, pt_index: u16) {}

    /// Phase Angle C (PhaseAngleC)
    ///
    /// Profile phase C angle in degrees.
    fn set_pt_phase_angle_c(&mut self, value: u16, prof_index: u16, pt_index: u16) {}
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model64411EnaProf {
    /// Stop Profile
    Stop = 0,
    /// Start Profile Immediately
    Start = 1,
    /// Start Profile via External Trigger Signal
    Trigger = 2,
}

impl Model64411EnaProf {
    pub fn from_repr(repr: u16) -> Option<Model64411EnaProf> {
        match repr {
            0 => Some(Model64411EnaProf::Stop),
            1 => Some(Model64411EnaProf::Start),
            2 => Some(Model64411EnaProf::Trigger),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model64411EnaProf`] - only `Model64411EnaProf` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `EnaProf` distinct from another model's point of the same name.
pub type EnaProf = Model64411EnaProf;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model64411Output {
    /// Output Off
    Off = 0,
    /// Output On
    On = 1,
}

impl Model64411Output {
    pub fn from_repr(repr: u16) -> Option<Model64411Output> {
        match repr {
            0 => Some(Model64411Output::Off),
            1 => Some(Model64411Output::On),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model64411Output`] - only `Model64411Output` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Output` distinct from another model's point of the same name.
pub type Output = Model64411Output;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model64411ProfRslt {
    /// Profile update in progress.
    InProgress = 0,
    /// Profile update completed successfully.
    Completed = 1,
    /// Profile update failed.
    Failed = 2,
}

impl Model64411ProfRslt {
    pub fn from_repr(repr: u16) -> Option<Model64411ProfRslt> {
        match repr {
            0 => Some(Model64411ProfRslt::InProgress),
            1 => Some(Model64411ProfRslt::Completed),
            2 => Some(Model64411ProfRslt::Failed),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model64411ProfRslt`] - only `Model64411ProfRslt` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `ProfRslt` distinct from another model's point of the same name.
pub type ProfRslt = Model64411ProfRslt;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model64411Regen {
    /// Regen Off
    Off = 0,
    /// Regen On
    On = 1,
}

impl Model64411Regen {
    pub fn from_repr(repr: u16) -> Option<Model64411Regen> {
        match repr {
            0 => Some(Model64411Regen::Off),
            1 => Some(Model64411Regen::On),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model64411Regen`] - only `Model64411Regen` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Regen` distinct from another model's point of the same name.
pub type Regen = Model64411Regen;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model64411Relay {
    /// Relay Open
    Open = 0,
    /// Relay Closed
    Closed = 1,
}

impl Model64411Relay {
    pub fn from_repr(repr: u16) -> Option<Model64411Relay> {
        match repr {
            0 => Some(Model64411Relay::Open),
            1 => Some(Model64411Relay::Closed),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model64411Relay`] - only `Model64411Relay` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Relay` distinct from another model's point of the same name.
pub type Relay = Model64411Relay;
