// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::cursor::Cursor;
use crate::model::{ModelSpec, StaticModelSpec};
use core::cmp::min;
use core::ffi::{CStr, c_char, c_void};

static POINTS: [PointDetails<()>; 11] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::TimeOffset,
        size: 10,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::Temperature,
        size: 2,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::GridModelSource,
        size: 32,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::IrradianceModelSource,
        size: 32,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::Irradiance,
        size: 2,
        start_address: 78,
    },
    PointDetails {
        point: |()| Point::GridVoltageA,
        size: 2,
        start_address: 80,
    },
    PointDetails {
        point: |()| Point::GridVoltageB,
        size: 2,
        start_address: 82,
    },
    PointDetails {
        point: |()| Point::GridVoltageC,
        size: 2,
        start_address: 84,
    },
    PointDetails {
        point: |()| Point::GridFrequency,
        size: 2,
        start_address: 86,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    TimeOffset,
    Temperature,
    GridModelSource,
    IrradianceModelSource,
    Irradiance,
    GridVoltageA,
    GridVoltageB,
    GridVoltageC,
    GridFrequency,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 64414. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model64414;

impl<'ad> ModelSpec<'ad> for Model64414 {
    const MODEL_ID: u16 = 64414;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        88
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model64414,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(64414);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::TimeOffset => {
            if let Some(value) = adapter.time_offset() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Temperature => {
            if let Some(value) = adapter.temperature() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::GridModelSource => {
            if let Some(value) = adapter.grid_model_source() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::IrradianceModelSource => {
            if let Some(value) = adapter.irradiance_model_source() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Irradiance => {
            if let Some(value) = adapter.irradiance() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::GridVoltageA => {
            if let Some(value) = adapter.grid_voltage_a() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::GridVoltageB => {
            if let Some(value) = adapter.grid_voltage_b() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::GridVoltageC => {
            if let Some(value) = adapter.grid_voltage_c() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::GridFrequency => {
            if let Some(value) = adapter.grid_frequency() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model64414,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::Temperature => {
            let value = buffer.read_f32()?;
            adapter.set_temperature(value);
            Ok(())
        }
        Point::GridModelSource => {
            let value = buffer.read_string::<64>()?;
            let str_value =
                CStr::from_bytes_with_nul(&value).map_err(|_| ModbusException::IllegalDataValue)?;
            adapter.set_grid_model_source(str_value);
            Ok(())
        }
        Point::IrradianceModelSource => {
            let value = buffer.read_string::<64>()?;
            let str_value =
                CStr::from_bytes_with_nul(&value).map_err(|_| ModbusException::IllegalDataValue)?;
            adapter.set_irradiance_model_source(str_value);
            Ok(())
        }
        Point::Irradiance => {
            let value = buffer.read_f32()?;
            adapter.set_irradiance(value);
            Ok(())
        }
        Point::GridVoltageA => {
            let value = buffer.read_f32()?;
            adapter.set_grid_voltage_a(value);
            Ok(())
        }
        Point::GridVoltageB => {
            let value = buffer.read_f32()?;
            adapter.set_grid_voltage_b(value);
            Ok(())
        }
        Point::GridVoltageC => {
            let value = buffer.read_f32()?;
            adapter.set_grid_voltage_c(value);
            Ok(())
        }
        Point::GridFrequency => {
            let value = buffer.read_f32()?;
            adapter.set_grid_frequency(value);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// Time offset (Time)
    ///
    /// Time offset for simulation formatted 'HH:MM:SS'
    fn time_offset(&self) -> Option<&CStr> {
        None
    }

    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    fn temperature(&self) -> Option<f32> {
        None
    }

    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    fn grid_model_source(&self) -> Option<&CStr> {
        None
    }

    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    fn irradiance_model_source(&self) -> Option<&CStr> {
        None
    }

    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    fn irradiance(&self) -> Option<f32> {
        None
    }

    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    fn grid_voltage_a(&self) -> Option<f32> {
        None
    }

    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    fn grid_voltage_b(&self) -> Option<f32> {
        None
    }

    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    fn grid_voltage_c(&self) -> Option<f32> {
        None
    }

    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    fn grid_frequency(&self) -> Option<f32> {
        None
    }
}

pub trait WriteAdapter {
    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    fn set_temperature(&mut self, value: f32) {}

    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    fn set_grid_model_source(&mut self, value: &CStr) {}

    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    fn set_irradiance_model_source(&mut self, value: &CStr) {}

    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    fn set_irradiance(&mut self, value: f32) {}

    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_a(&mut self, value: f32) {}

    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_b(&mut self, value: f32) {}

    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_c(&mut self, value: f32) {}

    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    fn set_grid_frequency(&mut self, value: f32) {}
}

#[repr(C)]
pub struct Model64414CallbackAdapter {
    context: *mut c_void,
    /// Time offset (Time)
    ///
    /// Time offset for simulation formatted 'HH:MM:SS'
    time_offset_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    temperature_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    set_temperature_callback: Option<extern "C" fn(f32, *mut c_void)>,
    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    grid_model_source_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    set_grid_model_source_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    irradiance_model_source_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    set_irradiance_model_source_callback: Option<extern "C" fn(*const c_char, *mut c_void)>,
    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    irradiance_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    set_irradiance_callback: Option<extern "C" fn(f32, *mut c_void)>,
    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    grid_voltage_a_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    set_grid_voltage_a_callback: Option<extern "C" fn(f32, *mut c_void)>,
    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    grid_voltage_b_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    set_grid_voltage_b_callback: Option<extern "C" fn(f32, *mut c_void)>,
    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    grid_voltage_c_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    set_grid_voltage_c_callback: Option<extern "C" fn(f32, *mut c_void)>,
    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    grid_frequency_callback: Option<extern "C" fn(*const c_void) -> f32>,
    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    set_grid_frequency_callback: Option<extern "C" fn(f32, *mut c_void)>,
}

impl ReadAdapter for Model64414CallbackAdapter {
    fn time_offset(&self) -> Option<&CStr> {
        self.time_offset_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn temperature(&self) -> Option<f32> {
        self.temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn grid_model_source(&self) -> Option<&CStr> {
        self.grid_model_source_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn irradiance_model_source(&self) -> Option<&CStr> {
        self.irradiance_model_source_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }

    fn irradiance(&self) -> Option<f32> {
        self.irradiance_callback
            .map(|callback| (callback)(self.context))
    }

    fn grid_voltage_a(&self) -> Option<f32> {
        self.grid_voltage_a_callback
            .map(|callback| (callback)(self.context))
    }

    fn grid_voltage_b(&self) -> Option<f32> {
        self.grid_voltage_b_callback
            .map(|callback| (callback)(self.context))
    }

    fn grid_voltage_c(&self) -> Option<f32> {
        self.grid_voltage_c_callback
            .map(|callback| (callback)(self.context))
    }

    fn grid_frequency(&self) -> Option<f32> {
        self.grid_frequency_callback
            .map(|callback| (callback)(self.context))
    }
}

impl WriteAdapter for Model64414CallbackAdapter {
    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    fn set_temperature(&mut self, value: f32) {
        if let Some(callback) = self.set_temperature_callback {
            (callback)(value, self.context);
        };
    }

    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    fn set_grid_model_source(&mut self, value: &CStr) {
        if let Some(callback) = self.set_grid_model_source_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    fn set_irradiance_model_source(&mut self, value: &CStr) {
        if let Some(callback) = self.set_irradiance_model_source_callback {
            (callback)(value.as_ptr(), self.context);
        };
    }

    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    fn set_irradiance(&mut self, value: f32) {
        if let Some(callback) = self.set_irradiance_callback {
            (callback)(value, self.context);
        };
    }

    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_a(&mut self, value: f32) {
        if let Some(callback) = self.set_grid_voltage_a_callback {
            (callback)(value, self.context);
        };
    }

    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_b(&mut self, value: f32) {
        if let Some(callback) = self.set_grid_voltage_b_callback {
            (callback)(value, self.context);
        };
    }

    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_c(&mut self, value: f32) {
        if let Some(callback) = self.set_grid_voltage_c_callback {
            (callback)(value, self.context);
        };
    }

    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    fn set_grid_frequency(&mut self, value: f32) {
        if let Some(callback) = self.set_grid_frequency_callback {
            (callback)(value, self.context);
        };
    }
}

#[repr(C)]
pub struct Model64414StatefulAdapter {
    /// Time offset (Time)
    ///
    /// Time offset for simulation formatted 'HH:MM:SS'
    pub time_offset: [c_char; 20],
    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    pub temperature: f32,
    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    pub grid_model_source: [c_char; 64],
    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    pub irradiance_model_source: [c_char; 64],
    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    pub irradiance: f32,
    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    pub grid_voltage_a: f32,
    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    pub grid_voltage_b: f32,
    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    pub grid_voltage_c: f32,
    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    pub grid_frequency: f32,
}

impl ReadAdapter for Model64414StatefulAdapter {
    fn time_offset(&self) -> Option<&CStr> {
        Some(unsafe { CStr::from_ptr(self.time_offset.as_ptr()) })
    }

    fn temperature(&self) -> Option<f32> {
        Some(self.temperature)
    }

    fn grid_model_source(&self) -> Option<&CStr> {
        Some(unsafe { CStr::from_ptr(self.grid_model_source.as_ptr()) })
    }

    fn irradiance_model_source(&self) -> Option<&CStr> {
        Some(unsafe { CStr::from_ptr(self.irradiance_model_source.as_ptr()) })
    }

    fn irradiance(&self) -> Option<f32> {
        Some(self.irradiance)
    }

    fn grid_voltage_a(&self) -> Option<f32> {
        Some(self.grid_voltage_a)
    }

    fn grid_voltage_b(&self) -> Option<f32> {
        Some(self.grid_voltage_b)
    }

    fn grid_voltage_c(&self) -> Option<f32> {
        Some(self.grid_voltage_c)
    }

    fn grid_frequency(&self) -> Option<f32> {
        Some(self.grid_frequency)
    }
}

impl WriteAdapter for Model64414StatefulAdapter {
    /// Temperature
    ///
    /// Ambient temperature (degrees Celsius)
    fn set_temperature(&mut self, value: f32) {
        self.temperature = value;
    }

    /// GridModelSource
    ///
    /// The data source for the grid model. 'csv' or 'const'
    fn set_grid_model_source(&mut self, value: &CStr) {
        for (dest, src) in self
            .grid_model_source
            .iter_mut()
            .zip(value.to_bytes_with_nul().iter())
        {
            *dest = *src as c_char;
        }
    }

    /// IrradianceModelSource
    ///
    /// The data source for the irradiance model. 'csv' or 'const'
    fn set_irradiance_model_source(&mut self, value: &CStr) {
        for (dest, src) in self
            .irradiance_model_source
            .iter_mut()
            .zip(value.to_bytes_with_nul().iter())
        {
            *dest = *src as c_char;
        }
    }

    /// Irradiance
    ///
    /// The irradiance on the DER device (W/m^2) for the 'const' irradiance model
    fn set_irradiance(&mut self, value: f32) {
        self.irradiance = value;
    }

    /// GridVoltageA
    ///
    /// Phase A RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_a(&mut self, value: f32) {
        self.grid_voltage_a = value;
    }

    /// GridVoltageB
    ///
    /// Phase B RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_b(&mut self, value: f32) {
        self.grid_voltage_b = value;
    }

    /// GridVoltageC
    ///
    /// Phase C RMS Voltage (pu) for the 'const' grid model
    fn set_grid_voltage_c(&mut self, value: f32) {
        self.grid_voltage_c = value;
    }

    /// GridFrequency
    ///
    /// Grid frequency (Hz) for the 'const' grid model
    fn set_grid_frequency(&mut self, value: f32) {
        self.grid_frequency = value;
    }
}

/// C-FFI dispatch descriptor for SunSpec model 64414. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_64414: StaticModelSpec = StaticModelSpec {
    id: 64414,
    length: model_64414_c_length,
    writable: true,
    visit_read: model_64414_c_visit_read,
    visit_write: model_64414_c_visit_write,
};

fn model_64414_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model64414).model_length()
}

/// # Safety
/// For `kind` 1 or 2, `adapter` must point to a live `Model64414{Stateful,Callback}Adapter`,
/// valid for the duration of the call.
unsafe fn model_64414_c_visit_read(
    kind: u8,
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model64414;
    let adapter: Option<&dyn ReadAdapter> = match kind {
        1 => Some(unsafe { &*(adapter as *const Model64414StatefulAdapter) } as &dyn ReadAdapter),
        2 => Some(unsafe { &*(adapter as *const Model64414CallbackAdapter) } as &dyn ReadAdapter),
        _ => None,
    };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_64414_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_64414_c_visit_write(
    kind: u8,
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let model = Model64414;
    let adapter: Option<&mut dyn WriteAdapter> =
        match kind {
            1 => Some(unsafe { &mut *(adapter as *mut Model64414StatefulAdapter) }
                as &mut dyn WriteAdapter),
            2 => Some(unsafe { &mut *(adapter as *mut Model64414CallbackAdapter) }
                as &mut dyn WriteAdapter),
            _ => None,
        };
    cursor.visit_source_block(model.model_length(), |offset, from, len| match adapter {
        Some(adapter) => model.traverse_points_write(adapter, &buffer.slice(from, len), offset),
        None => Err(ModbusException::IllegalDataAddress),
    });
}
