// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::model::ModelSpec;
use core::cmp::min;

static POINTS: [PointDetails<()>; 19] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::Status,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::VendorStatus,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::Events,
        size: 2,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::VendorModuleEventFlags,
        size: 2,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::Control,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::VendorControl,
        size: 2,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::ControlValue,
        size: 2,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::Timestamp,
        size: 2,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::OutputCurrent,
        size: 2,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::OutputVoltage,
        size: 2,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::OutputEnergy,
        size: 2,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::OutputPower,
        size: 2,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::Temp,
        size: 2,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::InputCurrent,
        size: 2,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::InputVoltage,
        size: 2,
        start_address: 27,
    },
    PointDetails {
        point: |()| Point::InputEnergy,
        size: 2,
        start_address: 29,
    },
    PointDetails {
        point: |()| Point::InputPower,
        size: 2,
        start_address: 31,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    Status,
    VendorStatus,
    Events,
    VendorModuleEventFlags,
    Control,
    VendorControl,
    ControlValue,
    Timestamp,
    OutputCurrent,
    OutputVoltage,
    OutputEnergy,
    OutputPower,
    Temp,
    InputCurrent,
    InputVoltage,
    InputEnergy,
    InputPower,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 501. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model501;

impl<'ad> ModelSpec<'ad> for Model501 {
    const MODEL_ID: u16 = 501;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        33
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model501,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(501);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::Status => {
            buffer.write_u16(adapter.status() as u16);
        }
        Point::VendorStatus => {
            if let Some(value) = adapter.vendor_status() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Events => {
            buffer.write_u32(adapter.events(), offset);
        }
        Point::VendorModuleEventFlags => {
            if let Some(value) = adapter.vendor_module_event_flags() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Control => {
            if let Some(value) = adapter.control() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VendorControl => {
            if let Some(value) = adapter.vendor_control() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::ControlValue => {
            if let Some(value) = adapter.control_value() {
                buffer.write_i32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Timestamp => {
            if let Some(value) = adapter.timestamp() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::OutputCurrent => {
            if let Some(value) = adapter.output_current() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::OutputVoltage => {
            if let Some(value) = adapter.output_voltage() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::OutputEnergy => {
            if let Some(value) = adapter.output_energy() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::OutputPower => {
            if let Some(value) = adapter.output_power() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::Temp => {
            if let Some(value) = adapter.temp() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::InputCurrent => {
            if let Some(value) = adapter.input_current() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::InputVoltage => {
            if let Some(value) = adapter.input_voltage() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::InputEnergy => {
            if let Some(value) = adapter.input_energy() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::InputPower => {
            if let Some(value) = adapter.input_power() {
                buffer.write_f32(value, offset);
            } else {
                buffer.zero();
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model501,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::Control => {
            let value = buffer.read_u16()?;
            adapter.set_control(value);
            Ok(())
        }
        Point::VendorControl => {
            let value = buffer.read_u32()?;
            adapter.set_vendor_control(value);
            Ok(())
        }
        Point::ControlValue => {
            let value = buffer.read_i32()?;
            adapter.set_control_value(value);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// Status (Stat)
    ///
    /// Module Status Code
    fn status(&self) -> Stat;

    /// Vendor Status (StatVend)
    ///
    /// Module Vendor Status Code
    fn vendor_status(&self) -> Option<u16> {
        None
    }

    /// Events (Evt)
    ///
    /// Module Event Flags
    fn events(&self) -> u32;

    /// Vendor Module Event Flags (EvtVend)
    ///
    /// Vendor specific flags
    fn vendor_module_event_flags(&self) -> Option<u32> {
        None
    }

    /// Control (Ctl)
    ///
    /// Module Control
    fn control(&self) -> Option<u16> {
        None
    }

    /// Vendor Control (CtlVend)
    ///
    /// Vendor Module Control
    fn vendor_control(&self) -> Option<u32> {
        None
    }

    /// Control Value (CtlVal)
    ///
    /// Module Control Value
    fn control_value(&self) -> Option<i32> {
        None
    }

    /// Timestamp (Tms)
    ///
    /// Time in seconds since 2000 epoch
    fn timestamp(&self) -> Option<u32> {
        None
    }

    /// Output Current (OutA)
    ///
    /// Output Current
    fn output_current(&self) -> Option<f32> {
        None
    }

    /// Output Voltage (OutV)
    ///
    /// Output Voltage
    fn output_voltage(&self) -> Option<f32> {
        None
    }

    /// Output Energy (OutWh)
    ///
    /// Output Energy
    fn output_energy(&self) -> Option<f32> {
        None
    }

    /// Output Power (OutW)
    ///
    /// Output Power
    fn output_power(&self) -> Option<f32> {
        None
    }

    /// Temp (Tmp)
    ///
    /// Module Temperature
    fn temp(&self) -> Option<f32> {
        None
    }

    /// Input Current (InA)
    ///
    /// Input Current
    fn input_current(&self) -> Option<f32> {
        None
    }

    /// Input Voltage (InV)
    ///
    /// Input Voltage
    fn input_voltage(&self) -> Option<f32> {
        None
    }

    /// Input Energy (InWh)
    ///
    /// Input Energy
    fn input_energy(&self) -> Option<f32> {
        None
    }

    /// Input Power (InW)
    ///
    /// Input Power
    fn input_power(&self) -> Option<f32> {
        None
    }
}

pub trait WriteAdapter {
    /// Control (Ctl)
    ///
    /// Module Control
    fn set_control(&mut self, value: u16) {}

    /// Vendor Control (CtlVend)
    ///
    /// Vendor Module Control
    fn set_vendor_control(&mut self, value: u32) {}

    /// Control Value (CtlVal)
    ///
    /// Module Control Value
    fn set_control_value(&mut self, value: i32) {}
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model501Stat {
    Off = 1,
    Sleeping = 2,
    Starting = 3,
    Mppt = 4,
    Throttled = 5,
    ShuttingDown = 6,
    Fault = 7,
    Standby = 8,
    Test = 9,
    Other = 10,
}

impl Model501Stat {
    pub fn from_repr(repr: u16) -> Option<Model501Stat> {
        match repr {
            1 => Some(Model501Stat::Off),
            2 => Some(Model501Stat::Sleeping),
            3 => Some(Model501Stat::Starting),
            4 => Some(Model501Stat::Mppt),
            5 => Some(Model501Stat::Throttled),
            6 => Some(Model501Stat::ShuttingDown),
            7 => Some(Model501Stat::Fault),
            8 => Some(Model501Stat::Standby),
            9 => Some(Model501Stat::Test),
            10 => Some(Model501Stat::Other),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model501Stat`] - only `Model501Stat` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Stat` distinct from another model's point of the same name.
pub type Stat = Model501Stat;
