// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::cursor::Cursor;
use crate::model::{ModelSpec, StaticModelSpec};
use core::cmp::min;
use core::ffi::c_void;

static POINTS: [PointDetails<()>; 34] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::Amps,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::ASf,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::Voltage,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::VSf,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::Hz,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::HzSf,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::Watts,
        size: 1,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::WSf,
        size: 1,
        start_address: 9,
    },
    PointDetails {
        point: |()| Point::Va,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::VaSf,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::Var,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::VarSf,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::Pf,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::PfSf,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursExported,
        size: 2,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursImported,
        size: 2,
        start_address: 18,
    },
    PointDetails {
        point: |()| Point::TotWhSf,
        size: 1,
        start_address: 20,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursExported,
        size: 2,
        start_address: 21,
    },
    PointDetails {
        point: |()| Point::TotalVaHoursImported,
        size: 2,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::TotVAhSf,
        size: 1,
        start_address: 25,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursImportedQ1,
        size: 2,
        start_address: 26,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursImportedQ2,
        size: 2,
        start_address: 28,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ3,
        size: 2,
        start_address: 30,
    },
    PointDetails {
        point: |()| Point::TotalVArHoursExportedQ4,
        size: 2,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::TotVArhSf,
        size: 1,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::Events,
        size: 2,
        start_address: 35,
    },
    PointDetails {
        point: |()| Point::Rsrvd,
        size: 1,
        start_address: 37,
    },
    PointDetails {
        point: |()| Point::Timestamp,
        size: 2,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::Milliseconds,
        size: 1,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::Sequence,
        size: 1,
        start_address: 41,
    },
    PointDetails {
        point: |()| Point::Algorithm,
        size: 1,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::N,
        size: 1,
        start_address: 43,
    },
];

static REPEATING_POINTS: [PointDetails<()>; 1] = [PointDetails {
    point: |()| Point::RepeatingDs,
    size: 1,
    start_address: 0,
}];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    Amps,
    ASf,
    Voltage,
    VSf,
    Hz,
    HzSf,
    Watts,
    WSf,
    Va,
    VaSf,
    Var,
    VarSf,
    Pf,
    PfSf,
    TotalWattHoursExported,
    TotalWattHoursImported,
    TotWhSf,
    TotalVaHoursExported,
    TotalVaHoursImported,
    TotVAhSf,
    TotalVarHoursImportedQ1,
    TotalVArHoursImportedQ2,
    TotalVArHoursExportedQ3,
    TotalVArHoursExportedQ4,
    TotVArhSf,
    Events,
    Rsrvd,
    Timestamp,
    Milliseconds,
    Sequence,
    Algorithm,
    N,
    RepeatingDs,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 220. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model220;

impl<'ad> ModelSpec<'ad> for Model220 {
    const MODEL_ID: u16 = 220;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        45
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (44 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain(
                REPEATING_POINTS
                    .iter()
                    .map(move |p| (44 + p.start_address, p.size, (p.point)(()))),
            )
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model220,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(220);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::Amps => {
            buffer.write_i16(adapter.amps());
        }
        Point::ASf => {
            buffer.write_i16(adapter.a_sf());
        }
        Point::Voltage => {
            if let Some(value) = adapter.voltage() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VSf => {
            buffer.write_i16(adapter.v_sf());
        }
        Point::Hz => {
            buffer.write_i16(adapter.hz());
        }
        Point::HzSf => {
            if let Some(value) = adapter.hz_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Watts => {
            buffer.write_i16(adapter.watts());
        }
        Point::WSf => {
            buffer.write_i16(adapter.w_sf());
        }
        Point::Va => {
            if let Some(value) = adapter.va() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VaSf => {
            if let Some(value) = adapter.va_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Var => {
            if let Some(value) = adapter.var() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VarSf => {
            if let Some(value) = adapter.var_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Pf => {
            if let Some(value) = adapter.pf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PfSf => {
            if let Some(value) = adapter.pf_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursExported => {
            buffer.write_u32(adapter.total_watt_hours_exported(), offset);
        }
        Point::TotalWattHoursImported => {
            buffer.write_u32(adapter.total_watt_hours_imported(), offset);
        }
        Point::TotWhSf => {
            buffer.write_i16(adapter.tot_wh_sf());
        }
        Point::TotalVaHoursExported => {
            if let Some(value) = adapter.total_va_hours_exported() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVaHoursImported => {
            if let Some(value) = adapter.total_va_hours_imported() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotVAhSf => {
            if let Some(value) = adapter.tot_v_ah_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursImportedQ1 => {
            if let Some(value) = adapter.total_var_hours_imported_q1() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursImportedQ2 => {
            if let Some(value) = adapter.total_v_ar_hours_imported_q2() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ3 => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q3() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVArHoursExportedQ4 => {
            if let Some(value) = adapter.total_v_ar_hours_exported_q4() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotVArhSf => {
            if let Some(value) = adapter.tot_v_arh_sf() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Events => {
            buffer.write_u32(adapter.events(), offset);
        }
        Point::Rsrvd => {
            buffer.write_u16(0);
        }
        Point::Timestamp => {
            buffer.write_u32(adapter.timestamp(), offset);
        }
        Point::Milliseconds => {
            buffer.write_u16(adapter.milliseconds());
        }
        Point::Sequence => {
            buffer.write_u16(adapter.sequence());
        }
        Point::Algorithm => {
            buffer.write_u16(adapter.algorithm() as u16);
        }
        Point::N => {
            buffer.write_u16(adapter.n());
        }
        Point::RepeatingDs => {
            buffer.write_u16(adapter.repeating_ds());
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model220,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// Amps (A)
    ///
    /// Total AC Current
    fn amps(&self) -> i16;

    /// A_SF
    ///
    /// Current scale factor
    fn a_sf(&self) -> i16;

    /// Voltage (PhV)
    ///
    /// Average phase or line voltage
    fn voltage(&self) -> Option<i16> {
        None
    }

    /// V_SF
    ///
    /// Voltage scale factor
    fn v_sf(&self) -> i16;

    /// Hz (Hz)
    ///
    /// Frequency
    fn hz(&self) -> i16;

    /// Hz_SF
    ///
    /// Frequency scale factor
    fn hz_sf(&self) -> Option<i16> {
        None
    }

    /// Watts (W)
    ///
    /// Total Real Power
    fn watts(&self) -> i16;

    /// W_SF
    ///
    /// Real Power scale factor
    fn w_sf(&self) -> i16;

    /// VA (VA)
    ///
    /// AC Apparent Power
    fn va(&self) -> Option<i16> {
        None
    }

    /// VA_SF
    ///
    /// Apparent Power scale factor
    fn va_sf(&self) -> Option<i16> {
        None
    }

    /// VAR (VAR)
    ///
    /// Reactive Power
    fn var(&self) -> Option<i16> {
        None
    }

    /// VAR_SF
    ///
    /// Reactive Power scale factor
    fn var_sf(&self) -> Option<i16> {
        None
    }

    /// PF (PF)
    ///
    /// Power Factor
    fn pf(&self) -> Option<i16> {
        None
    }

    /// PF_SF
    ///
    /// Power Factor scale factor
    fn pf_sf(&self) -> Option<i16> {
        None
    }

    /// Total Watt-hours Exported (TotWhExp)
    ///
    /// Total Real Energy Exported
    fn total_watt_hours_exported(&self) -> u32;

    /// Total Watt-hours Imported (TotWhImp)
    ///
    /// Total Real Energy Imported
    fn total_watt_hours_imported(&self) -> u32;

    /// TotWh_SF
    ///
    /// Real Energy scale factor
    fn tot_wh_sf(&self) -> i16;

    /// Total VA-hours Exported (TotVAhExp)
    ///
    /// Total Apparent Energy Exported
    fn total_va_hours_exported(&self) -> Option<u32> {
        None
    }

    /// Total VA-hours Imported (TotVAhImp)
    ///
    /// Total Apparent Energy Imported
    fn total_va_hours_imported(&self) -> Option<u32> {
        None
    }

    /// TotVAh_SF
    ///
    /// Apparent Energy scale factor
    fn tot_v_ah_sf(&self) -> Option<i16> {
        None
    }

    /// Total VAR-hours Imported Q1 (TotVArhImpQ1)
    ///
    /// Total Reactive Energy Imported Quadrant 1
    fn total_var_hours_imported_q1(&self) -> Option<u32> {
        None
    }

    /// Total VAr-hours Imported Q2 (TotVArhImpQ2)
    ///
    /// Total Reactive Power Imported Quadrant 2
    fn total_v_ar_hours_imported_q2(&self) -> Option<u32> {
        None
    }

    /// Total VAr-hours Exported Q3 (TotVArhExpQ3)
    ///
    /// Total Reactive Power Exported Quadrant 3
    fn total_v_ar_hours_exported_q3(&self) -> Option<u32> {
        None
    }

    /// Total VAr-hours Exported Q4 (TotVArhExpQ4)
    ///
    /// Total Reactive Power Exported Quadrant 4
    fn total_v_ar_hours_exported_q4(&self) -> Option<u32> {
        None
    }

    /// TotVArh_SF
    ///
    /// Reactive Energy scale factor
    fn tot_v_arh_sf(&self) -> Option<i16> {
        None
    }

    /// Events (Evt)
    ///
    /// Meter Event Flags
    fn events(&self) -> u32;

    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    fn timestamp(&self) -> u32;

    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    fn milliseconds(&self) -> u16;

    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    fn sequence(&self) -> u16;

    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    fn algorithm(&self) -> Alg;

    /// N (N)
    ///
    /// Number of registers comprising the digital signature.
    ///
    /// The value of N must be at least 4 (64 bits)
    fn n(&self) -> u16;

    /// DS
    fn repeating_ds(&self) -> u16;
}

pub trait WriteAdapter {}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model220Alg {
    /// For test purposes only
    None = 0,
    AesGmac64 = 1,
    Ecc256 = 2,
}

impl Model220Alg {
    pub fn from_repr(repr: u16) -> Option<Model220Alg> {
        match repr {
            0 => Some(Model220Alg::None),
            1 => Some(Model220Alg::AesGmac64),
            2 => Some(Model220Alg::Ecc256),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model220Alg`] - only `Model220Alg` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Alg` distinct from another model's point of the same name.
pub type Alg = Model220Alg;

#[repr(C)]
pub struct Model220CallbackAdapter {
    context: *mut c_void,
    /// Amps (A)
    ///
    /// Total AC Current
    amps_callback: extern "C" fn(*const c_void) -> i16,
    /// A_SF
    ///
    /// Current scale factor
    a_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// Voltage (PhV)
    ///
    /// Average phase or line voltage
    voltage_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// V_SF
    ///
    /// Voltage scale factor
    v_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// Hz (Hz)
    ///
    /// Frequency
    hz_callback: extern "C" fn(*const c_void) -> i16,
    /// Hz_SF
    ///
    /// Frequency scale factor
    hz_sf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Watts (W)
    ///
    /// Total Real Power
    watts_callback: extern "C" fn(*const c_void) -> i16,
    /// W_SF
    ///
    /// Real Power scale factor
    w_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// VA (VA)
    ///
    /// AC Apparent Power
    va_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// VA_SF
    ///
    /// Apparent Power scale factor
    va_sf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// VAR (VAR)
    ///
    /// Reactive Power
    var_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// VAR_SF
    ///
    /// Reactive Power scale factor
    var_sf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// PF (PF)
    ///
    /// Power Factor
    pf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// PF_SF
    ///
    /// Power Factor scale factor
    pf_sf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Total Watt-hours Exported (TotWhExp)
    ///
    /// Total Real Energy Exported
    total_watt_hours_exported_callback: extern "C" fn(*const c_void) -> u32,
    /// Total Watt-hours Imported (TotWhImp)
    ///
    /// Total Real Energy Imported
    total_watt_hours_imported_callback: extern "C" fn(*const c_void) -> u32,
    /// TotWh_SF
    ///
    /// Real Energy scale factor
    tot_wh_sf_callback: extern "C" fn(*const c_void) -> i16,
    /// Total VA-hours Exported (TotVAhExp)
    ///
    /// Total Apparent Energy Exported
    total_va_hours_exported_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Total VA-hours Imported (TotVAhImp)
    ///
    /// Total Apparent Energy Imported
    total_va_hours_imported_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// TotVAh_SF
    ///
    /// Apparent Energy scale factor
    tot_v_ah_sf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Total VAR-hours Imported Q1 (TotVArhImpQ1)
    ///
    /// Total Reactive Energy Imported Quadrant 1
    total_var_hours_imported_q1_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Total VAr-hours Imported Q2 (TotVArhImpQ2)
    ///
    /// Total Reactive Power Imported Quadrant 2
    total_v_ar_hours_imported_q2_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Total VAr-hours Exported Q3 (TotVArhExpQ3)
    ///
    /// Total Reactive Power Exported Quadrant 3
    total_v_ar_hours_exported_q3_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Total VAr-hours Exported Q4 (TotVArhExpQ4)
    ///
    /// Total Reactive Power Exported Quadrant 4
    total_v_ar_hours_exported_q4_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// TotVArh_SF
    ///
    /// Reactive Energy scale factor
    tot_v_arh_sf_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Events (Evt)
    ///
    /// Meter Event Flags
    events_callback: extern "C" fn(*const c_void) -> u32,
    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    timestamp_callback: extern "C" fn(*const c_void) -> u32,
    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    milliseconds_callback: extern "C" fn(*const c_void) -> u16,
    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    sequence_callback: extern "C" fn(*const c_void) -> u16,
    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    algorithm_callback: extern "C" fn(*const c_void) -> Model220Alg,
    /// N (N)
    ///
    /// Number of registers comprising the digital signature.
    ///
    /// The value of N must be at least 4 (64 bits)
    n_callback: extern "C" fn(*const c_void) -> u16,
    /// DS
    repeating_ds_callback: extern "C" fn(*const c_void) -> u16,
}

impl ReadAdapter for Model220CallbackAdapter {
    fn amps(&self) -> i16 {
        (self.amps_callback)(self.context)
    }

    fn a_sf(&self) -> i16 {
        (self.a_sf_callback)(self.context)
    }

    fn voltage(&self) -> Option<i16> {
        self.voltage_callback
            .map(|callback| (callback)(self.context))
    }

    fn v_sf(&self) -> i16 {
        (self.v_sf_callback)(self.context)
    }

    fn hz(&self) -> i16 {
        (self.hz_callback)(self.context)
    }

    fn hz_sf(&self) -> Option<i16> {
        self.hz_sf_callback.map(|callback| (callback)(self.context))
    }

    fn watts(&self) -> i16 {
        (self.watts_callback)(self.context)
    }

    fn w_sf(&self) -> i16 {
        (self.w_sf_callback)(self.context)
    }

    fn va(&self) -> Option<i16> {
        self.va_callback.map(|callback| (callback)(self.context))
    }

    fn va_sf(&self) -> Option<i16> {
        self.va_sf_callback.map(|callback| (callback)(self.context))
    }

    fn var(&self) -> Option<i16> {
        self.var_callback.map(|callback| (callback)(self.context))
    }

    fn var_sf(&self) -> Option<i16> {
        self.var_sf_callback
            .map(|callback| (callback)(self.context))
    }

    fn pf(&self) -> Option<i16> {
        self.pf_callback.map(|callback| (callback)(self.context))
    }

    fn pf_sf(&self) -> Option<i16> {
        self.pf_sf_callback.map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_exported(&self) -> u32 {
        (self.total_watt_hours_exported_callback)(self.context)
    }

    fn total_watt_hours_imported(&self) -> u32 {
        (self.total_watt_hours_imported_callback)(self.context)
    }

    fn tot_wh_sf(&self) -> i16 {
        (self.tot_wh_sf_callback)(self.context)
    }

    fn total_va_hours_exported(&self) -> Option<u32> {
        self.total_va_hours_exported_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_va_hours_imported(&self) -> Option<u32> {
        self.total_va_hours_imported_callback
            .map(|callback| (callback)(self.context))
    }

    fn tot_v_ah_sf(&self) -> Option<i16> {
        self.tot_v_ah_sf_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_imported_q1(&self) -> Option<u32> {
        self.total_var_hours_imported_q1_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_v_ar_hours_imported_q2(&self) -> Option<u32> {
        self.total_v_ar_hours_imported_q2_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_v_ar_hours_exported_q3(&self) -> Option<u32> {
        self.total_v_ar_hours_exported_q3_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_v_ar_hours_exported_q4(&self) -> Option<u32> {
        self.total_v_ar_hours_exported_q4_callback
            .map(|callback| (callback)(self.context))
    }

    fn tot_v_arh_sf(&self) -> Option<i16> {
        self.tot_v_arh_sf_callback
            .map(|callback| (callback)(self.context))
    }

    fn events(&self) -> u32 {
        (self.events_callback)(self.context)
    }

    fn timestamp(&self) -> u32 {
        (self.timestamp_callback)(self.context)
    }

    fn milliseconds(&self) -> u16 {
        (self.milliseconds_callback)(self.context)
    }

    fn sequence(&self) -> u16 {
        (self.sequence_callback)(self.context)
    }

    fn algorithm(&self) -> Alg {
        (self.algorithm_callback)(self.context)
    }

    fn n(&self) -> u16 {
        (self.n_callback)(self.context)
    }

    fn repeating_ds(&self) -> u16 {
        (self.repeating_ds_callback)(self.context)
    }
}

#[repr(C)]
pub struct Model220StatefulAdapter {
    /// Amps (A)
    ///
    /// Total AC Current
    pub amps: i16,
    /// A_SF
    ///
    /// Current scale factor
    pub a_sf: i16,
    /// Voltage (PhV)
    ///
    /// Average phase or line voltage
    pub voltage: i16,
    /// V_SF
    ///
    /// Voltage scale factor
    pub v_sf: i16,
    /// Hz (Hz)
    ///
    /// Frequency
    pub hz: i16,
    /// Hz_SF
    ///
    /// Frequency scale factor
    pub hz_sf: i16,
    /// Watts (W)
    ///
    /// Total Real Power
    pub watts: i16,
    /// W_SF
    ///
    /// Real Power scale factor
    pub w_sf: i16,
    /// VA (VA)
    ///
    /// AC Apparent Power
    pub va: i16,
    /// VA_SF
    ///
    /// Apparent Power scale factor
    pub va_sf: i16,
    /// VAR (VAR)
    ///
    /// Reactive Power
    pub var: i16,
    /// VAR_SF
    ///
    /// Reactive Power scale factor
    pub var_sf: i16,
    /// PF (PF)
    ///
    /// Power Factor
    pub pf: i16,
    /// PF_SF
    ///
    /// Power Factor scale factor
    pub pf_sf: i16,
    /// Total Watt-hours Exported (TotWhExp)
    ///
    /// Total Real Energy Exported
    pub total_watt_hours_exported: u32,
    /// Total Watt-hours Imported (TotWhImp)
    ///
    /// Total Real Energy Imported
    pub total_watt_hours_imported: u32,
    /// TotWh_SF
    ///
    /// Real Energy scale factor
    pub tot_wh_sf: i16,
    /// Total VA-hours Exported (TotVAhExp)
    ///
    /// Total Apparent Energy Exported
    pub total_va_hours_exported: u32,
    /// Total VA-hours Imported (TotVAhImp)
    ///
    /// Total Apparent Energy Imported
    pub total_va_hours_imported: u32,
    /// TotVAh_SF
    ///
    /// Apparent Energy scale factor
    pub tot_v_ah_sf: i16,
    /// Total VAR-hours Imported Q1 (TotVArhImpQ1)
    ///
    /// Total Reactive Energy Imported Quadrant 1
    pub total_var_hours_imported_q1: u32,
    /// Total VAr-hours Imported Q2 (TotVArhImpQ2)
    ///
    /// Total Reactive Power Imported Quadrant 2
    pub total_v_ar_hours_imported_q2: u32,
    /// Total VAr-hours Exported Q3 (TotVArhExpQ3)
    ///
    /// Total Reactive Power Exported Quadrant 3
    pub total_v_ar_hours_exported_q3: u32,
    /// Total VAr-hours Exported Q4 (TotVArhExpQ4)
    ///
    /// Total Reactive Power Exported Quadrant 4
    pub total_v_ar_hours_exported_q4: u32,
    /// TotVArh_SF
    ///
    /// Reactive Energy scale factor
    pub tot_v_arh_sf: i16,
    /// Events (Evt)
    ///
    /// Meter Event Flags
    pub events: u32,
    /// Timestamp (Ts)
    ///
    /// Timestamp value is the number of seconds since January 1, 2000
    pub timestamp: u32,
    /// Milliseconds (Ms)
    ///
    /// Millisecond counter 0-999
    pub milliseconds: u16,
    /// Sequence (Seq)
    ///
    /// Sequence number of request
    ///
    /// Shall be advanced for each request
    pub sequence: u16,
    /// Algorithm (Alg)
    ///
    /// Algorithm used to compute the digital signature
    ///
    /// For future proof
    pub algorithm: Model220Alg,
    /// N (N)
    ///
    /// Number of registers comprising the digital signature.
    ///
    /// The value of N must be at least 4 (64 bits)
    pub n: u16,
    /// DS
    pub repeating_ds: u16,
}

impl ReadAdapter for Model220StatefulAdapter {
    fn amps(&self) -> i16 {
        self.amps
    }

    fn a_sf(&self) -> i16 {
        self.a_sf
    }

    fn voltage(&self) -> Option<i16> {
        Some(self.voltage)
    }

    fn v_sf(&self) -> i16 {
        self.v_sf
    }

    fn hz(&self) -> i16 {
        self.hz
    }

    fn hz_sf(&self) -> Option<i16> {
        Some(self.hz_sf)
    }

    fn watts(&self) -> i16 {
        self.watts
    }

    fn w_sf(&self) -> i16 {
        self.w_sf
    }

    fn va(&self) -> Option<i16> {
        Some(self.va)
    }

    fn va_sf(&self) -> Option<i16> {
        Some(self.va_sf)
    }

    fn var(&self) -> Option<i16> {
        Some(self.var)
    }

    fn var_sf(&self) -> Option<i16> {
        Some(self.var_sf)
    }

    fn pf(&self) -> Option<i16> {
        Some(self.pf)
    }

    fn pf_sf(&self) -> Option<i16> {
        Some(self.pf_sf)
    }

    fn total_watt_hours_exported(&self) -> u32 {
        self.total_watt_hours_exported
    }

    fn total_watt_hours_imported(&self) -> u32 {
        self.total_watt_hours_imported
    }

    fn tot_wh_sf(&self) -> i16 {
        self.tot_wh_sf
    }

    fn total_va_hours_exported(&self) -> Option<u32> {
        Some(self.total_va_hours_exported)
    }

    fn total_va_hours_imported(&self) -> Option<u32> {
        Some(self.total_va_hours_imported)
    }

    fn tot_v_ah_sf(&self) -> Option<i16> {
        Some(self.tot_v_ah_sf)
    }

    fn total_var_hours_imported_q1(&self) -> Option<u32> {
        Some(self.total_var_hours_imported_q1)
    }

    fn total_v_ar_hours_imported_q2(&self) -> Option<u32> {
        Some(self.total_v_ar_hours_imported_q2)
    }

    fn total_v_ar_hours_exported_q3(&self) -> Option<u32> {
        Some(self.total_v_ar_hours_exported_q3)
    }

    fn total_v_ar_hours_exported_q4(&self) -> Option<u32> {
        Some(self.total_v_ar_hours_exported_q4)
    }

    fn tot_v_arh_sf(&self) -> Option<i16> {
        Some(self.tot_v_arh_sf)
    }

    fn events(&self) -> u32 {
        self.events
    }

    fn timestamp(&self) -> u32 {
        self.timestamp
    }

    fn milliseconds(&self) -> u16 {
        self.milliseconds
    }

    fn sequence(&self) -> u16 {
        self.sequence
    }

    fn algorithm(&self) -> Alg {
        self.algorithm
    }

    fn n(&self) -> u16 {
        self.n
    }

    fn repeating_ds(&self) -> u16 {
        self.repeating_ds
    }
}

/// C-FFI dispatch descriptor for SunSpec model 220. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_220: StaticModelSpec = StaticModelSpec {
    id: 220,
    length: model_220_c_length,
    writable: false,
    visit_read: model_220_c_visit_read,
    visit_write: model_220_c_visit_write,
};

fn model_220_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model220).model_length()
}

/// # Safety
/// For `kind` 1 or 2, `adapter` must point to a live `Model220{Stateful,Callback}Adapter`,
/// valid for the duration of the call.
unsafe fn model_220_c_visit_read(
    kind: u8,
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model220;
    let adapter: Option<&dyn ReadAdapter> = match kind {
        1 => Some(unsafe { &*(adapter as *const Model220StatefulAdapter) } as &dyn ReadAdapter),
        2 => Some(unsafe { &*(adapter as *const Model220CallbackAdapter) } as &dyn ReadAdapter),
        _ => None,
    };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_220_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_220_c_visit_write(
    kind: u8,
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let _ = (kind, adapter, buffer);
    let model = Model220;
    cursor.visit_source_block(model.model_length(), |_, _, _| {
        Err(ModbusException::IllegalDataAddress)
    });
}
