// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::model::ModelSpec;
use core::cmp::min;

static POINTS: [PointDetails<()>; 9] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::DerTripLvModuleEnable,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::AdoptCurveRequest,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::AdoptCurveResult,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::NumberOfPoints,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::StoredCurveCount,
        size: 1,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::VoltageScaleFactor,
        size: 1,
        start_address: 7,
    },
    PointDetails {
        point: |()| Point::TimePointScaleFactor,
        size: 1,
        start_address: 8,
    },
];

static CRV_POINTS: [PointDetails<u16>; 1] = [PointDetails {
    point: |crv_index| Point::CrvCurveAccess { crv_index },
    size: 1,
    start_address: 0,
}];

static MUST_TRIP_POINTS: [PointDetails<u16>; 1] = [PointDetails {
    point: |crv_index| Point::MustTripCurveCrvNumberOfActivePoints { crv_index },
    size: 1,
    start_address: 0,
}];

static MUST_TRIP_PT_POINTS: [PointDetails<(u16, u16)>; 2] = [
    PointDetails {
        point: |(crv_index, pt_index)| Point::MustTripCurvePtVoltagePoint {
            crv_index,
            pt_index,
        },
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |(crv_index, pt_index)| Point::MustTripCurvePtTimePoint {
            crv_index,
            pt_index,
        },
        size: 2,
        start_address: 1,
    },
];

static MAY_TRIP_POINTS: [PointDetails<u16>; 1] = [PointDetails {
    point: |crv_index| Point::MayTripCurveCrvNumberOfActivePoints { crv_index },
    size: 1,
    start_address: 0,
}];

static MAY_TRIP_PT_POINTS: [PointDetails<(u16, u16)>; 2] = [
    PointDetails {
        point: |(crv_index, pt_index)| Point::MayTripCurvePtVoltagePoint {
            crv_index,
            pt_index,
        },
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |(crv_index, pt_index)| Point::MayTripCurvePtTimePoint {
            crv_index,
            pt_index,
        },
        size: 2,
        start_address: 1,
    },
];

static MOM_CESS_POINTS: [PointDetails<u16>; 1] = [PointDetails {
    point: |crv_index| Point::MomentaryCessationCurveCrvNumberOfActivePoints { crv_index },
    size: 1,
    start_address: 0,
}];

static MOM_CESS_PT_POINTS: [PointDetails<(u16, u16)>; 2] = [
    PointDetails {
        point: |(crv_index, pt_index)| Point::MomentaryCessationCurvePtVoltagePoint {
            crv_index,
            pt_index,
        },
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |(crv_index, pt_index)| Point::MomentaryCessationCurvePtTimePoint {
            crv_index,
            pt_index,
        },
        size: 2,
        start_address: 1,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    DerTripLvModuleEnable,
    AdoptCurveRequest,
    AdoptCurveResult,
    NumberOfPoints,
    StoredCurveCount,
    VoltageScaleFactor,
    TimePointScaleFactor,
    CrvCurveAccess { crv_index: u16 },
    MustTripCurveCrvNumberOfActivePoints { crv_index: u16 },
    MayTripCurveCrvNumberOfActivePoints { crv_index: u16 },
    MomentaryCessationCurveCrvNumberOfActivePoints { crv_index: u16 },
    MustTripCurvePtVoltagePoint { crv_index: u16, pt_index: u16 },
    MustTripCurvePtTimePoint { crv_index: u16, pt_index: u16 },
    MayTripCurvePtVoltagePoint { crv_index: u16, pt_index: u16 },
    MayTripCurvePtTimePoint { crv_index: u16, pt_index: u16 },
    MomentaryCessationCurvePtVoltagePoint { crv_index: u16, pt_index: u16 },
    MomentaryCessationCurvePtTimePoint { crv_index: u16, pt_index: u16 },
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 707. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model707 {
    /// Number of repeating blocks in this model instance.
    pub stored_curve_count: u16,
    /// Number of repeating blocks in this model instance.
    pub number_of_points: u16,
}

impl<'ad> ModelSpec<'ad> for Model707 {
    const MODEL_ID: u16 = 707;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        9 + self.stored_curve_count
            * (4 + self.number_of_points * (3)
                + self.number_of_points * (3)
                + self.number_of_points * (3))
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let must_trip_pt_count = self.number_of_points;
        let must_trip_pt_size = 3;

        let may_trip_pt_count = self.number_of_points;
        let may_trip_pt_size = 3;

        let mom_cess_pt_count = self.number_of_points;
        let mom_cess_pt_size = 3;

        let crv_count = self.stored_curve_count;
        let crv_size = 4
            + must_trip_pt_count * must_trip_pt_size
            + may_trip_pt_count * may_trip_pt_size
            + mom_cess_pt_count * mom_cess_pt_size;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain((0..crv_count).flat_map(move |crv_index| {
                let crv_address = 9 + crv_index * crv_size;
                CRV_POINTS
                    .iter()
                    .map(move |p| (crv_address + p.start_address, p.size, (p.point)(crv_index)))
                    .chain(MUST_TRIP_POINTS.iter().map(move |p| {
                        (
                            crv_address + 1 + p.start_address,
                            p.size,
                            (p.point)(crv_index),
                        )
                    }))
                    .chain((0..must_trip_pt_count).flat_map(move |pt_index| {
                        let must_trip_pt_address =
                            crv_address + 1 + 1 + pt_index * must_trip_pt_size;
                        MUST_TRIP_PT_POINTS.iter().map(move |p| {
                            (
                                must_trip_pt_address + p.start_address,
                                p.size,
                                (p.point)((crv_index, pt_index)),
                            )
                        })
                    }))
                    .chain(MAY_TRIP_POINTS.iter().map(move |p| {
                        (
                            crv_address
                                + 1
                                + 1
                                + must_trip_pt_count * must_trip_pt_size
                                + p.start_address,
                            p.size,
                            (p.point)(crv_index),
                        )
                    }))
                    .chain((0..may_trip_pt_count).flat_map(move |pt_index| {
                        let may_trip_pt_address = crv_address
                            + 1
                            + 1
                            + must_trip_pt_count * must_trip_pt_size
                            + 1
                            + pt_index * may_trip_pt_size;
                        MAY_TRIP_PT_POINTS.iter().map(move |p| {
                            (
                                may_trip_pt_address + p.start_address,
                                p.size,
                                (p.point)((crv_index, pt_index)),
                            )
                        })
                    }))
                    .chain(MOM_CESS_POINTS.iter().map(move |p| {
                        (
                            crv_address
                                + 1
                                + 1
                                + must_trip_pt_count * must_trip_pt_size
                                + 1
                                + may_trip_pt_count * may_trip_pt_size
                                + p.start_address,
                            p.size,
                            (p.point)(crv_index),
                        )
                    }))
                    .chain((0..mom_cess_pt_count).flat_map(move |pt_index| {
                        let mom_cess_pt_address = crv_address
                            + 1
                            + 1
                            + must_trip_pt_count * must_trip_pt_size
                            + 1
                            + may_trip_pt_count * may_trip_pt_size
                            + 1
                            + pt_index * mom_cess_pt_size;
                        MOM_CESS_PT_POINTS.iter().map(move |p| {
                            (
                                mom_cess_pt_address + p.start_address,
                                p.size,
                                (p.point)((crv_index, pt_index)),
                            )
                        })
                    }))
            }))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let must_trip_pt_count = self.number_of_points;
        let must_trip_pt_size = 3;

        let may_trip_pt_count = self.number_of_points;
        let may_trip_pt_size = 3;

        let mom_cess_pt_count = self.number_of_points;
        let mom_cess_pt_size = 3;

        let crv_count = self.stored_curve_count;
        let crv_size = 4
            + must_trip_pt_count * must_trip_pt_size
            + may_trip_pt_count * may_trip_pt_size
            + mom_cess_pt_count * mom_cess_pt_size;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .chain((0..crv_count).flat_map(move |crv_index| {
                let crv_address = 9 + crv_index * crv_size;
                CRV_POINTS
                    .iter()
                    .map(move |p| (crv_address + p.start_address, p.size, (p.point)(crv_index)))
                    .chain(MUST_TRIP_POINTS.iter().map(move |p| {
                        (
                            crv_address + 1 + p.start_address,
                            p.size,
                            (p.point)(crv_index),
                        )
                    }))
                    .chain((0..must_trip_pt_count).flat_map(move |pt_index| {
                        let must_trip_pt_address =
                            crv_address + 1 + 1 + pt_index * must_trip_pt_size;
                        MUST_TRIP_PT_POINTS.iter().map(move |p| {
                            (
                                must_trip_pt_address + p.start_address,
                                p.size,
                                (p.point)((crv_index, pt_index)),
                            )
                        })
                    }))
                    .chain(MAY_TRIP_POINTS.iter().map(move |p| {
                        (
                            crv_address
                                + 1
                                + 1
                                + must_trip_pt_count * must_trip_pt_size
                                + p.start_address,
                            p.size,
                            (p.point)(crv_index),
                        )
                    }))
                    .chain((0..may_trip_pt_count).flat_map(move |pt_index| {
                        let may_trip_pt_address = crv_address
                            + 1
                            + 1
                            + must_trip_pt_count * must_trip_pt_size
                            + 1
                            + pt_index * may_trip_pt_size;
                        MAY_TRIP_PT_POINTS.iter().map(move |p| {
                            (
                                may_trip_pt_address + p.start_address,
                                p.size,
                                (p.point)((crv_index, pt_index)),
                            )
                        })
                    }))
                    .chain(MOM_CESS_POINTS.iter().map(move |p| {
                        (
                            crv_address
                                + 1
                                + 1
                                + must_trip_pt_count * must_trip_pt_size
                                + 1
                                + may_trip_pt_count * may_trip_pt_size
                                + p.start_address,
                            p.size,
                            (p.point)(crv_index),
                        )
                    }))
                    .chain((0..mom_cess_pt_count).flat_map(move |pt_index| {
                        let mom_cess_pt_address = crv_address
                            + 1
                            + 1
                            + must_trip_pt_count * must_trip_pt_size
                            + 1
                            + may_trip_pt_count * may_trip_pt_size
                            + 1
                            + pt_index * mom_cess_pt_size;
                        MOM_CESS_PT_POINTS.iter().map(move |p| {
                            (
                                mom_cess_pt_address + p.start_address,
                                p.size,
                                (p.point)((crv_index, pt_index)),
                            )
                        })
                    }))
            }))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model707,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(707);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::DerTripLvModuleEnable => {
            buffer.write_u16(adapter.der_trip_lv_module_enable() as u16);
        }
        Point::AdoptCurveRequest => {
            buffer.write_u16(adapter.adopt_curve_request());
        }
        Point::AdoptCurveResult => {
            buffer.write_u16(adapter.adopt_curve_result() as u16);
        }
        Point::NumberOfPoints => {
            buffer.write_u16(adapter.number_of_points());
        }
        Point::StoredCurveCount => {
            buffer.write_u16(adapter.stored_curve_count());
        }
        Point::VoltageScaleFactor => {
            buffer.write_i16(adapter.voltage_scale_factor());
        }
        Point::TimePointScaleFactor => {
            buffer.write_i16(adapter.time_point_scale_factor());
        }
        Point::CrvCurveAccess { crv_index } => {
            buffer.write_u16(adapter.crv_curve_access(*crv_index) as u16);
        }
        Point::MustTripCurveCrvNumberOfActivePoints { crv_index } => {
            if let Some(value) = adapter.must_trip_curve_crv_number_of_active_points(*crv_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MayTripCurveCrvNumberOfActivePoints { crv_index } => {
            if let Some(value) = adapter.may_trip_curve_crv_number_of_active_points(*crv_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MomentaryCessationCurveCrvNumberOfActivePoints { crv_index } => {
            if let Some(value) =
                adapter.momentary_cessation_curve_crv_number_of_active_points(*crv_index)
            {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MustTripCurvePtVoltagePoint {
            crv_index,
            pt_index,
        } => {
            if let Some(value) = adapter.must_trip_curve_pt_voltage_point(*crv_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MustTripCurvePtTimePoint {
            crv_index,
            pt_index,
        } => {
            if let Some(value) = adapter.must_trip_curve_pt_time_point(*crv_index, *pt_index) {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MayTripCurvePtVoltagePoint {
            crv_index,
            pt_index,
        } => {
            if let Some(value) = adapter.may_trip_curve_pt_voltage_point(*crv_index, *pt_index) {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MayTripCurvePtTimePoint {
            crv_index,
            pt_index,
        } => {
            if let Some(value) = adapter.may_trip_curve_pt_time_point(*crv_index, *pt_index) {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::MomentaryCessationCurvePtVoltagePoint {
            crv_index,
            pt_index,
        } => {
            if let Some(value) =
                adapter.momentary_cessation_curve_pt_voltage_point(*crv_index, *pt_index)
            {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::MomentaryCessationCurvePtTimePoint {
            crv_index,
            pt_index,
        } => {
            if let Some(value) =
                adapter.momentary_cessation_curve_pt_time_point(*crv_index, *pt_index)
            {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model707,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    match point {
        Point::DerTripLvModuleEnable => {
            let value = buffer.read_u16()?;
            let enum_value = Ena::from_repr(value).ok_or(ModbusException::IllegalDataValue)?;
            adapter.set_der_trip_lv_module_enable(enum_value);
            Ok(())
        }
        Point::AdoptCurveRequest => {
            let value = buffer.read_u16()?;
            adapter.set_adopt_curve_request(value);
            Ok(())
        }
        Point::MustTripCurveCrvNumberOfActivePoints { crv_index } => {
            let value = buffer.read_u16()?;
            adapter.set_must_trip_curve_crv_number_of_active_points(value, *crv_index);
            Ok(())
        }
        Point::MayTripCurveCrvNumberOfActivePoints { crv_index } => {
            let value = buffer.read_u16()?;
            adapter.set_may_trip_curve_crv_number_of_active_points(value, *crv_index);
            Ok(())
        }
        Point::MomentaryCessationCurveCrvNumberOfActivePoints { crv_index } => {
            let value = buffer.read_u16()?;
            adapter.set_momentary_cessation_curve_crv_number_of_active_points(value, *crv_index);
            Ok(())
        }
        Point::MustTripCurvePtVoltagePoint {
            crv_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_must_trip_curve_pt_voltage_point(value, *crv_index, *pt_index);
            Ok(())
        }
        Point::MustTripCurvePtTimePoint {
            crv_index,
            pt_index,
        } => {
            let value = buffer.read_u32()?;
            adapter.set_must_trip_curve_pt_time_point(value, *crv_index, *pt_index);
            Ok(())
        }
        Point::MayTripCurvePtVoltagePoint {
            crv_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_may_trip_curve_pt_voltage_point(value, *crv_index, *pt_index);
            Ok(())
        }
        Point::MayTripCurvePtTimePoint {
            crv_index,
            pt_index,
        } => {
            let value = buffer.read_u32()?;
            adapter.set_may_trip_curve_pt_time_point(value, *crv_index, *pt_index);
            Ok(())
        }
        Point::MomentaryCessationCurvePtVoltagePoint {
            crv_index,
            pt_index,
        } => {
            let value = buffer.read_u16()?;
            adapter.set_momentary_cessation_curve_pt_voltage_point(value, *crv_index, *pt_index);
            Ok(())
        }
        Point::MomentaryCessationCurvePtTimePoint {
            crv_index,
            pt_index,
        } => {
            let value = buffer.read_u32()?;
            adapter.set_momentary_cessation_curve_pt_time_point(value, *crv_index, *pt_index);
            Ok(())
        }
        _ => Err(ModbusException::IllegalDataAddress),
    }
}

pub trait ReadAdapter {
    /// DER Trip LV Module Enable (Ena)
    ///
    /// DER low voltage trip control enable.
    fn der_trip_lv_module_enable(&self) -> Ena;

    /// Adopt Curve Request (AdptCrvReq)
    ///
    /// Index of curve points to adopt. First curve index is 1.
    fn adopt_curve_request(&self) -> u16;

    /// Adopt Curve Result (AdptCrvRslt)
    ///
    /// Result of last adopt curve operation.
    fn adopt_curve_result(&self) -> AdptCrvRslt;

    /// Number Of Points (NPt)
    ///
    /// Number of curve points supported.
    fn number_of_points(&self) -> u16;

    /// Stored Curve Count (NCrvSet)
    ///
    /// Number of stored curves supported.
    fn stored_curve_count(&self) -> u16;

    /// Voltage Scale Factor (V_SF)
    ///
    /// Scale factor for curve voltage points.
    fn voltage_scale_factor(&self) -> i16;

    /// Time Point Scale Factor (Tms_SF)
    ///
    /// Scale factor for curve time points.
    fn time_point_scale_factor(&self) -> i16;

    /// Curve Access (ReadOnly)
    ///
    /// Curve read-write access.
    fn crv_curve_access(&self, crv_index: u16) -> ReadOnly;

    /// Number Of Active Points (ActPt)
    ///
    /// Number of active points in must trip curve.
    fn must_trip_curve_crv_number_of_active_points(&self, crv_index: u16) -> Option<u16> {
        None
    }

    /// Number Of Active Points (ActPt)
    ///
    /// Number of active points in may trip curve.
    fn may_trip_curve_crv_number_of_active_points(&self, crv_index: u16) -> Option<u16> {
        None
    }

    /// Number Of Active Points (ActPt)
    ///
    /// Number of active points in the momentary cessation curve.
    fn momentary_cessation_curve_crv_number_of_active_points(&self, crv_index: u16) -> Option<u16> {
        None
    }

    /// Voltage Point (V)
    ///
    /// Curve voltage point as percentage.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes.
    fn must_trip_curve_pt_voltage_point(&self, crv_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Time Point (Tms)
    ///
    /// Curve time point in seconds.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes.
    fn must_trip_curve_pt_time_point(&self, crv_index: u16, pt_index: u16) -> Option<u32> {
        None
    }

    /// Voltage Point (V)
    ///
    /// Curve voltage point as percentage.
    fn may_trip_curve_pt_voltage_point(&self, crv_index: u16, pt_index: u16) -> Option<u16> {
        None
    }

    /// Time Point (Tms)
    ///
    /// Curve time point in seconds.
    fn may_trip_curve_pt_time_point(&self, crv_index: u16, pt_index: u16) -> Option<u32> {
        None
    }

    /// Voltage Point (V)
    ///
    /// Curve voltage point as percentage.
    fn momentary_cessation_curve_pt_voltage_point(
        &self,
        crv_index: u16,
        pt_index: u16,
    ) -> Option<u16> {
        None
    }

    /// Time Point (Tms)
    ///
    /// Curve time point in seconds.
    fn momentary_cessation_curve_pt_time_point(
        &self,
        crv_index: u16,
        pt_index: u16,
    ) -> Option<u32> {
        None
    }
}

pub trait WriteAdapter {
    /// DER Trip LV Module Enable (Ena)
    ///
    /// DER low voltage trip control enable.
    fn set_der_trip_lv_module_enable(&mut self, value: Ena);

    /// Adopt Curve Request (AdptCrvReq)
    ///
    /// Index of curve points to adopt. First curve index is 1.
    fn set_adopt_curve_request(&mut self, value: u16);

    /// Number Of Active Points (ActPt)
    ///
    /// Number of active points in must trip curve.
    fn set_must_trip_curve_crv_number_of_active_points(&mut self, value: u16, crv_index: u16) {}

    /// Number Of Active Points (ActPt)
    ///
    /// Number of active points in may trip curve.
    fn set_may_trip_curve_crv_number_of_active_points(&mut self, value: u16, crv_index: u16) {}

    /// Number Of Active Points (ActPt)
    ///
    /// Number of active points in the momentary cessation curve.
    fn set_momentary_cessation_curve_crv_number_of_active_points(
        &mut self,
        value: u16,
        crv_index: u16,
    ) {
    }

    /// Voltage Point (V)
    ///
    /// Curve voltage point as percentage.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes.
    fn set_must_trip_curve_pt_voltage_point(&mut self, value: u16, crv_index: u16, pt_index: u16) {}

    /// Time Point (Tms)
    ///
    /// Curve time point in seconds.
    ///
    /// Internal curve conformance checks should be conducted when AdptCrvReq is set to 1, not on point writes.
    fn set_must_trip_curve_pt_time_point(&mut self, value: u32, crv_index: u16, pt_index: u16) {}

    /// Voltage Point (V)
    ///
    /// Curve voltage point as percentage.
    fn set_may_trip_curve_pt_voltage_point(&mut self, value: u16, crv_index: u16, pt_index: u16) {}

    /// Time Point (Tms)
    ///
    /// Curve time point in seconds.
    fn set_may_trip_curve_pt_time_point(&mut self, value: u32, crv_index: u16, pt_index: u16) {}

    /// Voltage Point (V)
    ///
    /// Curve voltage point as percentage.
    fn set_momentary_cessation_curve_pt_voltage_point(
        &mut self,
        value: u16,
        crv_index: u16,
        pt_index: u16,
    ) {
    }

    /// Time Point (Tms)
    ///
    /// Curve time point in seconds.
    fn set_momentary_cessation_curve_pt_time_point(
        &mut self,
        value: u32,
        crv_index: u16,
        pt_index: u16,
    ) {
    }
}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model707AdptCrvRslt {
    /// Update In Progress
    ///
    /// Curve update in progress.
    InProgress = 0,
    /// Update Complete
    ///
    /// Curve update completed successfully.
    Completed = 1,
    /// Update Failed
    ///
    /// Curve update failed.
    Failed = 2,
}

impl Model707AdptCrvRslt {
    pub fn from_repr(repr: u16) -> Option<Model707AdptCrvRslt> {
        match repr {
            0 => Some(Model707AdptCrvRslt::InProgress),
            1 => Some(Model707AdptCrvRslt::Completed),
            2 => Some(Model707AdptCrvRslt::Failed),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model707AdptCrvRslt`] - only `Model707AdptCrvRslt` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `AdptCrvRslt` distinct from another model's point of the same name.
pub type AdptCrvRslt = Model707AdptCrvRslt;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model707Ena {
    /// Disabled
    ///
    /// Function is disabled.
    Disabled = 0,
    /// Enabled
    ///
    /// Function is enabled.
    Enabled = 1,
}

impl Model707Ena {
    pub fn from_repr(repr: u16) -> Option<Model707Ena> {
        match repr {
            0 => Some(Model707Ena::Disabled),
            1 => Some(Model707Ena::Enabled),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model707Ena`] - only `Model707Ena` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `Ena` distinct from another model's point of the same name.
pub type Ena = Model707Ena;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model707ReadOnly {
    /// Read-Write Access
    ///
    /// Curve has read-write access.
    Rw = 0,
    /// Read-Only Access
    ///
    /// Curve has read-only access.
    R = 1,
}

impl Model707ReadOnly {
    pub fn from_repr(repr: u16) -> Option<Model707ReadOnly> {
        match repr {
            0 => Some(Model707ReadOnly::Rw),
            1 => Some(Model707ReadOnly::R),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model707ReadOnly`] - only `Model707ReadOnly` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `ReadOnly` distinct from another model's point of the same name.
pub type ReadOnly = Model707ReadOnly;
