// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::{ModbusException, ModelSpec};
use core::cmp::min;
use core::ffi::CStr;

static POINTS: [PointDetails<()>; 8] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::Tm,
        size: 6,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::Date,
        size: 4,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::Location,
        size: 20,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::Lat,
        size: 2,
        start_address: 32,
    },
    PointDetails {
        point: |()| Point::Long,
        size: 2,
        start_address: 34,
    },
    PointDetails {
        point: |()| Point::Altitude,
        size: 2,
        start_address: 36,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    Tm,
    Date,
    Location,
    Lat,
    Long,
    Altitude,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 305. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model305;

impl<'ad> ModelSpec<'ad> for Model305 {
    const MODEL_ID: u16 = 305;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        38
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model305,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(305);
        }
        Point::ModelLength => {
            buffer.write_u16(model.model_length() - 2);
        }
        Point::Tm => {
            buffer.write_string(
                adapter.tm().unwrap_or(crate::not_implemented::STRING),
                offset,
            );
        }
        Point::Date => {
            buffer.write_string(
                adapter.date().unwrap_or(crate::not_implemented::STRING),
                offset,
            );
        }
        Point::Location => {
            buffer.write_string(
                adapter.location().unwrap_or(crate::not_implemented::STRING),
                offset,
            );
        }
        Point::Lat => {
            buffer.write_i32(
                adapter.lat().unwrap_or(crate::not_implemented::INT32),
                offset,
            );
        }
        Point::Long => {
            buffer.write_i32(
                adapter.long().unwrap_or(crate::not_implemented::INT32),
                offset,
            );
        }
        Point::Altitude => {
            buffer.write_i32(
                adapter.altitude().unwrap_or(crate::not_implemented::INT32),
                offset,
            );
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model305,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// Tm (Tm)
    ///
    /// UTC 24 hour time stamp to millisecond hhmmss.sssZ format
    fn tm(&self) -> Option<&CStr> {
        None
    }

    /// Date (Date)
    ///
    /// UTC Date string YYYYMMDD format
    fn date(&self) -> Option<&CStr> {
        None
    }

    /// Location (Loc)
    ///
    /// Location string (40 chars max)
    fn location(&self) -> Option<&CStr> {
        None
    }

    /// Lat (Lat)
    ///
    /// Latitude with seven degrees of precision
    fn lat(&self) -> Option<i32> {
        None
    }

    /// Long (Long)
    ///
    /// Longitude with seven degrees of precision
    fn long(&self) -> Option<i32> {
        None
    }

    /// Altitude (Alt)
    ///
    /// Altitude measurement in meters
    fn altitude(&self) -> Option<i32> {
        None
    }
}

pub trait WriteAdapter {}
