// @generated by the sunspec-gen crate (crates/sunspec-gen) from the SunSpec model definitions in
// https://github.com/sunspec/models at tag v2026-04-20.
// Do not edit by hand - run `cargo run -p sunspec-gen` to regenerate.

use crate::ModbusException;
use crate::buffer::{ReadableRegisterBuffer, WritableRegisterBuffer};
use crate::cursor::Cursor;
use crate::model::{ModelSpec, StaticModelSpec};
use core::cmp::min;
use core::ffi::{CStr, c_char, c_void};

static POINTS: [PointDetails<()>; 72] = [
    PointDetails {
        point: |()| Point::ModelId,
        size: 1,
        start_address: 0,
    },
    PointDetails {
        point: |()| Point::ModelLength,
        size: 1,
        start_address: 1,
    },
    PointDetails {
        point: |()| Point::AcWiringType,
        size: 1,
        start_address: 2,
    },
    PointDetails {
        point: |()| Point::OperatingState,
        size: 1,
        start_address: 3,
    },
    PointDetails {
        point: |()| Point::InverterState,
        size: 1,
        start_address: 4,
    },
    PointDetails {
        point: |()| Point::GridConnectionState,
        size: 1,
        start_address: 5,
    },
    PointDetails {
        point: |()| Point::AlarmBitfield,
        size: 2,
        start_address: 6,
    },
    PointDetails {
        point: |()| Point::DerOperationalCharacteristics,
        size: 2,
        start_address: 8,
    },
    PointDetails {
        point: |()| Point::ActivePower,
        size: 1,
        start_address: 10,
    },
    PointDetails {
        point: |()| Point::ApparentPower,
        size: 1,
        start_address: 11,
    },
    PointDetails {
        point: |()| Point::ReactivePower,
        size: 1,
        start_address: 12,
    },
    PointDetails {
        point: |()| Point::PowerFactor,
        size: 1,
        start_address: 13,
    },
    PointDetails {
        point: |()| Point::TotalAcCurrent,
        size: 1,
        start_address: 14,
    },
    PointDetails {
        point: |()| Point::VoltageLl,
        size: 1,
        start_address: 15,
    },
    PointDetails {
        point: |()| Point::VoltageLn,
        size: 1,
        start_address: 16,
    },
    PointDetails {
        point: |()| Point::Frequency,
        size: 2,
        start_address: 17,
    },
    PointDetails {
        point: |()| Point::TotalEnergyInjected,
        size: 4,
        start_address: 19,
    },
    PointDetails {
        point: |()| Point::TotalEnergyAbsorbed,
        size: 4,
        start_address: 23,
    },
    PointDetails {
        point: |()| Point::TotalReactiveEnergyInj,
        size: 4,
        start_address: 27,
    },
    PointDetails {
        point: |()| Point::TotalReactiveEnergyAbs,
        size: 4,
        start_address: 31,
    },
    PointDetails {
        point: |()| Point::AmbientTemperature,
        size: 1,
        start_address: 35,
    },
    PointDetails {
        point: |()| Point::CabinetTemperature,
        size: 1,
        start_address: 36,
    },
    PointDetails {
        point: |()| Point::HeatSinkTemperature,
        size: 1,
        start_address: 37,
    },
    PointDetails {
        point: |()| Point::TransformerTemperature,
        size: 1,
        start_address: 38,
    },
    PointDetails {
        point: |()| Point::IgbtMosfetTemperature,
        size: 1,
        start_address: 39,
    },
    PointDetails {
        point: |()| Point::OtherTemperature,
        size: 1,
        start_address: 40,
    },
    PointDetails {
        point: |()| Point::WattsL1,
        size: 1,
        start_address: 41,
    },
    PointDetails {
        point: |()| Point::VaL1,
        size: 1,
        start_address: 42,
    },
    PointDetails {
        point: |()| Point::VarL1,
        size: 1,
        start_address: 43,
    },
    PointDetails {
        point: |()| Point::PfL1,
        size: 1,
        start_address: 44,
    },
    PointDetails {
        point: |()| Point::AmpsL1,
        size: 1,
        start_address: 45,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageL1L2,
        size: 1,
        start_address: 46,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageL1N,
        size: 1,
        start_address: 47,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursInjL1,
        size: 4,
        start_address: 48,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursAbsL1,
        size: 4,
        start_address: 52,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursInjL1,
        size: 4,
        start_address: 56,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursAbsL1,
        size: 4,
        start_address: 60,
    },
    PointDetails {
        point: |()| Point::WattsL2,
        size: 1,
        start_address: 64,
    },
    PointDetails {
        point: |()| Point::VaL2,
        size: 1,
        start_address: 65,
    },
    PointDetails {
        point: |()| Point::VarL2,
        size: 1,
        start_address: 66,
    },
    PointDetails {
        point: |()| Point::PfL2,
        size: 1,
        start_address: 67,
    },
    PointDetails {
        point: |()| Point::AmpsL2,
        size: 1,
        start_address: 68,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageL2L3,
        size: 1,
        start_address: 69,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageL2N,
        size: 1,
        start_address: 70,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursInjL2,
        size: 4,
        start_address: 71,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursAbsL2,
        size: 4,
        start_address: 75,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursInjL2,
        size: 4,
        start_address: 79,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursAbsL2,
        size: 4,
        start_address: 83,
    },
    PointDetails {
        point: |()| Point::WattsL3,
        size: 1,
        start_address: 87,
    },
    PointDetails {
        point: |()| Point::VaL3,
        size: 1,
        start_address: 88,
    },
    PointDetails {
        point: |()| Point::VarL3,
        size: 1,
        start_address: 89,
    },
    PointDetails {
        point: |()| Point::PfL3,
        size: 1,
        start_address: 90,
    },
    PointDetails {
        point: |()| Point::AmpsL3,
        size: 1,
        start_address: 91,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageL3L1,
        size: 1,
        start_address: 92,
    },
    PointDetails {
        point: |()| Point::PhaseVoltageL3N,
        size: 1,
        start_address: 93,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursInjL3,
        size: 4,
        start_address: 94,
    },
    PointDetails {
        point: |()| Point::TotalWattHoursAbsL3,
        size: 4,
        start_address: 98,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursInjL3,
        size: 4,
        start_address: 102,
    },
    PointDetails {
        point: |()| Point::TotalVarHoursAbsL3,
        size: 4,
        start_address: 106,
    },
    PointDetails {
        point: |()| Point::ThrottlingInPct,
        size: 1,
        start_address: 110,
    },
    PointDetails {
        point: |()| Point::ThrottleSourceInformation,
        size: 2,
        start_address: 111,
    },
    PointDetails {
        point: |()| Point::CurrentScaleFactor,
        size: 1,
        start_address: 113,
    },
    PointDetails {
        point: |()| Point::VoltageScaleFactor,
        size: 1,
        start_address: 114,
    },
    PointDetails {
        point: |()| Point::FrequencyScaleFactor,
        size: 1,
        start_address: 115,
    },
    PointDetails {
        point: |()| Point::ActivePowerScaleFactor,
        size: 1,
        start_address: 116,
    },
    PointDetails {
        point: |()| Point::PowerFactorScaleFactor,
        size: 1,
        start_address: 117,
    },
    PointDetails {
        point: |()| Point::ApparentPowerScaleFactor,
        size: 1,
        start_address: 118,
    },
    PointDetails {
        point: |()| Point::ReactivePowerScaleFactor,
        size: 1,
        start_address: 119,
    },
    PointDetails {
        point: |()| Point::ActiveEnergyScaleFactor,
        size: 1,
        start_address: 120,
    },
    PointDetails {
        point: |()| Point::ReactiveEnergyScaleFactor,
        size: 1,
        start_address: 121,
    },
    PointDetails {
        point: |()| Point::TemperatureScaleFactor,
        size: 1,
        start_address: 122,
    },
    PointDetails {
        point: |()| Point::ManufacturerAlarmInfo,
        size: 32,
        start_address: 123,
    },
];

#[derive(Debug)]
pub enum Point {
    ModelId,
    ModelLength,
    AcWiringType,
    OperatingState,
    InverterState,
    GridConnectionState,
    AlarmBitfield,
    DerOperationalCharacteristics,
    ActivePower,
    ApparentPower,
    ReactivePower,
    PowerFactor,
    TotalAcCurrent,
    VoltageLl,
    VoltageLn,
    Frequency,
    TotalEnergyInjected,
    TotalEnergyAbsorbed,
    TotalReactiveEnergyInj,
    TotalReactiveEnergyAbs,
    AmbientTemperature,
    CabinetTemperature,
    HeatSinkTemperature,
    TransformerTemperature,
    IgbtMosfetTemperature,
    OtherTemperature,
    WattsL1,
    VaL1,
    VarL1,
    PfL1,
    AmpsL1,
    PhaseVoltageL1L2,
    PhaseVoltageL1N,
    TotalWattHoursInjL1,
    TotalWattHoursAbsL1,
    TotalVarHoursInjL1,
    TotalVarHoursAbsL1,
    WattsL2,
    VaL2,
    VarL2,
    PfL2,
    AmpsL2,
    PhaseVoltageL2L3,
    PhaseVoltageL2N,
    TotalWattHoursInjL2,
    TotalWattHoursAbsL2,
    TotalVarHoursInjL2,
    TotalVarHoursAbsL2,
    WattsL3,
    VaL3,
    VarL3,
    PfL3,
    AmpsL3,
    PhaseVoltageL3L1,
    PhaseVoltageL3N,
    TotalWattHoursInjL3,
    TotalWattHoursAbsL3,
    TotalVarHoursInjL3,
    TotalVarHoursAbsL3,
    ThrottlingInPct,
    ThrottleSourceInformation,
    CurrentScaleFactor,
    VoltageScaleFactor,
    FrequencyScaleFactor,
    ActivePowerScaleFactor,
    PowerFactorScaleFactor,
    ApparentPowerScaleFactor,
    ReactivePowerScaleFactor,
    ActiveEnergyScaleFactor,
    ReactiveEnergyScaleFactor,
    TemperatureScaleFactor,
    ManufacturerAlarmInfo,
}

struct PointDetails<GroupIndexArgs> {
    point: fn(GroupIndexArgs) -> Point,
    start_address: u16,
    size: u16,
}

/// Marker for SunSpec model 701. Add it to a [`Sunspec`](crate::Sunspec) model list.
pub struct Model701;

impl<'ad> ModelSpec<'ad> for Model701 {
    const MODEL_ID: u16 = 701;
    type ReadAdapter = dyn ReadAdapter + 'ad;
    type WriteAdapter = dyn WriteAdapter + 'ad;

    fn model_length(&self) -> u16 {
        155
    }

    fn traverse_points_read<'a>(
        &self,
        adapter: &Self::ReadAdapter,
        buffer: &mut WritableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            write_point_to_buffer(
                self,
                adapter,
                &point,
                &mut buffer.slice(cursor, word_count),
                point_offset,
            );
            cursor += word_count;
        }

        Ok(())
    }

    fn traverse_points_write<'a>(
        &self,
        adapter: &mut Self::WriteAdapter,
        buffer: &ReadableRegisterBuffer<'a>,
        offset: u16,
    ) -> Result<(), ModbusException> {
        let until = offset + buffer.len();
        let mut cursor = 0;

        let iter = POINTS
            .iter()
            .map(|p| (p.start_address, p.size, (p.point)(())))
            .skip_while(|(start, size, _)| offset >= start + size)
            .take_while(|(start, _, _)| until > *start);

        for (start, size, point) in iter {
            let point_offset = offset.saturating_sub(start);
            let word_count = min(size - point_offset, buffer.len() - cursor);
            if point_offset > 0 {
                return Err(ModbusException::IllegalDataAddress);
            }
            read_point_from_buffer(self, adapter, &point, &buffer.slice(cursor, word_count))?;
            cursor += word_count;
        }

        Ok(())
    }
}

pub(crate) fn write_point_to_buffer<'a>(
    model: &Model701,
    adapter: &dyn ReadAdapter,
    point: &Point,
    buffer: &mut WritableRegisterBuffer<'a>,
    offset: u16,
) {
    match point {
        Point::ModelId => {
            buffer.write_u16(701);
        }
        Point::ModelLength => {
            buffer.write_u16(153);
        }
        Point::AcWiringType => {
            buffer.write_u16(adapter.ac_wiring_type() as u16);
        }
        Point::OperatingState => {
            if let Some(value) = adapter.operating_state() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::InverterState => {
            if let Some(value) = adapter.inverter_state() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::GridConnectionState => {
            if let Some(value) = adapter.grid_connection_state() {
                buffer.write_u16(value as u16);
            } else {
                buffer.zero();
            }
        }
        Point::AlarmBitfield => {
            if let Some(value) = adapter.alarm_bitfield() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::DerOperationalCharacteristics => {
            if let Some(value) = adapter.der_operational_characteristics() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::ActivePower => {
            if let Some(value) = adapter.active_power() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ApparentPower => {
            if let Some(value) = adapter.apparent_power() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ReactivePower => {
            if let Some(value) = adapter.reactive_power() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PowerFactor => {
            if let Some(value) = adapter.power_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TotalAcCurrent => {
            if let Some(value) = adapter.total_ac_current() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageLl => {
            if let Some(value) = adapter.voltage_ll() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageLn => {
            if let Some(value) = adapter.voltage_ln() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::Frequency => {
            if let Some(value) = adapter.frequency() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalEnergyInjected => {
            if let Some(value) = adapter.total_energy_injected() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalEnergyAbsorbed => {
            if let Some(value) = adapter.total_energy_absorbed() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalReactiveEnergyInj => {
            if let Some(value) = adapter.total_reactive_energy_inj() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalReactiveEnergyAbs => {
            if let Some(value) = adapter.total_reactive_energy_abs() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::AmbientTemperature => {
            if let Some(value) = adapter.ambient_temperature() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::CabinetTemperature => {
            if let Some(value) = adapter.cabinet_temperature() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::HeatSinkTemperature => {
            if let Some(value) = adapter.heat_sink_temperature() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TransformerTemperature => {
            if let Some(value) = adapter.transformer_temperature() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::IgbtMosfetTemperature => {
            if let Some(value) = adapter.igbt_mosfet_temperature() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::OtherTemperature => {
            if let Some(value) = adapter.other_temperature() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::WattsL1 => {
            if let Some(value) = adapter.watts_l1() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VaL1 => {
            if let Some(value) = adapter.va_l1() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VarL1 => {
            if let Some(value) = adapter.var_l1() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PfL1 => {
            if let Some(value) = adapter.pf_l1() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::AmpsL1 => {
            if let Some(value) = adapter.amps_l1() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseVoltageL1L2 => {
            if let Some(value) = adapter.phase_voltage_l1_l2() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseVoltageL1N => {
            if let Some(value) = adapter.phase_voltage_l1_n() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursInjL1 => {
            if let Some(value) = adapter.total_watt_hours_inj_l1() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursAbsL1 => {
            if let Some(value) = adapter.total_watt_hours_abs_l1() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursInjL1 => {
            if let Some(value) = adapter.total_var_hours_inj_l1() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursAbsL1 => {
            if let Some(value) = adapter.total_var_hours_abs_l1() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::WattsL2 => {
            if let Some(value) = adapter.watts_l2() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VaL2 => {
            if let Some(value) = adapter.va_l2() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VarL2 => {
            if let Some(value) = adapter.var_l2() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PfL2 => {
            if let Some(value) = adapter.pf_l2() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::AmpsL2 => {
            if let Some(value) = adapter.amps_l2() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseVoltageL2L3 => {
            if let Some(value) = adapter.phase_voltage_l2_l3() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseVoltageL2N => {
            if let Some(value) = adapter.phase_voltage_l2_n() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursInjL2 => {
            if let Some(value) = adapter.total_watt_hours_inj_l2() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursAbsL2 => {
            if let Some(value) = adapter.total_watt_hours_abs_l2() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursInjL2 => {
            if let Some(value) = adapter.total_var_hours_inj_l2() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursAbsL2 => {
            if let Some(value) = adapter.total_var_hours_abs_l2() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::WattsL3 => {
            if let Some(value) = adapter.watts_l3() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VaL3 => {
            if let Some(value) = adapter.va_l3() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VarL3 => {
            if let Some(value) = adapter.var_l3() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PfL3 => {
            if let Some(value) = adapter.pf_l3() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::AmpsL3 => {
            if let Some(value) = adapter.amps_l3() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseVoltageL3L1 => {
            if let Some(value) = adapter.phase_voltage_l3_l1() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PhaseVoltageL3N => {
            if let Some(value) = adapter.phase_voltage_l3_n() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursInjL3 => {
            if let Some(value) = adapter.total_watt_hours_inj_l3() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalWattHoursAbsL3 => {
            if let Some(value) = adapter.total_watt_hours_abs_l3() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursInjL3 => {
            if let Some(value) = adapter.total_var_hours_inj_l3() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::TotalVarHoursAbsL3 => {
            if let Some(value) = adapter.total_var_hours_abs_l3() {
                buffer.write_u64(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::ThrottlingInPct => {
            if let Some(value) = adapter.throttling_in_pct() {
                buffer.write_u16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ThrottleSourceInformation => {
            if let Some(value) = adapter.throttle_source_information() {
                buffer.write_u32(value, offset);
            } else {
                buffer.zero();
            }
        }
        Point::CurrentScaleFactor => {
            if let Some(value) = adapter.current_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::VoltageScaleFactor => {
            if let Some(value) = adapter.voltage_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::FrequencyScaleFactor => {
            if let Some(value) = adapter.frequency_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ActivePowerScaleFactor => {
            if let Some(value) = adapter.active_power_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::PowerFactorScaleFactor => {
            if let Some(value) = adapter.power_factor_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ApparentPowerScaleFactor => {
            if let Some(value) = adapter.apparent_power_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ReactivePowerScaleFactor => {
            if let Some(value) = adapter.reactive_power_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ActiveEnergyScaleFactor => {
            if let Some(value) = adapter.active_energy_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ReactiveEnergyScaleFactor => {
            if let Some(value) = adapter.reactive_energy_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::TemperatureScaleFactor => {
            if let Some(value) = adapter.temperature_scale_factor() {
                buffer.write_i16(value);
            } else {
                buffer.zero();
            }
        }
        Point::ManufacturerAlarmInfo => {
            if let Some(value) = adapter.manufacturer_alarm_info() {
                buffer.write_string(value, offset);
            } else {
                buffer.zero();
            }
        }
    }
}

pub(crate) fn read_point_from_buffer<'a>(
    model: &Model701,
    adapter: &mut dyn WriteAdapter,
    point: &Point,
    buffer: &ReadableRegisterBuffer<'a>,
) -> Result<(), ModbusException> {
    Err(ModbusException::IllegalDataAddress)
}

pub trait ReadAdapter {
    /// AC Wiring Type (ACType)
    ///
    /// AC wiring type.
    fn ac_wiring_type(&self) -> AcType;

    /// Operating State (St)
    ///
    /// Operating state of the DER.
    fn operating_state(&self) -> Option<St> {
        None
    }

    /// Inverter State (InvSt)
    ///
    /// Inverter state.
    fn inverter_state(&self) -> Option<InvSt> {
        None
    }

    /// Grid Connection State (ConnSt)
    ///
    /// Grid connection state of the DER.
    fn grid_connection_state(&self) -> Option<ConnSt> {
        None
    }

    /// Alarm Bitfield (Alrm)
    ///
    /// Active alarms for the DER.
    fn alarm_bitfield(&self) -> Option<u32> {
        None
    }

    /// DER Operational Characteristics (DERMode)
    ///
    /// Current operational characteristics of the DER.
    fn der_operational_characteristics(&self) -> Option<u32> {
        None
    }

    /// Active Power (W)
    ///
    /// Total active power. Active power is positive for DER generation and negative for absorption.
    fn active_power(&self) -> Option<i16> {
        None
    }

    /// Apparent Power (VA)
    ///
    /// Total apparent power.
    fn apparent_power(&self) -> Option<i16> {
        None
    }

    /// Reactive Power (Var)
    ///
    /// Total reactive power.
    fn reactive_power(&self) -> Option<i16> {
        None
    }

    /// Power Factor (PF)
    ///
    /// Power factor. The sign of power factor should be the sign of active power.
    fn power_factor(&self) -> Option<i16> {
        None
    }

    /// Total AC Current (A)
    ///
    /// Total AC current.
    fn total_ac_current(&self) -> Option<i16> {
        None
    }

    /// Voltage LL (LLV)
    ///
    /// Line to line AC voltage as an average of active phases.
    fn voltage_ll(&self) -> Option<u16> {
        None
    }

    /// Voltage LN (LNV)
    ///
    /// Line to neutral AC voltage as an average of active phases.
    fn voltage_ln(&self) -> Option<u16> {
        None
    }

    /// Frequency (Hz)
    ///
    /// AC frequency.
    fn frequency(&self) -> Option<u32> {
        None
    }

    /// Total Energy Injected (TotWhInj)
    ///
    /// Total active energy injected (Quadrants 1 & 4).
    fn total_energy_injected(&self) -> Option<u64> {
        None
    }

    /// Total Energy Absorbed (TotWhAbs)
    ///
    /// Total active energy absorbed (Quadrants 2 & 3).
    fn total_energy_absorbed(&self) -> Option<u64> {
        None
    }

    /// Total Reactive Energy Inj (TotVarhInj)
    ///
    /// Total reactive energy injected (Quadrants 1 & 2).
    fn total_reactive_energy_inj(&self) -> Option<u64> {
        None
    }

    /// Total Reactive Energy Abs (TotVarhAbs)
    ///
    /// Total reactive energy absorbed (Quadrants 3 & 4).
    fn total_reactive_energy_abs(&self) -> Option<u64> {
        None
    }

    /// Ambient Temperature (TmpAmb)
    ///
    /// Ambient temperature.
    fn ambient_temperature(&self) -> Option<i16> {
        None
    }

    /// Cabinet Temperature (TmpCab)
    ///
    /// Cabinet temperature.
    fn cabinet_temperature(&self) -> Option<i16> {
        None
    }

    /// Heat Sink Temperature (TmpSnk)
    ///
    /// Heat sink temperature.
    fn heat_sink_temperature(&self) -> Option<i16> {
        None
    }

    /// Transformer Temperature (TmpTrns)
    ///
    /// Transformer temperature.
    fn transformer_temperature(&self) -> Option<i16> {
        None
    }

    /// IGBT/MOSFET Temperature (TmpSw)
    ///
    /// IGBT/MOSFET temperature.
    fn igbt_mosfet_temperature(&self) -> Option<i16> {
        None
    }

    /// Other Temperature (TmpOt)
    ///
    /// Other temperature.
    fn other_temperature(&self) -> Option<i16> {
        None
    }

    /// Watts L1 (WL1)
    ///
    /// Active power L1.
    fn watts_l1(&self) -> Option<i16> {
        None
    }

    /// VA L1 (VAL1)
    ///
    /// Apparent power L1.
    fn va_l1(&self) -> Option<i16> {
        None
    }

    /// Var L1 (VarL1)
    ///
    /// Reactive power L1.
    fn var_l1(&self) -> Option<i16> {
        None
    }

    /// PF L1 (PFL1)
    ///
    /// Power factor phase L1.
    fn pf_l1(&self) -> Option<i16> {
        None
    }

    /// Amps L1 (AL1)
    ///
    /// Current phase L1.
    fn amps_l1(&self) -> Option<i16> {
        None
    }

    /// Phase Voltage L1-L2 (VL1L2)
    ///
    /// Phase voltage L1-L2.
    fn phase_voltage_l1_l2(&self) -> Option<u16> {
        None
    }

    /// Phase Voltage L1-N (VL1)
    ///
    /// Phase voltage L1-N.
    fn phase_voltage_l1_n(&self) -> Option<u16> {
        None
    }

    /// Total Watt-Hours Inj L1 (TotWhInjL1)
    ///
    /// Total active energy injected L1.
    fn total_watt_hours_inj_l1(&self) -> Option<u64> {
        None
    }

    /// Total Watt-Hours Abs L1 (TotWhAbsL1)
    ///
    /// Total active energy absorbed L1.
    fn total_watt_hours_abs_l1(&self) -> Option<u64> {
        None
    }

    /// Total Var-Hours Inj L1 (TotVarhInjL1)
    ///
    /// Total reactive energy injected L1.
    fn total_var_hours_inj_l1(&self) -> Option<u64> {
        None
    }

    /// Total Var-Hours Abs L1 (TotVarhAbsL1)
    ///
    /// Total reactive energy absorbed L1.
    fn total_var_hours_abs_l1(&self) -> Option<u64> {
        None
    }

    /// Watts L2 (WL2)
    ///
    /// Active power L2.
    fn watts_l2(&self) -> Option<i16> {
        None
    }

    /// VA L2 (VAL2)
    ///
    /// Apparent power L2.
    fn va_l2(&self) -> Option<i16> {
        None
    }

    /// Var L2 (VarL2)
    ///
    /// Reactive power L2.
    fn var_l2(&self) -> Option<i16> {
        None
    }

    /// PF L2 (PFL2)
    ///
    /// Power factor L2.
    fn pf_l2(&self) -> Option<i16> {
        None
    }

    /// Amps L2 (AL2)
    ///
    /// Current L2.
    fn amps_l2(&self) -> Option<i16> {
        None
    }

    /// Phase Voltage L2-L3 (VL2L3)
    ///
    /// Phase voltage L2-L3.
    fn phase_voltage_l2_l3(&self) -> Option<u16> {
        None
    }

    /// Phase Voltage L2-N (VL2)
    ///
    /// Phase voltage L2-N.
    fn phase_voltage_l2_n(&self) -> Option<u16> {
        None
    }

    /// Total Watt-Hours Inj L2 (TotWhInjL2)
    ///
    /// Total active energy injected L2.
    fn total_watt_hours_inj_l2(&self) -> Option<u64> {
        None
    }

    /// Total Watt-Hours Abs L2 (TotWhAbsL2)
    ///
    /// Total active energy absorbed L2.
    fn total_watt_hours_abs_l2(&self) -> Option<u64> {
        None
    }

    /// Total Var-Hours Inj L2 (TotVarhInjL2)
    ///
    /// Total reactive energy injected L2.
    fn total_var_hours_inj_l2(&self) -> Option<u64> {
        None
    }

    /// Total Var-Hours Abs L2 (TotVarhAbsL2)
    ///
    /// Total reactive energy absorbed L2.
    fn total_var_hours_abs_l2(&self) -> Option<u64> {
        None
    }

    /// Watts L3 (WL3)
    ///
    /// Active power L3.
    fn watts_l3(&self) -> Option<i16> {
        None
    }

    /// VA L3 (VAL3)
    ///
    /// Apparent power L3.
    fn va_l3(&self) -> Option<i16> {
        None
    }

    /// Var L3 (VarL3)
    ///
    /// Reactive power L3.
    fn var_l3(&self) -> Option<i16> {
        None
    }

    /// PF L3 (PFL3)
    ///
    /// Power factor L3.
    fn pf_l3(&self) -> Option<i16> {
        None
    }

    /// Amps L3 (AL3)
    ///
    /// Current L3.
    fn amps_l3(&self) -> Option<i16> {
        None
    }

    /// Phase Voltage L3-L1 (VL3L1)
    ///
    /// Phase voltage L3-L1.
    fn phase_voltage_l3_l1(&self) -> Option<u16> {
        None
    }

    /// Phase Voltage L3-N (VL3)
    ///
    /// Phase voltage L3-N.
    fn phase_voltage_l3_n(&self) -> Option<u16> {
        None
    }

    /// Total Watt-Hours Inj L3 (TotWhInjL3)
    ///
    /// Total active energy injected L3.
    fn total_watt_hours_inj_l3(&self) -> Option<u64> {
        None
    }

    /// Total Watt-Hours Abs L3 (TotWhAbsL3)
    ///
    /// Total active energy absorbed L3.
    fn total_watt_hours_abs_l3(&self) -> Option<u64> {
        None
    }

    /// Total Var-Hours Inj L3 (TotVarhInjL3)
    ///
    /// Total reactive energy injected L3.
    fn total_var_hours_inj_l3(&self) -> Option<u64> {
        None
    }

    /// Total Var-Hours Abs L3 (TotVarhAbsL3)
    ///
    /// Total reactive energy absorbed L3.
    fn total_var_hours_abs_l3(&self) -> Option<u64> {
        None
    }

    /// Throttling In Pct (ThrotPct)
    ///
    /// Throttling in pct of maximum active power.
    fn throttling_in_pct(&self) -> Option<u16> {
        None
    }

    /// Throttle Source Information (ThrotSrc)
    ///
    /// Active throttling source.
    fn throttle_source_information(&self) -> Option<u32> {
        None
    }

    /// Current Scale Factor (A_SF)
    ///
    /// Current scale factor.
    fn current_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Voltage Scale Factor (V_SF)
    ///
    /// Voltage scale factor.
    fn voltage_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Frequency Scale Factor (Hz_SF)
    ///
    /// Frequency scale factor.
    fn frequency_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Active Power Scale Factor (W_SF)
    ///
    /// Active power scale factor.
    fn active_power_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Power Factor Scale Factor (PF_SF)
    ///
    /// Power factor scale factor.
    fn power_factor_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Apparent Power Scale Factor (VA_SF)
    ///
    /// Apparent power scale factor.
    fn apparent_power_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Reactive Power Scale Factor (Var_SF)
    ///
    /// Reactive power scale factor.
    fn reactive_power_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Active Energy Scale Factor (TotWh_SF)
    ///
    /// Active energy scale factor.
    fn active_energy_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Reactive Energy Scale Factor (TotVarh_SF)
    ///
    /// Reactive energy scale factor.
    fn reactive_energy_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Temperature Scale Factor (Tmp_SF)
    ///
    /// Temperature scale factor.
    fn temperature_scale_factor(&self) -> Option<i16> {
        None
    }

    /// Manufacturer Alarm Info (MnAlrmInfo)
    ///
    /// Manufacturer alarm information. Valid if MANUFACTURER_ALRM indication is active.
    fn manufacturer_alarm_info(&self) -> Option<&CStr> {
        None
    }
}

pub trait WriteAdapter {}

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model701AcType {
    /// Single Phase
    SinglePhase = 0,
    /// Split Phase
    SplitPhase = 1,
    /// Three Phase
    ThreePhase = 2,
}

impl Model701AcType {
    pub fn from_repr(repr: u16) -> Option<Model701AcType> {
        match repr {
            0 => Some(Model701AcType::SinglePhase),
            1 => Some(Model701AcType::SplitPhase),
            2 => Some(Model701AcType::ThreePhase),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model701AcType`] - only `Model701AcType` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `AcType` distinct from another model's point of the same name.
pub type AcType = Model701AcType;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model701ConnSt {
    /// Disconnected
    ///
    /// Disconnected from the grid.
    Disconnected = 0,
    /// Connected
    ///
    /// Connected to the grid.
    Connected = 1,
}

impl Model701ConnSt {
    pub fn from_repr(repr: u16) -> Option<Model701ConnSt> {
        match repr {
            0 => Some(Model701ConnSt::Disconnected),
            1 => Some(Model701ConnSt::Connected),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model701ConnSt`] - only `Model701ConnSt` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `ConnSt` distinct from another model's point of the same name.
pub type ConnSt = Model701ConnSt;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model701InvSt {
    Off = 0,
    Sleeping = 1,
    Starting = 2,
    Running = 3,
    Throttled = 4,
    ShuttingDown = 5,
    Fault = 6,
    Standby = 7,
}

impl Model701InvSt {
    pub fn from_repr(repr: u16) -> Option<Model701InvSt> {
        match repr {
            0 => Some(Model701InvSt::Off),
            1 => Some(Model701InvSt::Sleeping),
            2 => Some(Model701InvSt::Starting),
            3 => Some(Model701InvSt::Running),
            4 => Some(Model701InvSt::Throttled),
            5 => Some(Model701InvSt::ShuttingDown),
            6 => Some(Model701InvSt::Fault),
            7 => Some(Model701InvSt::Standby),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model701InvSt`] - only `Model701InvSt` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `InvSt` distinct from another model's point of the same name.
pub type InvSt = Model701InvSt;

#[derive(Clone, Copy, Debug, PartialEq)]
#[repr(u16)]
pub enum Model701St {
    /// Off
    Off = 0,
    /// On
    On = 1,
}

impl Model701St {
    pub fn from_repr(repr: u16) -> Option<Model701St> {
        match repr {
            0 => Some(Model701St::Off),
            1 => Some(Model701St::On),
            _ => None,
        }
    }
}

/// Short, spec-matching alias for [`Model701St`] - only `Model701St` (unique per model) reaches the generated C header, since cbindgen has no module system to keep `St` distinct from another model's point of the same name.
pub type St = Model701St;

#[repr(C)]
pub struct Model701CallbackAdapter {
    context: *mut c_void,
    /// AC Wiring Type (ACType)
    ///
    /// AC wiring type.
    ac_wiring_type_callback: extern "C" fn(*const c_void) -> Model701AcType,
    /// Operating State (St)
    ///
    /// Operating state of the DER.
    operating_state_callback: Option<extern "C" fn(*const c_void) -> Model701St>,
    /// Inverter State (InvSt)
    ///
    /// Inverter state.
    inverter_state_callback: Option<extern "C" fn(*const c_void) -> Model701InvSt>,
    /// Grid Connection State (ConnSt)
    ///
    /// Grid connection state of the DER.
    grid_connection_state_callback: Option<extern "C" fn(*const c_void) -> Model701ConnSt>,
    /// Alarm Bitfield (Alrm)
    ///
    /// Active alarms for the DER.
    alarm_bitfield_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// DER Operational Characteristics (DERMode)
    ///
    /// Current operational characteristics of the DER.
    der_operational_characteristics_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Active Power (W)
    ///
    /// Total active power. Active power is positive for DER generation and negative for absorption.
    active_power_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Apparent Power (VA)
    ///
    /// Total apparent power.
    apparent_power_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Reactive Power (Var)
    ///
    /// Total reactive power.
    reactive_power_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Power Factor (PF)
    ///
    /// Power factor. The sign of power factor should be the sign of active power.
    power_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Total AC Current (A)
    ///
    /// Total AC current.
    total_ac_current_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Voltage LL (LLV)
    ///
    /// Line to line AC voltage as an average of active phases.
    voltage_ll_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Voltage LN (LNV)
    ///
    /// Line to neutral AC voltage as an average of active phases.
    voltage_ln_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Frequency (Hz)
    ///
    /// AC frequency.
    frequency_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Total Energy Injected (TotWhInj)
    ///
    /// Total active energy injected (Quadrants 1 & 4).
    total_energy_injected_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Energy Absorbed (TotWhAbs)
    ///
    /// Total active energy absorbed (Quadrants 2 & 3).
    total_energy_absorbed_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Reactive Energy Inj (TotVarhInj)
    ///
    /// Total reactive energy injected (Quadrants 1 & 2).
    total_reactive_energy_inj_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Reactive Energy Abs (TotVarhAbs)
    ///
    /// Total reactive energy absorbed (Quadrants 3 & 4).
    total_reactive_energy_abs_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Ambient Temperature (TmpAmb)
    ///
    /// Ambient temperature.
    ambient_temperature_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Cabinet Temperature (TmpCab)
    ///
    /// Cabinet temperature.
    cabinet_temperature_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Heat Sink Temperature (TmpSnk)
    ///
    /// Heat sink temperature.
    heat_sink_temperature_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Transformer Temperature (TmpTrns)
    ///
    /// Transformer temperature.
    transformer_temperature_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// IGBT/MOSFET Temperature (TmpSw)
    ///
    /// IGBT/MOSFET temperature.
    igbt_mosfet_temperature_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Other Temperature (TmpOt)
    ///
    /// Other temperature.
    other_temperature_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Watts L1 (WL1)
    ///
    /// Active power L1.
    watts_l1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// VA L1 (VAL1)
    ///
    /// Apparent power L1.
    va_l1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Var L1 (VarL1)
    ///
    /// Reactive power L1.
    var_l1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// PF L1 (PFL1)
    ///
    /// Power factor phase L1.
    pf_l1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Amps L1 (AL1)
    ///
    /// Current phase L1.
    amps_l1_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Phase Voltage L1-L2 (VL1L2)
    ///
    /// Phase voltage L1-L2.
    phase_voltage_l1_l2_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Phase Voltage L1-N (VL1)
    ///
    /// Phase voltage L1-N.
    phase_voltage_l1_n_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Total Watt-Hours Inj L1 (TotWhInjL1)
    ///
    /// Total active energy injected L1.
    total_watt_hours_inj_l1_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Watt-Hours Abs L1 (TotWhAbsL1)
    ///
    /// Total active energy absorbed L1.
    total_watt_hours_abs_l1_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Var-Hours Inj L1 (TotVarhInjL1)
    ///
    /// Total reactive energy injected L1.
    total_var_hours_inj_l1_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Var-Hours Abs L1 (TotVarhAbsL1)
    ///
    /// Total reactive energy absorbed L1.
    total_var_hours_abs_l1_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Watts L2 (WL2)
    ///
    /// Active power L2.
    watts_l2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// VA L2 (VAL2)
    ///
    /// Apparent power L2.
    va_l2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Var L2 (VarL2)
    ///
    /// Reactive power L2.
    var_l2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// PF L2 (PFL2)
    ///
    /// Power factor L2.
    pf_l2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Amps L2 (AL2)
    ///
    /// Current L2.
    amps_l2_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Phase Voltage L2-L3 (VL2L3)
    ///
    /// Phase voltage L2-L3.
    phase_voltage_l2_l3_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Phase Voltage L2-N (VL2)
    ///
    /// Phase voltage L2-N.
    phase_voltage_l2_n_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Total Watt-Hours Inj L2 (TotWhInjL2)
    ///
    /// Total active energy injected L2.
    total_watt_hours_inj_l2_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Watt-Hours Abs L2 (TotWhAbsL2)
    ///
    /// Total active energy absorbed L2.
    total_watt_hours_abs_l2_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Var-Hours Inj L2 (TotVarhInjL2)
    ///
    /// Total reactive energy injected L2.
    total_var_hours_inj_l2_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Var-Hours Abs L2 (TotVarhAbsL2)
    ///
    /// Total reactive energy absorbed L2.
    total_var_hours_abs_l2_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Watts L3 (WL3)
    ///
    /// Active power L3.
    watts_l3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// VA L3 (VAL3)
    ///
    /// Apparent power L3.
    va_l3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Var L3 (VarL3)
    ///
    /// Reactive power L3.
    var_l3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// PF L3 (PFL3)
    ///
    /// Power factor L3.
    pf_l3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Amps L3 (AL3)
    ///
    /// Current L3.
    amps_l3_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Phase Voltage L3-L1 (VL3L1)
    ///
    /// Phase voltage L3-L1.
    phase_voltage_l3_l1_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Phase Voltage L3-N (VL3)
    ///
    /// Phase voltage L3-N.
    phase_voltage_l3_n_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Total Watt-Hours Inj L3 (TotWhInjL3)
    ///
    /// Total active energy injected L3.
    total_watt_hours_inj_l3_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Watt-Hours Abs L3 (TotWhAbsL3)
    ///
    /// Total active energy absorbed L3.
    total_watt_hours_abs_l3_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Var-Hours Inj L3 (TotVarhInjL3)
    ///
    /// Total reactive energy injected L3.
    total_var_hours_inj_l3_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Total Var-Hours Abs L3 (TotVarhAbsL3)
    ///
    /// Total reactive energy absorbed L3.
    total_var_hours_abs_l3_callback: Option<extern "C" fn(*const c_void) -> u64>,
    /// Throttling In Pct (ThrotPct)
    ///
    /// Throttling in pct of maximum active power.
    throttling_in_pct_callback: Option<extern "C" fn(*const c_void) -> u16>,
    /// Throttle Source Information (ThrotSrc)
    ///
    /// Active throttling source.
    throttle_source_information_callback: Option<extern "C" fn(*const c_void) -> u32>,
    /// Current Scale Factor (A_SF)
    ///
    /// Current scale factor.
    current_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Voltage Scale Factor (V_SF)
    ///
    /// Voltage scale factor.
    voltage_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Frequency Scale Factor (Hz_SF)
    ///
    /// Frequency scale factor.
    frequency_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Active Power Scale Factor (W_SF)
    ///
    /// Active power scale factor.
    active_power_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Power Factor Scale Factor (PF_SF)
    ///
    /// Power factor scale factor.
    power_factor_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Apparent Power Scale Factor (VA_SF)
    ///
    /// Apparent power scale factor.
    apparent_power_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Reactive Power Scale Factor (Var_SF)
    ///
    /// Reactive power scale factor.
    reactive_power_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Active Energy Scale Factor (TotWh_SF)
    ///
    /// Active energy scale factor.
    active_energy_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Reactive Energy Scale Factor (TotVarh_SF)
    ///
    /// Reactive energy scale factor.
    reactive_energy_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Temperature Scale Factor (Tmp_SF)
    ///
    /// Temperature scale factor.
    temperature_scale_factor_callback: Option<extern "C" fn(*const c_void) -> i16>,
    /// Manufacturer Alarm Info (MnAlrmInfo)
    ///
    /// Manufacturer alarm information. Valid if MANUFACTURER_ALRM indication is active.
    manufacturer_alarm_info_callback: Option<extern "C" fn(*const c_void) -> *const c_char>,
}

impl ReadAdapter for Model701CallbackAdapter {
    fn ac_wiring_type(&self) -> AcType {
        (self.ac_wiring_type_callback)(self.context)
    }

    fn operating_state(&self) -> Option<St> {
        self.operating_state_callback
            .map(|callback| (callback)(self.context))
    }

    fn inverter_state(&self) -> Option<InvSt> {
        self.inverter_state_callback
            .map(|callback| (callback)(self.context))
    }

    fn grid_connection_state(&self) -> Option<ConnSt> {
        self.grid_connection_state_callback
            .map(|callback| (callback)(self.context))
    }

    fn alarm_bitfield(&self) -> Option<u32> {
        self.alarm_bitfield_callback
            .map(|callback| (callback)(self.context))
    }

    fn der_operational_characteristics(&self) -> Option<u32> {
        self.der_operational_characteristics_callback
            .map(|callback| (callback)(self.context))
    }

    fn active_power(&self) -> Option<i16> {
        self.active_power_callback
            .map(|callback| (callback)(self.context))
    }

    fn apparent_power(&self) -> Option<i16> {
        self.apparent_power_callback
            .map(|callback| (callback)(self.context))
    }

    fn reactive_power(&self) -> Option<i16> {
        self.reactive_power_callback
            .map(|callback| (callback)(self.context))
    }

    fn power_factor(&self) -> Option<i16> {
        self.power_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_ac_current(&self) -> Option<i16> {
        self.total_ac_current_callback
            .map(|callback| (callback)(self.context))
    }

    fn voltage_ll(&self) -> Option<u16> {
        self.voltage_ll_callback
            .map(|callback| (callback)(self.context))
    }

    fn voltage_ln(&self) -> Option<u16> {
        self.voltage_ln_callback
            .map(|callback| (callback)(self.context))
    }

    fn frequency(&self) -> Option<u32> {
        self.frequency_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_energy_injected(&self) -> Option<u64> {
        self.total_energy_injected_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_energy_absorbed(&self) -> Option<u64> {
        self.total_energy_absorbed_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_reactive_energy_inj(&self) -> Option<u64> {
        self.total_reactive_energy_inj_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_reactive_energy_abs(&self) -> Option<u64> {
        self.total_reactive_energy_abs_callback
            .map(|callback| (callback)(self.context))
    }

    fn ambient_temperature(&self) -> Option<i16> {
        self.ambient_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn cabinet_temperature(&self) -> Option<i16> {
        self.cabinet_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn heat_sink_temperature(&self) -> Option<i16> {
        self.heat_sink_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn transformer_temperature(&self) -> Option<i16> {
        self.transformer_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn igbt_mosfet_temperature(&self) -> Option<i16> {
        self.igbt_mosfet_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn other_temperature(&self) -> Option<i16> {
        self.other_temperature_callback
            .map(|callback| (callback)(self.context))
    }

    fn watts_l1(&self) -> Option<i16> {
        self.watts_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn va_l1(&self) -> Option<i16> {
        self.va_l1_callback.map(|callback| (callback)(self.context))
    }

    fn var_l1(&self) -> Option<i16> {
        self.var_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn pf_l1(&self) -> Option<i16> {
        self.pf_l1_callback.map(|callback| (callback)(self.context))
    }

    fn amps_l1(&self) -> Option<i16> {
        self.amps_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn phase_voltage_l1_l2(&self) -> Option<u16> {
        self.phase_voltage_l1_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn phase_voltage_l1_n(&self) -> Option<u16> {
        self.phase_voltage_l1_n_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_inj_l1(&self) -> Option<u64> {
        self.total_watt_hours_inj_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_abs_l1(&self) -> Option<u64> {
        self.total_watt_hours_abs_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_inj_l1(&self) -> Option<u64> {
        self.total_var_hours_inj_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_abs_l1(&self) -> Option<u64> {
        self.total_var_hours_abs_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn watts_l2(&self) -> Option<i16> {
        self.watts_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn va_l2(&self) -> Option<i16> {
        self.va_l2_callback.map(|callback| (callback)(self.context))
    }

    fn var_l2(&self) -> Option<i16> {
        self.var_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn pf_l2(&self) -> Option<i16> {
        self.pf_l2_callback.map(|callback| (callback)(self.context))
    }

    fn amps_l2(&self) -> Option<i16> {
        self.amps_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn phase_voltage_l2_l3(&self) -> Option<u16> {
        self.phase_voltage_l2_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn phase_voltage_l2_n(&self) -> Option<u16> {
        self.phase_voltage_l2_n_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_inj_l2(&self) -> Option<u64> {
        self.total_watt_hours_inj_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_abs_l2(&self) -> Option<u64> {
        self.total_watt_hours_abs_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_inj_l2(&self) -> Option<u64> {
        self.total_var_hours_inj_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_abs_l2(&self) -> Option<u64> {
        self.total_var_hours_abs_l2_callback
            .map(|callback| (callback)(self.context))
    }

    fn watts_l3(&self) -> Option<i16> {
        self.watts_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn va_l3(&self) -> Option<i16> {
        self.va_l3_callback.map(|callback| (callback)(self.context))
    }

    fn var_l3(&self) -> Option<i16> {
        self.var_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn pf_l3(&self) -> Option<i16> {
        self.pf_l3_callback.map(|callback| (callback)(self.context))
    }

    fn amps_l3(&self) -> Option<i16> {
        self.amps_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn phase_voltage_l3_l1(&self) -> Option<u16> {
        self.phase_voltage_l3_l1_callback
            .map(|callback| (callback)(self.context))
    }

    fn phase_voltage_l3_n(&self) -> Option<u16> {
        self.phase_voltage_l3_n_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_inj_l3(&self) -> Option<u64> {
        self.total_watt_hours_inj_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_watt_hours_abs_l3(&self) -> Option<u64> {
        self.total_watt_hours_abs_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_inj_l3(&self) -> Option<u64> {
        self.total_var_hours_inj_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn total_var_hours_abs_l3(&self) -> Option<u64> {
        self.total_var_hours_abs_l3_callback
            .map(|callback| (callback)(self.context))
    }

    fn throttling_in_pct(&self) -> Option<u16> {
        self.throttling_in_pct_callback
            .map(|callback| (callback)(self.context))
    }

    fn throttle_source_information(&self) -> Option<u32> {
        self.throttle_source_information_callback
            .map(|callback| (callback)(self.context))
    }

    fn current_scale_factor(&self) -> Option<i16> {
        self.current_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn voltage_scale_factor(&self) -> Option<i16> {
        self.voltage_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn frequency_scale_factor(&self) -> Option<i16> {
        self.frequency_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn active_power_scale_factor(&self) -> Option<i16> {
        self.active_power_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn power_factor_scale_factor(&self) -> Option<i16> {
        self.power_factor_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn apparent_power_scale_factor(&self) -> Option<i16> {
        self.apparent_power_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn reactive_power_scale_factor(&self) -> Option<i16> {
        self.reactive_power_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn active_energy_scale_factor(&self) -> Option<i16> {
        self.active_energy_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn reactive_energy_scale_factor(&self) -> Option<i16> {
        self.reactive_energy_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn temperature_scale_factor(&self) -> Option<i16> {
        self.temperature_scale_factor_callback
            .map(|callback| (callback)(self.context))
    }

    fn manufacturer_alarm_info(&self) -> Option<&CStr> {
        self.manufacturer_alarm_info_callback
            .map(|callback| unsafe { CStr::from_ptr((callback)(self.context)) })
    }
}

#[repr(C)]
pub struct Model701StatefulAdapter {
    /// AC Wiring Type (ACType)
    ///
    /// AC wiring type.
    pub ac_wiring_type: Model701AcType,
    /// Operating State (St)
    ///
    /// Operating state of the DER.
    pub operating_state: Model701St,
    /// Inverter State (InvSt)
    ///
    /// Inverter state.
    pub inverter_state: Model701InvSt,
    /// Grid Connection State (ConnSt)
    ///
    /// Grid connection state of the DER.
    pub grid_connection_state: Model701ConnSt,
    /// Alarm Bitfield (Alrm)
    ///
    /// Active alarms for the DER.
    pub alarm_bitfield: u32,
    /// DER Operational Characteristics (DERMode)
    ///
    /// Current operational characteristics of the DER.
    pub der_operational_characteristics: u32,
    /// Active Power (W)
    ///
    /// Total active power. Active power is positive for DER generation and negative for absorption.
    pub active_power: i16,
    /// Apparent Power (VA)
    ///
    /// Total apparent power.
    pub apparent_power: i16,
    /// Reactive Power (Var)
    ///
    /// Total reactive power.
    pub reactive_power: i16,
    /// Power Factor (PF)
    ///
    /// Power factor. The sign of power factor should be the sign of active power.
    pub power_factor: i16,
    /// Total AC Current (A)
    ///
    /// Total AC current.
    pub total_ac_current: i16,
    /// Voltage LL (LLV)
    ///
    /// Line to line AC voltage as an average of active phases.
    pub voltage_ll: u16,
    /// Voltage LN (LNV)
    ///
    /// Line to neutral AC voltage as an average of active phases.
    pub voltage_ln: u16,
    /// Frequency (Hz)
    ///
    /// AC frequency.
    pub frequency: u32,
    /// Total Energy Injected (TotWhInj)
    ///
    /// Total active energy injected (Quadrants 1 & 4).
    pub total_energy_injected: u64,
    /// Total Energy Absorbed (TotWhAbs)
    ///
    /// Total active energy absorbed (Quadrants 2 & 3).
    pub total_energy_absorbed: u64,
    /// Total Reactive Energy Inj (TotVarhInj)
    ///
    /// Total reactive energy injected (Quadrants 1 & 2).
    pub total_reactive_energy_inj: u64,
    /// Total Reactive Energy Abs (TotVarhAbs)
    ///
    /// Total reactive energy absorbed (Quadrants 3 & 4).
    pub total_reactive_energy_abs: u64,
    /// Ambient Temperature (TmpAmb)
    ///
    /// Ambient temperature.
    pub ambient_temperature: i16,
    /// Cabinet Temperature (TmpCab)
    ///
    /// Cabinet temperature.
    pub cabinet_temperature: i16,
    /// Heat Sink Temperature (TmpSnk)
    ///
    /// Heat sink temperature.
    pub heat_sink_temperature: i16,
    /// Transformer Temperature (TmpTrns)
    ///
    /// Transformer temperature.
    pub transformer_temperature: i16,
    /// IGBT/MOSFET Temperature (TmpSw)
    ///
    /// IGBT/MOSFET temperature.
    pub igbt_mosfet_temperature: i16,
    /// Other Temperature (TmpOt)
    ///
    /// Other temperature.
    pub other_temperature: i16,
    /// Watts L1 (WL1)
    ///
    /// Active power L1.
    pub watts_l1: i16,
    /// VA L1 (VAL1)
    ///
    /// Apparent power L1.
    pub va_l1: i16,
    /// Var L1 (VarL1)
    ///
    /// Reactive power L1.
    pub var_l1: i16,
    /// PF L1 (PFL1)
    ///
    /// Power factor phase L1.
    pub pf_l1: i16,
    /// Amps L1 (AL1)
    ///
    /// Current phase L1.
    pub amps_l1: i16,
    /// Phase Voltage L1-L2 (VL1L2)
    ///
    /// Phase voltage L1-L2.
    pub phase_voltage_l1_l2: u16,
    /// Phase Voltage L1-N (VL1)
    ///
    /// Phase voltage L1-N.
    pub phase_voltage_l1_n: u16,
    /// Total Watt-Hours Inj L1 (TotWhInjL1)
    ///
    /// Total active energy injected L1.
    pub total_watt_hours_inj_l1: u64,
    /// Total Watt-Hours Abs L1 (TotWhAbsL1)
    ///
    /// Total active energy absorbed L1.
    pub total_watt_hours_abs_l1: u64,
    /// Total Var-Hours Inj L1 (TotVarhInjL1)
    ///
    /// Total reactive energy injected L1.
    pub total_var_hours_inj_l1: u64,
    /// Total Var-Hours Abs L1 (TotVarhAbsL1)
    ///
    /// Total reactive energy absorbed L1.
    pub total_var_hours_abs_l1: u64,
    /// Watts L2 (WL2)
    ///
    /// Active power L2.
    pub watts_l2: i16,
    /// VA L2 (VAL2)
    ///
    /// Apparent power L2.
    pub va_l2: i16,
    /// Var L2 (VarL2)
    ///
    /// Reactive power L2.
    pub var_l2: i16,
    /// PF L2 (PFL2)
    ///
    /// Power factor L2.
    pub pf_l2: i16,
    /// Amps L2 (AL2)
    ///
    /// Current L2.
    pub amps_l2: i16,
    /// Phase Voltage L2-L3 (VL2L3)
    ///
    /// Phase voltage L2-L3.
    pub phase_voltage_l2_l3: u16,
    /// Phase Voltage L2-N (VL2)
    ///
    /// Phase voltage L2-N.
    pub phase_voltage_l2_n: u16,
    /// Total Watt-Hours Inj L2 (TotWhInjL2)
    ///
    /// Total active energy injected L2.
    pub total_watt_hours_inj_l2: u64,
    /// Total Watt-Hours Abs L2 (TotWhAbsL2)
    ///
    /// Total active energy absorbed L2.
    pub total_watt_hours_abs_l2: u64,
    /// Total Var-Hours Inj L2 (TotVarhInjL2)
    ///
    /// Total reactive energy injected L2.
    pub total_var_hours_inj_l2: u64,
    /// Total Var-Hours Abs L2 (TotVarhAbsL2)
    ///
    /// Total reactive energy absorbed L2.
    pub total_var_hours_abs_l2: u64,
    /// Watts L3 (WL3)
    ///
    /// Active power L3.
    pub watts_l3: i16,
    /// VA L3 (VAL3)
    ///
    /// Apparent power L3.
    pub va_l3: i16,
    /// Var L3 (VarL3)
    ///
    /// Reactive power L3.
    pub var_l3: i16,
    /// PF L3 (PFL3)
    ///
    /// Power factor L3.
    pub pf_l3: i16,
    /// Amps L3 (AL3)
    ///
    /// Current L3.
    pub amps_l3: i16,
    /// Phase Voltage L3-L1 (VL3L1)
    ///
    /// Phase voltage L3-L1.
    pub phase_voltage_l3_l1: u16,
    /// Phase Voltage L3-N (VL3)
    ///
    /// Phase voltage L3-N.
    pub phase_voltage_l3_n: u16,
    /// Total Watt-Hours Inj L3 (TotWhInjL3)
    ///
    /// Total active energy injected L3.
    pub total_watt_hours_inj_l3: u64,
    /// Total Watt-Hours Abs L3 (TotWhAbsL3)
    ///
    /// Total active energy absorbed L3.
    pub total_watt_hours_abs_l3: u64,
    /// Total Var-Hours Inj L3 (TotVarhInjL3)
    ///
    /// Total reactive energy injected L3.
    pub total_var_hours_inj_l3: u64,
    /// Total Var-Hours Abs L3 (TotVarhAbsL3)
    ///
    /// Total reactive energy absorbed L3.
    pub total_var_hours_abs_l3: u64,
    /// Throttling In Pct (ThrotPct)
    ///
    /// Throttling in pct of maximum active power.
    pub throttling_in_pct: u16,
    /// Throttle Source Information (ThrotSrc)
    ///
    /// Active throttling source.
    pub throttle_source_information: u32,
    /// Current Scale Factor (A_SF)
    ///
    /// Current scale factor.
    pub current_scale_factor: i16,
    /// Voltage Scale Factor (V_SF)
    ///
    /// Voltage scale factor.
    pub voltage_scale_factor: i16,
    /// Frequency Scale Factor (Hz_SF)
    ///
    /// Frequency scale factor.
    pub frequency_scale_factor: i16,
    /// Active Power Scale Factor (W_SF)
    ///
    /// Active power scale factor.
    pub active_power_scale_factor: i16,
    /// Power Factor Scale Factor (PF_SF)
    ///
    /// Power factor scale factor.
    pub power_factor_scale_factor: i16,
    /// Apparent Power Scale Factor (VA_SF)
    ///
    /// Apparent power scale factor.
    pub apparent_power_scale_factor: i16,
    /// Reactive Power Scale Factor (Var_SF)
    ///
    /// Reactive power scale factor.
    pub reactive_power_scale_factor: i16,
    /// Active Energy Scale Factor (TotWh_SF)
    ///
    /// Active energy scale factor.
    pub active_energy_scale_factor: i16,
    /// Reactive Energy Scale Factor (TotVarh_SF)
    ///
    /// Reactive energy scale factor.
    pub reactive_energy_scale_factor: i16,
    /// Temperature Scale Factor (Tmp_SF)
    ///
    /// Temperature scale factor.
    pub temperature_scale_factor: i16,
    /// Manufacturer Alarm Info (MnAlrmInfo)
    ///
    /// Manufacturer alarm information. Valid if MANUFACTURER_ALRM indication is active.
    pub manufacturer_alarm_info: [c_char; 64],
}

impl ReadAdapter for Model701StatefulAdapter {
    fn ac_wiring_type(&self) -> AcType {
        self.ac_wiring_type
    }

    fn operating_state(&self) -> Option<St> {
        Some(self.operating_state)
    }

    fn inverter_state(&self) -> Option<InvSt> {
        Some(self.inverter_state)
    }

    fn grid_connection_state(&self) -> Option<ConnSt> {
        Some(self.grid_connection_state)
    }

    fn alarm_bitfield(&self) -> Option<u32> {
        Some(self.alarm_bitfield)
    }

    fn der_operational_characteristics(&self) -> Option<u32> {
        Some(self.der_operational_characteristics)
    }

    fn active_power(&self) -> Option<i16> {
        Some(self.active_power)
    }

    fn apparent_power(&self) -> Option<i16> {
        Some(self.apparent_power)
    }

    fn reactive_power(&self) -> Option<i16> {
        Some(self.reactive_power)
    }

    fn power_factor(&self) -> Option<i16> {
        Some(self.power_factor)
    }

    fn total_ac_current(&self) -> Option<i16> {
        Some(self.total_ac_current)
    }

    fn voltage_ll(&self) -> Option<u16> {
        Some(self.voltage_ll)
    }

    fn voltage_ln(&self) -> Option<u16> {
        Some(self.voltage_ln)
    }

    fn frequency(&self) -> Option<u32> {
        Some(self.frequency)
    }

    fn total_energy_injected(&self) -> Option<u64> {
        Some(self.total_energy_injected)
    }

    fn total_energy_absorbed(&self) -> Option<u64> {
        Some(self.total_energy_absorbed)
    }

    fn total_reactive_energy_inj(&self) -> Option<u64> {
        Some(self.total_reactive_energy_inj)
    }

    fn total_reactive_energy_abs(&self) -> Option<u64> {
        Some(self.total_reactive_energy_abs)
    }

    fn ambient_temperature(&self) -> Option<i16> {
        Some(self.ambient_temperature)
    }

    fn cabinet_temperature(&self) -> Option<i16> {
        Some(self.cabinet_temperature)
    }

    fn heat_sink_temperature(&self) -> Option<i16> {
        Some(self.heat_sink_temperature)
    }

    fn transformer_temperature(&self) -> Option<i16> {
        Some(self.transformer_temperature)
    }

    fn igbt_mosfet_temperature(&self) -> Option<i16> {
        Some(self.igbt_mosfet_temperature)
    }

    fn other_temperature(&self) -> Option<i16> {
        Some(self.other_temperature)
    }

    fn watts_l1(&self) -> Option<i16> {
        Some(self.watts_l1)
    }

    fn va_l1(&self) -> Option<i16> {
        Some(self.va_l1)
    }

    fn var_l1(&self) -> Option<i16> {
        Some(self.var_l1)
    }

    fn pf_l1(&self) -> Option<i16> {
        Some(self.pf_l1)
    }

    fn amps_l1(&self) -> Option<i16> {
        Some(self.amps_l1)
    }

    fn phase_voltage_l1_l2(&self) -> Option<u16> {
        Some(self.phase_voltage_l1_l2)
    }

    fn phase_voltage_l1_n(&self) -> Option<u16> {
        Some(self.phase_voltage_l1_n)
    }

    fn total_watt_hours_inj_l1(&self) -> Option<u64> {
        Some(self.total_watt_hours_inj_l1)
    }

    fn total_watt_hours_abs_l1(&self) -> Option<u64> {
        Some(self.total_watt_hours_abs_l1)
    }

    fn total_var_hours_inj_l1(&self) -> Option<u64> {
        Some(self.total_var_hours_inj_l1)
    }

    fn total_var_hours_abs_l1(&self) -> Option<u64> {
        Some(self.total_var_hours_abs_l1)
    }

    fn watts_l2(&self) -> Option<i16> {
        Some(self.watts_l2)
    }

    fn va_l2(&self) -> Option<i16> {
        Some(self.va_l2)
    }

    fn var_l2(&self) -> Option<i16> {
        Some(self.var_l2)
    }

    fn pf_l2(&self) -> Option<i16> {
        Some(self.pf_l2)
    }

    fn amps_l2(&self) -> Option<i16> {
        Some(self.amps_l2)
    }

    fn phase_voltage_l2_l3(&self) -> Option<u16> {
        Some(self.phase_voltage_l2_l3)
    }

    fn phase_voltage_l2_n(&self) -> Option<u16> {
        Some(self.phase_voltage_l2_n)
    }

    fn total_watt_hours_inj_l2(&self) -> Option<u64> {
        Some(self.total_watt_hours_inj_l2)
    }

    fn total_watt_hours_abs_l2(&self) -> Option<u64> {
        Some(self.total_watt_hours_abs_l2)
    }

    fn total_var_hours_inj_l2(&self) -> Option<u64> {
        Some(self.total_var_hours_inj_l2)
    }

    fn total_var_hours_abs_l2(&self) -> Option<u64> {
        Some(self.total_var_hours_abs_l2)
    }

    fn watts_l3(&self) -> Option<i16> {
        Some(self.watts_l3)
    }

    fn va_l3(&self) -> Option<i16> {
        Some(self.va_l3)
    }

    fn var_l3(&self) -> Option<i16> {
        Some(self.var_l3)
    }

    fn pf_l3(&self) -> Option<i16> {
        Some(self.pf_l3)
    }

    fn amps_l3(&self) -> Option<i16> {
        Some(self.amps_l3)
    }

    fn phase_voltage_l3_l1(&self) -> Option<u16> {
        Some(self.phase_voltage_l3_l1)
    }

    fn phase_voltage_l3_n(&self) -> Option<u16> {
        Some(self.phase_voltage_l3_n)
    }

    fn total_watt_hours_inj_l3(&self) -> Option<u64> {
        Some(self.total_watt_hours_inj_l3)
    }

    fn total_watt_hours_abs_l3(&self) -> Option<u64> {
        Some(self.total_watt_hours_abs_l3)
    }

    fn total_var_hours_inj_l3(&self) -> Option<u64> {
        Some(self.total_var_hours_inj_l3)
    }

    fn total_var_hours_abs_l3(&self) -> Option<u64> {
        Some(self.total_var_hours_abs_l3)
    }

    fn throttling_in_pct(&self) -> Option<u16> {
        Some(self.throttling_in_pct)
    }

    fn throttle_source_information(&self) -> Option<u32> {
        Some(self.throttle_source_information)
    }

    fn current_scale_factor(&self) -> Option<i16> {
        Some(self.current_scale_factor)
    }

    fn voltage_scale_factor(&self) -> Option<i16> {
        Some(self.voltage_scale_factor)
    }

    fn frequency_scale_factor(&self) -> Option<i16> {
        Some(self.frequency_scale_factor)
    }

    fn active_power_scale_factor(&self) -> Option<i16> {
        Some(self.active_power_scale_factor)
    }

    fn power_factor_scale_factor(&self) -> Option<i16> {
        Some(self.power_factor_scale_factor)
    }

    fn apparent_power_scale_factor(&self) -> Option<i16> {
        Some(self.apparent_power_scale_factor)
    }

    fn reactive_power_scale_factor(&self) -> Option<i16> {
        Some(self.reactive_power_scale_factor)
    }

    fn active_energy_scale_factor(&self) -> Option<i16> {
        Some(self.active_energy_scale_factor)
    }

    fn reactive_energy_scale_factor(&self) -> Option<i16> {
        Some(self.reactive_energy_scale_factor)
    }

    fn temperature_scale_factor(&self) -> Option<i16> {
        Some(self.temperature_scale_factor)
    }

    fn manufacturer_alarm_info(&self) -> Option<&CStr> {
        Some(unsafe { CStr::from_ptr(self.manufacturer_alarm_info.as_ptr()) })
    }
}

/// C-FFI dispatch descriptor for SunSpec model 701. A C `SunspecModelBinding` points
/// at this static, so the service functions dispatch with no model-id lookup.
#[unsafe(no_mangle)]
pub static SUNSPEC_MODEL_701: StaticModelSpec = StaticModelSpec {
    id: 701,
    length: model_701_c_length,
    writable: false,
    visit_read: model_701_c_visit_read,
    visit_write: model_701_c_visit_write,
};

fn model_701_c_length(_repeat_count_0: u16, _repeat_count_1: u16) -> u16 {
    (Model701).model_length()
}

/// # Safety
/// For `kind` 1 or 2, `adapter` must point to a live `Model701{Stateful,Callback}Adapter`,
/// valid for the duration of the call.
unsafe fn model_701_c_visit_read(
    kind: u8,
    adapter: *const c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &mut WritableRegisterBuffer<'_>,
) {
    let model = Model701;
    let adapter: Option<&dyn ReadAdapter> = match kind {
        1 => Some(unsafe { &*(adapter as *const Model701StatefulAdapter) } as &dyn ReadAdapter),
        2 => Some(unsafe { &*(adapter as *const Model701CallbackAdapter) } as &dyn ReadAdapter),
        _ => None,
    };
    cursor.visit_source_block(model.model_length(), |offset, from, len| {
        let mut block = buffer.slice(from, len);
        match adapter {
            Some(adapter) => model.traverse_points_read(adapter, &mut block, offset),
            None => {
                block.fill(&[0xff, 0xff]);
                Ok(())
            }
        }
    });
}

/// # Safety
/// As for [`model_701_c_visit_read`], and `adapter` must be uniquely borrowable for the call.
unsafe fn model_701_c_visit_write(
    kind: u8,
    adapter: *mut c_void,
    _repeat_count_0: u16,
    _repeat_count_1: u16,
    cursor: &mut Cursor<ModbusException>,
    buffer: &ReadableRegisterBuffer<'_>,
) {
    let _ = (kind, adapter, buffer);
    let model = Model701;
    cursor.visit_source_block(model.model_length(), |_, _, _| {
        Err(ModbusException::IllegalDataAddress)
    });
}
