[package]
name = "sunspec-gen"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
codegen = "0.3.0"
glob = "0.3.3"
heck = "0.5.0"
serde = "1.0.228"
serde_json = "1.0.150"
typify = "0.7.0"
schemars = "0.8"
rustfmt-wrapper = "0.2.1"

[build-dependencies]
serde_json = "1.0.150"
typify = "0.7.0"
schemars = "0.8"
rustfmt-wrapper = "0.2.1"
